### ISSUE TITLE
.desktop file does not pass desktop-file-validate

### ISSUE THREAD

**Issue by probonopd** [jupyterlab/jupyterlab-desktop#125]
```
jupyterlab_app.desktop: error: file contains key "Category" in group "Desktop Entry", but keys extending the format should start with "X-"
```

The key is called `Categories=`.

Please run the .desktop file through `desktop-file-validate` to make sure it passes validation.

Reference:
https://travis-ci.org/AppImage/appimage.github.io/builds/268769623#L578

**Comment by probonopd** [comment]
Still:

`jupyterlab_app.desktop: error: file contains key "Category" in group "Desktop Entry", but keys extending the format should start with "X-"`.

References:
* https://github.com/AppImage/appimage.github.io/pull/56
* https://travis-ci.org/AppImage/appimage.github.io/builds/360879895#L566

**Comment by probonopd** [comment]
Unfortunately we can't test PRs yet. But I'll be happy to run the test on the next release. Or you do a build and then post its resulting `*.desktop` file. Thanks!

**Comment by declanvk** [comment]
I'll reopen this until we verify that the `.desktop` file passes validation

**Comment by mbektas** [comment]
not relevant to latest version
