### ISSUE TITLE
Supporting most of the features

### ISSUE THREAD

**Issue by suyashmahar** [jupyterlab/jupyterlab-desktop#186]
I wrote a similar app as a personal project in an effort to get native desktop experience and learn some HTML, CSS and JS: 

https://github.com/suyashmahar/europa

This was a hobby project, so the code isn't the prettiest (I never wrote any HTML, CSS or JS before), although it is documented. 

Europa has most features that you'd expect: (1) Remote servers, (2) starting new local server and (3) Shortcuts (like @adammenges 's project). 

This covers the following open issues: 
#48 (multiple servers) 
#181 (abandoned) 
#169 (changing python interpreter) 
#43 (User friendly error messages)
#161 (saving settings?)
#15 (remote server)

I didn't know about jupyterlab_app when I started, though I would have still preferred to write my own since I had a bunch of free time and wanted to learn something new.

Europa is licensed as GPLv3, but, I'm willing to let the jupyterlab organization take over it and re-license it as BSD 3 clause. Would love to hear from someone at JupyterLab Org if this is sounds interesting.

\- Suyash

**Comment by jtpio** [comment]
Thanks @suyashmahar, this looks great!

Pinging @afshin who is also interested in this.

**Comment by mbektas** [comment]
most of the mentioned features already implemented
