### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by kobus-v-schoor** [jupyterlab/jupyterlab-desktop#225]
### Problem

I think it would be great if there was a Flatpak package as an alternative Linux installer. Flatpak is ideal for this kind of app, and I believe there are multiple electron apps already packaged on Flathub that can provide a base to work from.

### Proposed Solution

A Flatpak package just needs to be created and published to Flathub. I believe the existing deb installer can easily be used to create the package. I have previously packaged Flatpak packages (https://github.com/flathub/org.openhantek.OpenHantek6022) - so I'd be happy to help. However Flathub prefers if the official maintainers publish/maintain the package (if you don't want to maintain the package you need to say so here, then I just need to refer to this issue and they'll allow me to maintain the package)

### Additional context

An example Electron app that I found that is published on Flathub is here: https://github.com/flathub/io.github.liberodark.OpenDrive/ - it might prove useful as an example to work from

**Comment by kobus-v-schoor** [comment]
I've done some initial work on the Flatpak app here: https://github.com/kobus-v-schoor/flathub/tree/org.jupyter.JupyterLab - it's successfully building and seems to be running. The manifest still needs some cleaning up, but the basics are there.

**Comment by mbektas** [comment]
Thanks @kobus-v-schoor, we will explore this alternative.

**Comment by imLinguin** [comment]
Any update on this?

**Comment by kobus-v-schoor** [comment]
I'll open up the necessary PRs to get the package published, most of the work is already done so it shouldn't be too much work

**Comment by JasonWeill** [comment]
Closing in favor of #580.
