### ISSUE TITLE
Displaying available kernels

### ISSUE THREAD

**Issue by psychemedia** [jupyterlab/jupyterlab-desktop#226]
Hi

Just trying a first run on a Mac and I noticed a couple of things:

- JupyterLab-app opened with a couple of open notebooks that matched notebooks I had opened using a local notebook running already in browser tabs;
- JupyterLab-app opened into a browser directory on a path that JuypyterLab-app shouldn't have known about;
- multiple kernels are shown as notebook opening options JupyterLab-app launcher:
![image](https://user-images.githubusercontent.com/82988/134421515-242f2d73-e9a6-47d9-917c-258c53c3524e.png)

The *Python 3 (ipykernel)* kernel opens a kernel that seems to be the bundled kernel (`import site; site.getsitepackages()` gives `['/Applications/JupyterLab.app/Contents/Resources/jlab_server/lib/python3.8/site-packages']`. This kernel has the same name as the default kernel in my locally running Jupyter server. In the local browser accessed JupyterLab, the kernel with the same name connects a local kernel (not the JuyterLab-app bundled kernel).

If I have an open notebook in JupyterLab app, when I create a new local server JupyterLab browser window, the notebook open in the app opens in the local browser window (?!) but runs against a different kernel, albeit with the same name:

![image](https://user-images.githubusercontent.com/82988/134422278-97a55588-db58-4f60-93b1-a6fe484dae12.png)

I guess my issue is:

- the shipped kernel name may clash with a local kernel name; which kernel is used depends on which JupyterLab is running (app or local browser accessed server); *this is confusing;*
- the JupyterLab-app and local JupyterLab server seem to be able to share state re: current directory and currently opened notebooks(?!); *this is quite scary and I suspect could lead to all sorts of mishaps depending on what is shared and which server last wrote whatever state is shared);
- I seem to be able to connect to a local R kernel, but trying to connect to other local Py kernels seems to hang the app (that said, my other Py kernels may not be fully working or may be slow to start).

**Comment by krassowski** [comment]
Good points. I think that it largely depends on configuration - if you have kernels installed on system level, any instance of JupyterLab will list those (whether in a virtual environment or not).

> the JupyterLab-app and local JupyterLab server seem to be able to share state re: current directory and currently opened notebooks(?!); *this is quite scary and I suspect could lead to all sorts of mishaps depending on what is shared and which server last wrote whatever state is shared);

This happens with Jupyter(Lab) config and sessions in general; it is annoying because I get my workspace reset from time to time when I open a new session in a different environment. I think that this needs discussion in main JupyterLab repo (if there is not any).

**Comment by psychemedia** [comment]
@krassowski Re: installed kernels, what confused me was how the Python3 kernel is different in the desktop app versus the local server environment. It would be useful if the desktop app kernel were given a unique name/identity, rather than than trumping any local Python 3 kernel?

Re: workspace clobbering... I've yet to properly explore workspaces, but I was considering using JupyterLab-app for some particular customised workspace layouts for teaching purposes, separate from my local JupyterLab sessions. If I keep clobbering my workspaces whenever I switch context, that doesn't feel right! I raised a related issue here: https://github.com/jupyterlab/jupyterlab/issues/11120

**Comment by mbektas** [comment]
@psychemedia there has been several updates to the Desktop app to isolate workspaces and to work with different Python environments. Could you give it another try and let us know if you are having any major issues?
