### ISSUE TITLE
jupyterlabb_app fails to start on Ubuntu 20.04 with "JupyterServer Not Found"

### ISSUE THREAD

**Issue by ghshephard** [jupyterlab/jupyterlab-desktop#228]
## Description

Upon startup get the following error:

Jupyter Server Not Found
We were unable to launch a Jupyter server, which is a prerequisite for JupyterLab Native. If Jupyter is installed as a python module, but the python executable is not in your PATH, specify the executable location below. Otherwise, try installing or updating Jupyter. The Jupyter notebook version must be 4.3.0 or greater.

## Reproduce

This error may be difficult to reproduce as I expect it's an issue related to my local environment.   But it happens 100% of the time.  jupyter-lab works fine both before and after trying to start jupyterlab_app.  I've also tried starting jupyterlab_app both with, and without jupyter-lab running.

## Environment 

OS: Ubuntu 20.04
Browsers: Not sure it's relevant to the thick app, but  Chrome Version 91.0.4472.164  (64-bit)
Jupyter Versions:

$ jupyter --version
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.14.0
ipykernel        : 5.2.1
jupyter client   : 6.1.3
jupyter lab      : 2.1.2
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.6
traitlets        : 4.3.3

## Notes

I didn't find a great deal about *how* to start the application, what changes I need to make to my environment, or what has to be running already.   

I did try "Setting Path" to be my virtualenv Jupyter (I was, of course, in the venv prior to starting JupyterLabs):
/home/shephard/.virtualenvs/py38/lib/python3.8/site-packages/jupyter.py

I also tried running jupyterlab_app both with, and without the Jupyter server running - still no luck.

If someone could throw together a quick readme about what needs to be installed, and running prior to running jupyterlab_app - that might answer a lot of these questions.  

</pre>
</details>

**Comment by krassowski** [comment]
How are you starting JupyterLab-App? Are you using command line, or the icon in the Ubuntu launcher?

**Comment by ghshephard** [comment]
Tried both ways - Though - if you start it from the Icon - how will it know what venv to find your jupyter instance in?  
I'm presuming you need to pip install jupyter_lab prior to installing jupyterlab_app?  And you have to somehow inform jupyterlab_app where to find your venv?  If there is an installation or readme somewhere that I missed, I would love to dig into it.

**Comment by CarlosGrohmann** [comment]
I just installed it in Ubuntu 21.04 and it worked fine. Is it possible for you to update your system?

**Comment by Czaki** [comment]
> Tried both ways - Though - if you start it from the Icon - how will it know what venv to find your jupyter instance in?

When I start from the icon (deb installed package) it uses the bundled version of jupyter.

**Comment by DataBytzAI** [comment]
Same issue with me on Ubuntu:

We were unable to launch a Jupyter server, which is a prerequisite for JupyterLab Native. If Jupyter is installed as a python module, but the python executable is not in your PATH, specify the executable location below. Otherwise, try installing or updating Jupyter. The Jupyter notebook version must be 4.3.0 or greater.

However, it does seem that the installed path is available in PATH:

/home/allen/anaconda3/lib/python3.8/site-packages/jupyter_server

**Comment by castorfou** [comment]
I have the same issue from ubuntu 20.04.
That would be good to have a simple but complete user guide.

What I have got from instructions is to install .deb to get jupyter-lab desktop version. It goes to /opt/JupyterLab
To chown -R this installation folder to allow users to launch it.

I have multiple python environments on my laptop, managed with miniconda.
My 'base' environment is very minimalist without jupyter packages.

I have tried to install jupyterlab in base just to see if it was expected. But it doesn't help. Still the same error message : Jupyer Server not found.
What are the pre-requisites for jupyterlab desktop to run properly? Jupyterlab server should be installed separately ? in which python env ? Should it be running as a service ? I am blind here.

**Comment by AndrewAmmerlaan** [comment]
I have a similar issue on Gentoo, extracting the deb or rpm and running `/opt/JupyterLab/jupyterlab_app` results in "Jupyter Server Not Found" even though jupyerlab(_server) etc are all installed and I can run it in the browser just fine. The root of the issues seems to be that the "Choose Path" button doesn't do anything, selecting a system python executable (e.g. `/usr/bin/python3` just results in the same error about not being able to find `/opt/JupyterLab/jupyterlab_app/resources/jlab_server/bin/python`.

**Comment by krassowski** [comment]
Hi everyone, we are making progress on this one. I posted an updated in #238 and would like to close this one to focus the conversation over there. Hopefully the next release will solve most of the failure modes.
