### ISSUE TITLE
Failed lanching in  macos big sur 11.6

### ISSUE THREAD

**Issue by nicozhang** [jupyterlab/jupyterlab-desktop#229]
![image](https://user-images.githubusercontent.com/1912794/134436384-32c8ab8c-c560-40d2-b550-8b385e60a260.png)
only show this for quit a long time

**Comment by selasley** [comment]
On my Mac the splash screen stayed up for a long time on the first launch of JupyterLap.app but the main jupyterlab window eventually showed up.  The main window came up quicker on subsequent launches.

macOS 11.6
I'm not sure if these matter but they are installed
python 3.9.7 from python.org
SageMath-9-4.app  version: 9.4
R.app version: 4.1.0
Julia-1.6.app version: 1.6.1

**Comment by adammenges** [comment]
Yeah I was able to run it too, FWIW

**Comment by mbektas** [comment]
closing since it is too old. please test with the latest app version and create a new issue if having problems.
