### ISSUE TITLE
Keyboard arrow support in terminal

### ISSUE THREAD

**Issue by Czaki** [jupyterlab/jupyterlab-desktop#231]
### Problem

When I open a terminal in jupyter lab app I see that tab completion and using the arrows to navigate history or even moving through command does not work. 

### Proposed Solution

Start `bash` or `zsh` instead of `sh` shell. 

### Additional context

Run from icon (gnome launcher)
Version 3.1.12-1
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 21.04
Release:	21.04
Codename:	hirsute

**Comment by krassowski** [comment]
Hi @Czaki thanks for opening this issue. I think that this should be addressed upstream in JupyterLab. There is already an issue for allowing to customize the terminal shell: https://github.com/jupyterlab/jupyterlab/issues/4034 and a pull request here: https://github.com/jupyterlab/jupyterlab/pull/10203 (but it seems that no one is currently working on this one - feel free to contribute).
