### ISSUE TITLE
Picking up wrong conda

### ISSUE THREAD

**Issue by ianhbell** [jupyterlab/jupyterlab-desktop#239]
## Description

I just installed Jupyter Lab and am excited to get to know it as a long time python and jupyter user.  An immediate issue I ran into is that I need to install other packages in the conda environment but the conda that it picks up is the *system* conda rather than the JupyterLab one.  Pip gets pushed properly to the head of the PATH. Here is a screenshot showing the problem:

![image](https://user-images.githubusercontent.com/11966765/134594625-191e4b24-fd6f-4a2e-912c-e5ede3b822e8.png)

## Reproduce

Downloaded jupyterlab app to a machine that already had Miniconda installed

## Expected behavior

conda is first on path so that 

``!conda install sympy``

## Context

- Operating System and version: windows 10
- Browser and version: Chrome 94.0.4606.54 (Official Build) (64-bit)
- JupyterLab version: 3.1.12-1

**Comment by mbektas** [comment]
@ianhbell thanks for reporting this issue. can you try this as a workaround for now:
```bash
import sys
!{sys.executable} -m pip install sympy
```
or
```bash
import sys
!conda install -c conda-forge --yes --prefix {sys.prefix} sympy
```

**Comment by ianhbell** [comment]
First one doesn't help (isn't needed) because JupyterLab's pip is first on path (see above).  Second one does work.

**Comment by mbektas** [comment]
resolved
