### ISSUE TITLE
Option to remove the leave/stay prompt?

### ISSUE THREAD

**Issue by jpivarski** [jupyterlab/jupyterlab-desktop#247]
This is minor, but I'd like to be able to remove the "Do you want to leave? Changes you made may not be saved." dialog box when I close the JupyterLab_app window. I fully understand why it's there by default, I'd just like the ability to remove it. I like to live dangerously.

The reason is that I see JupyterLab_app as a way to "pop into Jupyter" quickly (I already have a keyboard shortcut for it). That was the problem with regular Jupyter: I'd have to start a server in a terminal and open it in a web browser tab—too much fuss for a 3-second test. The way that it creates Untitled.ipynb files everywhere is also a problem, but I've fixed that: I open it in `/tmp`. This is the same way that I use Emacs `*scratch*` buffers and short-lived terminals: there's value in having some kinds of work be ephemeral.

> Here I was born, and there I died. It was only a moment for you; you took no notice.

**Comment by A3EKV** [comment]
My concern is completely different than yours. I find it frusturating when the default UX changes even for a dialog box. We are, almost, all accustomed to "yes", "no", "cancel" button, you can't simply change that to something else. It's hard to explain why this is wrong  but that's wrong. The dialog box should use the defautlt buttons not some arbitrary "stay', or "leave" options! it is very confusing.

**Comment by mbektas** [comment]
closing since the behavior is different now.
