### ISSUE TITLE
Cannot use git extension on jupyterlab_app, even though I can see the tab.

### ISSUE THREAD

**Issue by hellojinwoo** [jupyterlab/jupyterlab-desktop#264]
![image](https://user-images.githubusercontent.com/34431729/135223237-4fa6e186-9436-41ad-adfb-1be79b4f0da2.png)

Even though I have installed jupyter_git and used it on usual jupyter lab environment, I cannot use it on jupyterlab_app. 
I can see the tab for `git`, but when I click the tab, it shows only help. 

Plus, why can't I see the extension on the left side bar in the jupyterlab_app?

**Comment by hellojinwoo** [comment]
Plus, is there a way to use the extension manager on the jupyterlab_app? I cannot see the extension manager at the sidebar of the jupyterlab_app

**Comment by krassowski** [comment]
Extension manager is currently disabled in JupyterLab-app, but it is something that we will definitely want to enable in the future. I personally think that it would be best to enable after rewriting it to work with prebuilt extensions but no one volunteered to do so as for today.

**Comment by krassowski** [comment]
The work in #322 will enable using `jupyterlab-git` and other prebuilt extensions. You will need to:

1. install the new version (once released, or right now from the build artifacts if you want to help to test and know what you are doing),
2. follow the [Python Environment Customization Guide](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#Customizing-the-Bundled-Python-Environment) instructions differ between operating systems
3. Install the `jupyterlab-git` extension, assuming that you have `git` available: `%pip install jupyterlab-git` from a notebook (see the customization guide above)
4. restart the app and enjoy

![Screenshot from 2021-10-31 13-24-25](https://user-images.githubusercontent.com/5832902/139585915-5d276f51-605a-4b88-ae9e-d83d0a1df3d4.png)
