### ISSUE TITLE
No way to specify gateway url

### ISSUE THREAD

**Issue by sa-** [jupyterlab/jupyterlab-desktop#268]
## Description

Hello wonderful people.

I usually start jupyter lab with a gateway url, but I can't seem to do that here :(

## Reproduce

1. Open the jupyter lab app
2. Try to enter the gateway url somewhere

## Expected behavior

The gateway url is entered somewhere, and I can use my shiny remote kernels.

Maybe this is feedback for jupyter lab and not the app itself, but it would be nice to add/remove kernel gateways from the launcher tab.

One possible solution is to have a server list on the left, similar to what Lens has:
![image](https://user-images.githubusercontent.com/1297369/135713055-c58fe850-b464-4463-994e-5ddc3e49d2d6.png)

This way one can create new instances of jupyter with different command line args and switch between them.

The photon list component could be used to make this: photonkit.com/components/

## Context

- Operating System and version: 
- Browser and version: 
- JupyterLab version: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter lab` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by sa-** [comment]
I see that there is a command line now, could there be a way to add cmd line args to it?

**Comment by mbektas** [comment]
you can now customize server launch arguments with the newest version 3.6.1-2. please install it and check the [user guide](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#server-launch-arguments) for instructions.
