### ISSUE TITLE
"Export Notebook as..." does not work

### ISSUE THREAD

**Issue by connorferster** [jupyterlab/jupyterlab-desktop#270]
## Description

First, I am so very excited for a JupyterLab app. Thank you to the Jupyter team for this incredible contribution and gift! I am particularly excited to promote it as a general engineering tool. 

I tried a simple calculation script and went to export the notebook using the "Export Notebook as..." functionality in the File menu. Immediately a blank window popped up. I waited to see if it would populate or otherwise trigger some process but it does not seem to. 

It looks as follows:
![image](https://user-images.githubusercontent.com/38441489/135531948-3411ece7-276f-465e-91fd-5368dbab9ddc.png)

I tried exporting as HTML and Latex but neither seemed to do anything but both brought up this window. I am guessing this functionality is not currently implemented yet?

Many thanks!

## Reproduce

1. Create a new Notebook and fill it with some stuff
2. Click on 'File' in the menu
3. Scroll down to 'Export Notebook as...' and select HTML or Latex
4. See window

## Expected behavior

Either a browser window opens to display the output (HTML?) or a system file dialogue pops up asking where I would like to save the exported Notebook.

## Context

- Operating System and version: Windows 10
- Browser and version: Firefox 92.0.1
- JupyterLab version: App: Version 3.1.13-1

**Comment by krassowski** [comment]
It does not work on Ubuntu either. There is an error showing up in console:

```js
Uncaught (in promise) TypeError: child.location.assign is not a function
    at browser.bundle.js:83613
    at new Promise (<anonymous>)
    at execute (browser.bundle.js:83612)
    at CommandRegistry.execute (browser.bundle.js:126833)
    at RankedMenu.Menu.triggerActiveItem (browser.bundle.js:149582)
    at RankedMenu.Menu._evtMouseUp (browser.bundle.js:149929)
    at RankedMenu.Menu.handleEvent (browser.bundle.js:149728)
```

**Comment by krassowski** [comment]
If `child.location.href = url;` was used instead it would have worked. It might get resolved once we update Electron, but give `location.assign()` has generally lower support (e.g. not supported in Deno) it might be a good idea to switch to `.href` for now in https://github.com/jupyterlab/jupyterlab/blob/88ae23f798c2adfcaea6a8fd0385f23b8aa2b8a1/packages/notebook-extension/src/index.ts#L403-L413. Would you like to make a PR?

**Comment by mbektas** [comment]
@krassowski thanks for debugging the issue. I would try upgrading Electron first to see if that fixes the problem.

**Comment by mbektas** [comment]
@krassowski I tried upgrading Electron but it didn't fix the issue. I will push a PR to jupyterlab as workaround as you suggested.

**Comment by krassowski** [comment]
Closing as fixed in the most recent version.
