### ISSUE TITLE
Full Native Apple Silicon Support (Mac M1)

### ISSUE THREAD

**Issue by cmhatche23** [jupyterlab/jupyterlab-desktop#279]
Do we know if the current MacOS version is fully supported by Apple Silicon (Mac M1), or does this run with Rosetta? If the latter, I would be interested in requesting Mac M1 full support.

**Comment by lexnasser** [comment]
I can confirm that the current MacOS version runs with Rosetta.

+1 on the request for full M1 support.

**Comment by debjitpal5040** [comment]
+1 for apple silicon support

**Comment by s-valent** [comment]
It's actually compiling perfectly fine on m1, you just need to follow the instructions provided.

As for python bundled with application, anaconda is not supported natively, but it is possible to build the whole application without python and then install python elsewhere (brew, python.org, condaforge or anything else), and then choose it on first startup.

**Comment by chrisvander** [comment]
@s-valent how did you build it? Constructor is not available for M1 yet.

**Comment by krassowski** [comment]
How can we make it easier? I understand that Electron already supports M1. If we bundle non-M1 conda constructor with M1 Electron will that help a bit?

**Comment by chrisvander** [comment]
Well, if there were a macos-arm64 build of Constructor on conda-forge I could install it with Miniforge and build the server component + desktop app fairly easily, and then an ARM64 macOS release becomes possible to distribute.

**Comment by krassowski** [comment]
@chrisvander would you mind opening an issue on https://github.com/conda-forge/constructor-feedstock as a first step? I see some instructions on adding the macos-arm64 here: https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/

**Comment by debjitpal5040** [comment]
Now this app has been upgraded to Electron 14. So is this a universal app now for macOS ?

**Comment by lexnasser** [comment]
I cannot speak to whether this is now a universal app, but, even if it is, the app installed by the `JupyterLab-Setup-macOS.pkg` release file continues to run with Rosetta on M1 machines.

**Comment by debjitpal5040** [comment]
Can anyone provide any news/updates on native apple silicon support for jupyterlab desktop app ?

**Comment by cigoic** [comment]
Need Native Apple Silicon support! +1

Just tried `yarn && yarn build && yarn dist:mac`

It won't pass the compiling process, and show some error:

.../dist/mac-arm64/JupyterLab.app/dist/mac/JupyterLab.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libEGL.dylib: No such file or directory

='(

**Comment by tachijuan** [comment]
+1 on Apple Silicon Support

**Comment by mbektas** [comment]
Apple Silicon support is now available with [v3.6.2-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.6.2-1)
