### ISSUE TITLE
Showing only the logo animation in Ubuntu 20.04 

### ISSUE THREAD

**Issue by Binit-Dhakal** [jupyterlab/jupyterlab-desktop#281]
When i open the Jupyter lab app it only shows the starting animation and do nothing. I don't know if there is something fault from my side as i am newbie in this jupyter lab environment but it seem not to work. I dont think i made any mistake regarding installation as its quite easy (just installing the .deb file). 

I have just left it to open for about 10 minutes but its still showing only animation. Should i do more than just installing .deb file or is it a bug?

**Comment by krassowski** [comment]
Thank you! I think that "schema not found" is the most useful message. One possibility would be that you installed the app as a root/sudo user, but are running it as a normal user. Another possibility would be that you have an older (< 3) version of JupyterLab installed. There is also a possibility of an issue with the installer but it seems less likely to me.

**Comment by Binit-Dhakal** [comment]
I think i have installed it using sudo i guess as this is the first version of jupyterlab desktop i am installing(so second option might be incorrect) . 
The downloaded .deb file opens with "Software install" and then it asks for password as it is installed from other source.
 Can you please help, how can i install it as a normal user or run it as sudo / root user(both might work for now)?

I know i can do sudo <app name> to run the app as root user, but tried using "jupyter lab desktop" || "jupyterlab-app" but nothing seems to work from terminal.

**Comment by krassowski** [comment]
The command-line name is `jlab`, so maybe `sudo jlab`? Could you also see if there are any logs in `~/.config/jupyterlab-desktop/logs/main.log` and paste those here, please?

**Comment by mbektas** [comment]
no response for long time. should be fixed in the newer versions.
