### ISSUE TITLE
Broken "View"->"Reload" menu item and accompanying shortcut (⌘R on macOS)

### ISSUE THREAD

**Issue by will-henney** [jupyterlab/jupyterlab-desktop#283]
## Description

If I type ⌘R in a notebook, then I get an error:

> 404 : Not Found
> You are requesting a page that does not exist!

and the app is completely broken (need to quit and relaunch to recover)
![CleanShot 2021-10-07 at 10 59 04@2x](https://user-images.githubusercontent.com/161264/136437114-eeb4ee21-19d1-4355-ade6-10503cf580ae.jpg)

Here is the console output from the developer tools:

![CleanShot 2021-10-07 at 11 01 59@2x](https://user-images.githubusercontent.com/161264/136437195-f58c1abd-4a4d-49b8-828d-514c6702985c.jpg)

## Reproduce

1. Open a notebook
2. Choose "View"->"Reload" from the top-level app menu bar or type ⌘R
3. See error "404 : Not Found"

## Expected behavior

I would expect ⌘R to behave as in the jupyterlab web app in a browser, which is to reload all notebooks from disk.  There is an item "File"->"Reload Notebook from Disk" in the _internal_  menu bar that does this for a single notebook.  This works fine, but it has no default key binding.

## Context

- Operating System and version: macOS Big Sur 11.5.2 - MacBook Pro (16-inch, 2019)
- Browser and version: Desktop app
- JupyterLab version: Version 3.1.13-1 (3.1.13-1)

**Comment by mbektas** [comment]
@will-henney `View` -> `Reload` menu functionality is not implemented and will most likely be removed in future versions. Unfortunately the default implementation is causing the error message you are seeing. What is your use case of reloading the application window? was there a state issue you tried to fix with reloading?

**Comment by dirkroorda** [comment]
See issues #379 and

I needed this kind of refresh in order to get the pre-built extension jupyterlab-vim to work.

Since the last version I noticed that refresh was very quick, i.e. it did not happen. And so I cannot do vim in notebook cells.

So my hope is that either refresh gets re-instated, or another way to get vim in notebook cells is found.

**Comment by mbektas** [comment]
@dirkroorda could you test with the latest? 3.6.1-1. are you still having issues with jupyterlab-vim?

**Comment by mbektas** [comment]
closing since no response for a long time
