### ISSUE TITLE
Menubar disappears when going fullscreen on macOS

### ISSUE THREAD

**Issue by jasongrout** [jupyterlab/jupyterlab-desktop#284]
## Description

On macOS Catalina, the app looks great when a normal non-fullscreen window:
![Screen Shot 2021-10-07 at 8 21 50 PM](https://user-images.githubusercontent.com/192614/136493311-d3cefed3-480b-42e6-8ab4-fc48235e85c2.png)

However, when activating full screen mode by clicking on the green titlebar maximize button, or pressing Ctrl Cmd F, the JupyterLab menubar disappears (I'm talking about the menu bar inside JupyterLab, not the system menubar at the top of the screen), and the application looks like:

![Screen Shot 2021-10-07 at 8 21 58 PM](https://user-images.githubusercontent.com/192614/136493373-4bb7d542-b827-48d8-9851-0e7d477345b7.png)

## Reproduce

1. Open the app
2. Press the green "maximize" button in the titlebar
3. Observe that the JupyterLab menu bar disappears as the app goes to fullscreen.

## Expected behavior

The JupyterLab menu bar to stay visible so we can use menu items while the app is fullscreen.

## Context

- Operating System and version: macos catalina
- Browser and version: Firefox 93
- JupyterLab version: 3.1.13-1

**Comment by will-henney** [comment]
I have also run into this issue in fullscreen on macOS.  I found that a workaround is to toggle the "Simple" UI button, which brings the menu bar back (for a while, at least). 
![CleanShot 2021-10-09 at 19 21 43@2x](https://user-images.githubusercontent.com/161264/136677000-697496bc-eb73-4d78-ae5f-5204734ba1c5.jpg)
