### ISSUE TITLE
Document how to run the app

### ISSUE THREAD

**Issue by lambdaofgod** [jupyterlab/jupyterlab-desktop#286]
It would be nice to know how to actually run the app. I don't see this anywhere in README. Or in the [medium blogpost](https://blog.jupyter.org/jupyterlab-desktop-app-now-available-b8b661b17e9a)

**Comment by krassowski** [comment]
I think that's a good idea. The app is supposed to be run from the GUI of your OS, so it will vary; while I don't think that common applications like Chrome, or Firefox document where to find the icon itself (again, it varies a lot), we probably should mention that this app can be run from the icon found in the (OS-specific) version of menu/dash/desktop, or from command line using `jlab` (which is a new addition, not yet released).

**Comment by lambdaofgod** [comment]
Running with `jlab` which is mentioned in README works. Thanks!
