### ISSUE TITLE
How to install Git?

### ISSUE THREAD

**Issue by chbussler** [jupyterlab/jupyterlab-desktop#287]
I want to install https://github.com/jupyterlab/jupyterlab-git, but am unsure on how to approach this. Would it be possible to add some instructions to the readme? Thank you.

**Comment by hellojinwoo** [comment]
Installing additional JupyterLab Extensions are not supported in the desktop application at the moment. We are considering adding this support in a future release. - Referenced from other questions

**Comment by krassowski** [comment]
I think that this is a duplicate of https://github.com/jupyterlab/jupyterlab-desktop/issues/264. Opening fewer duplicate issues helps prioritize work rather than answering duplicates ;)
