### ISSUE TITLE
Plotly figures don't show up

### ISSUE THREAD

**Issue by A3EKV** [jupyterlab/jupyterlab-desktop#288]
Hello,
using the latest version of this application on Ubuntu 20.04, the plotly figures seems not to work.
Here is an example:
( the output of the figure is empty).

![image](https://user-images.githubusercontent.com/90999345/136595415-727a3463-8827-40ad-bd56-125c8ae586a9.png)

**Comment by kevwilhelm95** [comment]
Also running into this issue. Please advise

**Comment by krassowski** [comment]
I wonder if this could be fixed in a way similar to https://github.com/jupyterlab/retrolab/pull/262.
