### ISSUE TITLE
Getting an error when using  %matplotlib notebook magic

### ISSUE THREAD

**Issue by A3EKV** [jupyterlab/jupyterlab-desktop#291]
On Ubuntu 20.04 with the latest version of this application, when I try to use `%matplotlib notebook`, I get an error as shown in the screenshot below:

![image](https://user-images.githubusercontent.com/90999345/136657135-e2ef171a-9502-413b-928f-c9eeec941926.png)

Here is the code shown in the screenshot:

```
%matplotlib notebook
import numpy as np

import matplotlib.pyplot as plt
x = np.linspace(0, 5, 500)
y = np.cos(x)
plt.scatter(x=x, y=y)
```

**Comment by A3EKV** [comment]
@krassowski
Thank you for the reply. 
Sorry, I thought this has something wrong with Electron implementation or something like that.  Maybe opening this issue here will help future people who will experience the similar issue with this application.

[Meta]: I never heard of JupyterLab before, all I knew is Jupyter notebooks, and thanks to some random newsletter on my email informing me about this application.

Thank you :)

**Comment by krassowski** [comment]
No worries, I'm glad you are enjoying JupyterLab.

I will close this issue as resolved now.
