### ISSUE TITLE
Not locating Jupyter in PATH

### ISSUE THREAD

**Issue by im-coder-lg** [jupyterlab/jupyterlab-desktop#295]
## Description

I installed Anaconda3 today and installed JupyterLAB after that but all I get is this:
![image](https://user-images.githubusercontent.com/76845820/136683900-5180f7a4-3e5e-4d96-b0a8-c1c835f73f4a.png)

## Reproduce

IDK if it's possible to recreate this since it comes on startup

## Expected behavior

Supposed to launch JupyterLab

## Context

- Operating System and version: Windows 7 Ultimate
- Browser and version: Vivaldi 4.2
- JupyterLab version: Latest I got from here

<details><summary>Troubleshoot Output</summary>
<pre>
This won't work since the web version works, it is having problems with the desktop app
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Same, works on the browser, not on app
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.
I don't understand. Can you provide a step-by-step guide, please?
</pre>
</details>

Extra info: running this on Git Bash since I am a Bash user

**Comment by im-coder-lg** [comment]
Can anybody help me with this?

**Comment by melund** [comment]
I experienced the same problem when trying out Jupiter native the other day. I haven't found a way to make it work.

**Comment by im-coder-lg** [comment]
> I experienced the same problem when trying out Jupiter native the other day. I haven't found a way to make it work.

Did you try that Add PATH button? I tried to add it to my Jupyter source file but my Jupyter shortcut redirects me to Python. I haven't managed to get Jupyter onto the native app that way.

**Comment by robbishman** [comment]
Same problem. I noticed that "choose path" is not working. I installed jlab_server on my D-drive. After selecting "**D:\**JupyterLab\resources\jlab_server\python.exe" and clicking on "Use path" following error message is shown: "Environment not found at **C:\**JupyterLab\resources\jlab_server\python.exe".

**Comment by krassowski** [comment]
Let's focus the discussion over in #238. I would like to help to solve this problem; could you please check the following and post answers in #238:
- does running the application as an Administrator help?
- does installing it as an administrator, for all users, without changing the path help?
- what operating system are you using, and what version?

Thank you for your help.

**Comment by im-coder-lg** [comment]
> what operating system are you using, and what version?

Windows 7 SP 1 build 7601
