### ISSUE TITLE
Shift + Right doesn't work

### ISSUE THREAD

**Issue by A3EKV** [jupyterlab/jupyterlab-desktop#297]
When I right click, I see in the bottom of the menu that I need to `Shift ` + `Right `click to bring up the browser menu.
![image](https://user-images.githubusercontent.com/90999345/136692275-4eca8575-a019-4220-9685-6945bfa35943.png)

However it doesn't seem to work with this application. When I `Shift` + `Right` Click nothing happens.

(I found that this feature is implemented and no issue was reported here: https://github.com/jupyterlab/jupyterlab/issues/3224 )

**Comment by krassowski** [comment]
Thanks for opening this issue. Indeed there is no Browser Menu in JupyterLab Desktop. This is already tracked in #296. Please chime in in there and let us know what solution you would prefer.

**Comment by A3EKV** [comment]
@krassowski : You mean issue #206 instead of #296 right?

**Comment by krassowski** [comment]
Yes, sorry!
