### ISSUE TITLE
extentions are missing

### ISSUE THREAD

**Issue by ssmns** [jupyterlab/jupyterlab-desktop#302]
I install the latest jupyterlab on my ubuntu 20.04 but its seems missigns extension section(icon not showing). is there a way to activate extensions?

![2021-10-12_21-57](https://user-images.githubusercontent.com/21356156/137009568-fe99396a-c46f-4c9f-a6e2-5c174cc68b29.png)

**Comment by krassowski** [comment]
Please see the response in #269.

**Comment by krassowski** [comment]
Closing this one as a duplicate, I will reopen the original one.
