### ISSUE TITLE
How to change terminal inside JupyterLab on Windows?

### ISSUE THREAD

**Issue by haesleinhuepf** [jupyterlab/jupyterlab-desktop#309]
## Description

Hi all,

I'm rather new to Jupyter lab, locally installed as Desktop app. The terminal is typically quite powerful, but not here. First of all I'm wondering how to change the "default" cmd (which is powershell on my Windows) to a normal CMD. Furthermore, its PATH is obvidoulsy not configured. The user can't execute python from the terminal (and one cannot read `python`, because its orange):

![image](https://user-images.githubusercontent.com/12660498/137624971-b7bba4ad-e596-46bb-b80a-69dce65520c9.png)

## Reproduce

* Download Jupyterlab Version 3.1.18-1. 
* Install it on Windows with default configuration.
* Start JupyterLab
* Start a Terminal
* Enter "python".

You will see the error above. Btw, also `pip install fails`

![image](https://user-images.githubusercontent.com/12660498/137625048-6d3dfecb-43be-4f8a-b967-5f1e0b5f1fe9.png)

## Expected behavior

I'm expcting it runs python.

## Context

- Operating System and version: Windows 10 20h2
- JupyterLab-Desktop version: 3.1.18-1
- Installer: JupyterLab-Setup-Windows.exe

### Troubleshoot Output

<pre>
PS C:\Users\rober> jupyter troubleshoot
jupyter : The term 'jupyter' is not recognized as the name of a cmdlet, function, script file, or operable program. Check 
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ jupyter troubleshoot
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (jupyter:String) [], CommandNotFoundException        
    + FullyQualifiedErrorId : CommandNotFoundException
</pre>
</details>

### Browser Output

> Go to `Help` menu -> `Open Developer Console` to access the JavaScript console

There is no such menu:
![image](https://user-images.githubusercontent.com/12660498/137625139-c4c73794-1614-44fc-b107-3aa1e463cd78.png)

**Comment by JasonWeill** [comment]
@mbektas This came up again in #643, which @yuliaUU opened. I don't see `powershell` mentioned in the code; is there a workaround or fix for this?

**Comment by krassowski** [comment]
If you have a different shell installed you should be able to use it by customising the `--ServerApp.terminado_settings` traitlet, entering it with a correct path under "Settings" (under hamburger menu in top-right corner of the window bar) → "Server" tab → "Additional JupyterLab Server launch args":

![Screenshot from 2023-04-25 19-36-47](https://user-images.githubusercontent.com/5832902/234371156-f0ec4006-68b1-469e-91e5-21dca6e90f58.png)

Examples of valid arguments:

```
--ServerApp.terminado_settings="shell_command=['/bin/zsh']"
```

```
--ServerApp.terminado_settings="shell_command='/bin/zsh'"
```

This requires an up-to-date jupyter-server including https://github.com/jupyter-server/jupyter_server/pull/949 (so v2.0+) - if you are using a custom environment it may not work

**Comment by yuliaUU** [comment]
I wonder if anyone know the fix for this for JupyterLab Desktop?

**Comment by mbektas** [comment]
@haesleinhuepf @yuliaUU did you try the suggestion from @krassowski above? setting the addtional launch args as `--ServerApp.terminado_settings="shell_command=['C:\Windows\SysWOW64\cmd.exe']"` worked for me on Win 11.

**Comment by yuliaUU** [comment]
@mbektas I am not sure where I should add it to in Jupyter Lab Desktop app

**Comment by yuliaUU** [comment]
@krassowski thanks, that worked
