### ISSUE TITLE
Export WebPDF not working

### ISSUE THREAD

**Issue by stefnestor** [jupyterlab/jupyterlab-desktop#313]
## Description

Hello, @krassowski! I installed JupyterLab Desktop today (v3.1.18-1) & ran into https://github.com/jupyterlab/jupyterlab-desktop/issues/270. Per https://github.com/jupyterlab/jupyterlab-desktop/issues/290#issuecomment-939291234, this should be resolved for jupyterlab >=v3.2.0 via https://github.com/jupyterlab/jupyterlab/pull/11208. (I may/not be using the other PDF export than previously raised, not sure from linked write-ups.)

## Reproduce

1. System Info (TLDR: MacOs BigSur on Firefox w/installation from today)

    ```
    ~ $ jupyter --version
    jupyter core     : 4.7.1
    jupyter-notebook : 6.4.0
    qtconsole        : 5.1.1
    ipython          : 7.25.0
    ipykernel        : 6.0.1
    jupyter client   : 6.1.12
    jupyter lab      : 3.2.1
    nbconvert        : 6.1.0
    ipywidgets       : 7.6.3
    nbformat         : 5.1.3
    traitlets        : 5.0.5
    
    ~ $ sw_vers
    ProductName:	macOS
    ProductVersion:	11.5.2  # aka Big Sur
    BuildVersion:	20G95
    
    ~ $ # firefox info
    # 93.0 (64-bit)
    ```

1. Export `webpdf` via `$ jupyter-lab` (from `pip install jupyterlab` => `http://localhost:888X` (success)
    - ![image](https://user-images.githubusercontent.com/26751266/138626474-254412fe-fab0-459f-a2f4-abd1d53cad0c.png)
    - ![image](https://user-images.githubusercontent.com/26751266/138626491-fadfde6f-c845-426b-8d7c-83c459e331a5.png)

1. Attempt export via Jupyter Desktop, receive white NULL page (replicated after app restart). Confirm no export in Downloads / file directory.
    - ![image](https://user-images.githubusercontent.com/26751266/138626561-3d868dfb-22f6-4713-a5c1-2eaea4d85240.png)

1. (**Edit**: Reading more, since this hosts via Electron,) I opened app's developer tools to grab error. Similar to https://github.com/jupyterlab/jupyterlab-desktop/issues/270#issuecomment-932729513 but potentially distinct.

    ```
    browser.bundle.js:84405 Uncaught (in promise) TypeError: child.location.assign is not a function
        at browser.bundle.js:84405
        at new Promise (<anonymous>)
        at execute (browser.bundle.js:84404)
        at CommandRegistry.execute (browser.bundle.js:127669)
        at RankedMenu.Menu.triggerActiveItem (browser.bundle.js:150438)
        at RankedMenu.Menu._evtMouseUp (browser.bundle.js:150785)
        at RankedMenu.Menu.handleEvent (browser.bundle.js:150584)
    
    (anonymous) @ browser.bundle.js:84405
    execute @ browser.bundle.js:84404
    CommandRegistry.execute @ browser.bundle.js:127669
    Menu.triggerActiveItem @ browser.bundle.js:150438
    Menu._evtMouseUp @ browser.bundle.js:150785
    Menu.handleEvent @ browser.bundle.js:150584
    ```

**Comment by bollwyvl** [comment]
Bit of a necropost here, but: it seems like after paying the electron price, [`printToPDF`](https://www.electronjs.org/docs/latest/api/web-contents#contentsprinttopdfoptions) would potentially make generating publication-quality PDF from actual lab DOM (as opposed to roundtripping to static HTML on the server) _much_ more robust and testable than most other solutions.

While the initial thing would likely need to handle the basic case of "everything inside this Notebook MainAreaPanel," it would likely be reasonable to offer this in such a way that extension authors could use a client-side token (e.g. `IPrintManager`) which allowed for building up multi-page documents (e.g. open presentation, run all cells, click).

Really bringing this home would be a CLI that offered this capability in a headless environment, so quality PDF could become part of the output of a CI process.
