### ISSUE TITLE
Warning. "This app will not work with future version of macos"

### ISSUE THREAD

**Issue by vincentdavis** [jupyterlab/jupyterlab-desktop#315]
After updating to macOS Monterey 12.0.1, I get this warning that links to the url below. This looks like a macOS system warning, but it is strange to me that it links to the python website. See attached image.
[Learn More](https://www.python.org/doc/sunset-python-2/)

<img width="266" alt="Screen Shot 2021-10-26 at 7 48 18 PM" src="https://user-images.githubusercontent.com/232564/138986465-3670b0ef-2944-447f-9e0f-8f3cbafd603b.png">

BTW, love the app!

**Comment by mbektas** [comment]
@vincentdavis I have been using JupyterLab Desktop with macOS Monterey 12.0.1 for a while without issues. Could you retry with the latest version please?

**Comment by krassowski** [comment]
Not a macOS user, but it looks like this is triggered by any first invocation of `/usr/bin/python` from any app. What are the aliases on Mac? Is it `python` → `/usr/bin/python` and `python3` → `/usr/bin/python3`? If so, then maybe this line is to blame:

https://github.com/jupyterlab/jupyterlab-desktop/blob/62809f714a3dac599bb3dda848f5650771638912/dist-resources/darwin/jlab.sh#L4

? Just a guess.

**Comment by vincentdavis** [comment]
I think @krassowski might me on the right track.
I only got it the first time I opened it. I was setting up a new computer and have since installed other python version. 
I have seen this same error with a couple other programs although I forget which.
@mbektas I wonder if we setup a new user account and run Jupyterlab we will get the warning.

Currently, from my zsh shell
python > /Users/vincentdavis/opt/anaconda3/bin/python
python3 > /Users/vincentdavis/opt/anaconda3/bin/python3

**Comment by vincentdavis** [comment]
It does appear this is because the app triggers the use of the built in python 2.7, see link below.

```
Python
Deprecations

    If an app uses Python 2.7, macOS now triggers an alert indicating that the developer must update the app to ensure it will work in future versions of macOS. (80221011)
```
    
https://developer.apple.com/documentation/macos-release-notes/macos-12_0_1-release-notes

**Comment by mbektas** [comment]
@vincentdavis did you run into this issue when you ran JupyterLab Desktop using command-line (`jlab` command)?

**Comment by vincentdavis** [comment]
> @vincentdavis did you run into this issue when you ran JupyterLab Desktop using command-line (`jlab` command)?

I did not, First time I opened the app, by clicking the app icon, which I installed in my User/Applications folder.
I have never opened the app from the command-line.
