### ISSUE TITLE
Keyboard arrow keys for moving to cell above/below

### ISSUE THREAD

**Issue by hellojinwoo** [jupyterlab/jupyterlab-desktop#326]
# Question
- What should I do to move to another cell, using only my keyboard?
- Up/Down arrow keys lets me scroll up/down, but does not let me move to another cell above or below.
- Which setting should I correct to use arrow keys to move to another cell, as I did in Jupyterlab?

**Comment by krassowski** [comment]
Please see #320.

**Comment by hellojinwoo** [comment]
> Please see #320.

Thanks! I will close this issue, then.
