### ISSUE TITLE
Still cannot see the 'extension manager' after updating to 3.2.1-2

### ISSUE THREAD

**Issue by hellojinwoo** [jupyterlab/jupyterlab-desktop#327]
- After the PR #322 is merged, I have updated to the most recent version of jupyterlab-desktop, which is 3.2.1-2, but still cannot see the extension manager yet.
![image](https://user-images.githubusercontent.com/34431729/140020179-c2cde06f-0103-4094-9424-309e392506c7.png)

- According to the [release page](https://github.com/jupyterlab/jupyterlab-desktop/releases), jupyterlab extensions are now supported so I assumed we can see the extension manager at the left side-bar but it is not there.
![image](https://user-images.githubusercontent.com/34431729/140020328-1bfcb7f9-86b9-4c0b-a107-3f3d44a6bbc3.png)

- I have set "true" to the "enabled" section in the advanced settings editor, and installed all the 'build dependencies', such as node.js. Why can't I see the extension manager?
![image](https://user-images.githubusercontent.com/34431729/140020516-fe6ca5a9-96f7-4b13-b920-229f4cc8e3dd.png)

**Comment by krassowski** [comment]
That PR enabled installing and using prebuilt (aka federated) extensions that are installed with `pip`/`conda` and sometimes other package managers; The description of #322 specifically says:

> Does not solve #269, i.e. the extension manager remains disabled as we do not offer support for source extensions but currently the extension manager assumes that both prebuild (federated) and source extension are supported.

I added clarifying comment in https://github.com/jupyterlab/jupyterlab-desktop/issues/269#issuecomment-958771989. Let's consolidate discussion in #289 which I purposefully left open to tracka did extension manager. Please feel welcome to contribute to upstream JupyterLab to make the extension manager support prebuilt extensions installation.
