### ISSUE TITLE
Why `C:/` appears twice, preventing me from opening or creating other files?

### ISSUE THREAD

**Issue by hellojinwoo** [jupyterlab/jupyterlab-desktop#328]
- After installing the jupyterlab desktop 3.2.1-2 this morning, I encountered this problem that shows the `C:/` two times or three times.
![image](https://user-images.githubusercontent.com/34431729/140034642-c2a2310d-38b3-4831-8aa3-b7d51963b9b2.png)
![image](https://user-images.githubusercontent.com/34431729/140034865-0e4ba435-afab-44c9-8243-cf42af6b087b.png)

- When it happens, I cannot open or create an `.ipynb` file anymore due to the following error screen
![image](https://user-images.githubusercontent.com/34431729/140034522-2819700e-a485-45ef-a75a-0fc766c5ebfa.png)

- When this problem occurs, I need to go to the top folder, such as `C:/`, in the file explorer in the jupyterlab. Then this double or triple `C:/` problem is gone.

- What should I do to get rid of this problem?

**Comment by krassowski** [comment]
Thank you for this report - it should not be like that. Does the amount of `C:/` correlate with any action, like entering a nested folder?

**Comment by hellojinwoo** [comment]
@krassowski I just executed the JupyterLab, through clicking the shortcut icon on the desktop for 5 times (My OS is Windows 10, btw), And I found some funny points to share with you.

1. Out of 5 times, I had multiple `C:/`s 4 times. Only 1 out of 5, I had one `C:/`.
2. The number of `C:/` is random. Sometimes there are 2, sometimes there are 3, and even 4 sometimes.
![image](https://user-images.githubusercontent.com/34431729/140037572-13abde68-b597-4e05-a48a-960a6b73a556.png)
3. It seems like this problem started to happen after I tried to change the folder name in the Jupyterlab Desktop. I had an error screen saying that "Permission Denied", because I had one `.ipynb` file opened in the folder, whose name I tried to change. I am just telling you this because it might help you figure out the source of this problem.

**Comment by hellojinwoo** [comment]
Is there anyway that I can fix the starting folder when I open up the jupyterlab desktop? If I can set it to be `C:/`, then this problem might go away.

**Comment by krassowski** [comment]
I will try to investigate on Saturday. Sorry, it's a busy week.

**Comment by mbektas** [comment]
> Is there anyway that I can fix the starting folder when I execute the jupyterlab desktop? If I can set it to be `C:/`, then this problem might go away.

@hellojinwoo you can set the starting folder to `c:\` by launching JupyterLab Desktop using `Command Prompt` with command `jlab c:\`

**Comment by hellojinwoo** [comment]
> > Is there anyway that I can fix the starting folder when I execute the jupyterlab desktop? If I can set it to be `C:/`, then this problem might go away.
> 
> @hellojinwoo you can set the starting folder to `c:\` by launching JupyterLab Desktop using `Command Prompt` with command `jlab c:\`

Do I need to type `jlab c:\` every time when I start jupyterlab desktop if I want to set the starting folder to `c:\`? Is there any config file that I can set?

One of the main reasons that I am using jupyterlab desktop is that I do not want to type jupyterlab on `Command Promt`, so I do not want to type anything on `cmd`...

**Comment by mbektas** [comment]
you can modify the JupyterLab shortcut created on your desktop, or create a new shortcut and add the launch folder to the `Target` (e.g `C:\JupyterLab\JupyterLab.exe C:\`).

![change-win-shortcut](https://user-images.githubusercontent.com/40003442/140953708-09091b75-9df0-4370-869c-7ac0d1dd0c0b.png)

**Comment by hellojinwoo** [comment]
> you can modify the JupyterLab shortcut created on your desktop, or create a new shortcut and add the launch folder to the `Target` (e.g `C:\JupyterLab\JupyterLab.exe C:\`).
> 
> ![change-win-shortcut](https://user-images.githubusercontent.com/40003442/140953708-09091b75-9df0-4370-869c-7ac0d1dd0c0b.png)

This does not work for me. It still starts at the last folder when I exited the `jupyterlab desktop`.

**Comment by hellojinwoo** [comment]
I have deleted and reinstalled the JupyterLab-Desktop and now it works as you instructed. Thank you @mbektas
