### ISSUE TITLE
Is it possible to convert Jupyter Notebook project to standalone app with Jupyterlab-Desktop?

### ISSUE THREAD

**Issue by pplonski** [jupyterlab/jupyterlab-desktop#333]
Hi,

Thank you for a very nice project! I have a question. Is it possible to convert notebook (ipynb file) to a standalone app, so it can work similarly to Jupyterlab-Desktop? I have a notebook with a few ipywidgets and visualizations. I would like to hide the code and only show widgets+plots to my friend. 

Thank you!

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/is-it-possible-to-convert-jupyer-notebook-ipynb-file-to-desktop-app/11590/4

**Comment by pplonski** [comment]
Looks like it is possible for R - https://github.com/chasemc/electricShine However, it will work only on Windows. Anyway, amazing package.

**Comment by krassowski** [comment]
Hi @pplonski can we close this as answered on Jupyter Community Forum?

**Comment by pplonski** [comment]
@krassowski Yes, please. Thank you for your help!
