### ISSUE TITLE
Cannot install `jupyterlab-variableInspector`

### ISSUE THREAD

**Issue by hellojinwoo** [jupyterlab/jupyterlab-desktop#335]
## Description
- Cannot install a jupyterlab extension `jupyterlab-variableInspector` via `pip`. 
- I can install it with jupyterlab, but cannot with `jupyterlab-desktop`

## Reproduce

1. Go to `Jupyterlab Desktop`
2. Open a new notebook file
3. Type `pip install lckr-jupyterlab-variableinspector` in a cell. 

```
error: could not create 'build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.9.data\data\share\jupyter\labextensions\@lckr\jupyterlab_variableinspector': The system cannot find the path specified
  ----------------------------------------
  ERROR: Failed building wheel for lckr-jupyterlab-variableinspector
ERROR: Could not build wheels for lckr-jupyterlab-variableinspector, which is required to install pyproject.toml-based projects
```

## Expected behavior
Installing the `jupyterlab-variableinspector` without an issue

## Context

- Operating System and version:  : Windows 10
- JupyterLab-Desktop version: : Version 3.2.1-2
- Installer: : exe

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab-Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

**Comment by pplonski** [comment]
Have you followed the instructions https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#customizing-the-bundled-python-environment ?

**Comment by hellojinwoo** [comment]
@pplonski Yes you are right. You saved my day, thank you :D
