### ISSUE TITLE
package not found in desktopapp but found in (browser)lab and notebook

### ISSUE THREAD

**Issue by nphaibk** [jupyterlab/jupyterlab-desktop#338]
my desktopapp jupyterlab works well a few days ago and today it cannot find some packages such as jieba, xpinyin

but when running jupyter lab in browser and notebook, they both work fine with the packages

I have updated to the latest version 3.2.3-1 but problem remains, anyone has the same issue?

**Comment by krassowski** [comment]
You are likely using a different Python environment. Please change the environment using the selector in the statusbar.

**Comment by nphaibk** [comment]
> You are likely using a different Python environment. Please change the environment using the selector in the statusbar.

Indeed!
Thanks a lot - although I could not select the other env from the statusbar, but I manually delete the new env created during lab installation, and problem resolved
