### ISSUE TITLE
Link in the update dialog does not show up correctly

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-desktop#351]
## Description

Link in the update dialog does not show up correctly

![signal-2021-11-26-21-45-11-322.png](https://user-images.githubusercontent.com/5832902/143657122-d8cc1b5f-8b13-4da7-bd76-42bee5de18da.png)

## Reproduce

1. Install 3.2.4-1
2. See error in dialog on startup

## Expected behavior

The link should be clickable

## Context

- Operating System and version: Ubuntu 21.10
- JupyterLab-Desktop version: 3.2.4-2

**Comment by ptoche** [comment]
I can confirm this on MacOS Big Sur 11.6 and JupyterLab-Desktop version: 3.2.4-1.
