### ISSUE TITLE
Change default folder Mac

### ISSUE THREAD

**Issue by tamet83** [jupyterlab/jupyterlab-desktop#356]
Hi,

I know this is not a but, but I did't know where ask.
I installed JupyterLab Desktop non my Mac and it works perfectly.

I just need to ask how can I change the default path directory. I need to access directly on this path:

`/Users/matteo/Nextcloud/2 - Documenti/Corsi/Data Science/`

Is there a way to force the app settings?

Many thanks

**Comment by krassowski** [comment]
There is no setting just yet, but it is high on my wishlist too. I envision this as having separate "projects" which can be opened from a new File -> Open Recent Project, and File -> New Project, where Project = environment + path + other config (in the future). However, you should be able to start the app pointing to a specific directory already using `jlap your/dir/path` as described in https://github.com/jupyterlab/jupyterlab-desktop#jlab-command-line-launch-examples - does it work for you for now?

**Comment by tamet83** [comment]
Many thanks for your help. I think I'm going to open the app through the file.
I've just started to look around an I prefer stick with easy things.
I'll wait future updates.
Thanks.

**Comment by mbektas** [comment]
this is already fixed in the latest version
