### ISSUE TITLE
Build request dialog shows up after installing some extensions

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-desktop#365]
## Description

Installing jupyterlab-git also fetches nbdime as a dependency. nbdime installation triggers a prompt for rebuilding lab, which we do not currently support.

## Reproduce

1. Create a new environment
2. Install JupterLab and `jupyterlab-git` in the new environment
3. Switch JupyterLab Dekstop to use that environment
4. See misleading prompt:

![Screenshot from 2021-12-10 13-06-33](https://user-images.githubusercontent.com/5832902/145578902-54217fd9-41f7-4f82-ba15-98d628425494.png)

## Expected behavior

This prompt should not show up as we do not support rebuilding.

This can be solved by adding disabling `page_config_data` `buildCheck` see https://github.com/jupyterlab/jupyterlab/issues/7368 and https://github.com/jupyter-lsp/jupyterlab-lsp/blob/6f32efd0d004b636ab9ef175633df26ee1c102a3/atest/fixtures/jupyter_server_config.json#L6-L13

**Comment by hellojinwoo** [comment]
I have just installed `jupyterlab-git` and that message 'build recommended' didn't come out. My OS is windows 10 and I am using jupyterlab-desktop 3.2.5-1
