### ISSUE TITLE
Automatic updates

### ISSUE THREAD

**Issue by NicolausSteno** [jupyterlab/jupyterlab-desktop#371]
Currently, at least on MacOS, to update to the latest JupyterLab Desktop version with improvements and new features, one needs to first uninstall the version installed and reinstall everything from Github. This process takes quite long and can cause issues if the bundled environment is customised with other packages and so on. I would suggest releasing a new feature that allows new updates to be installed directly from the app or, even better, releasing JupyterLab Desktop on the Mac App Store.

**Comment by krassowski** [comment]
Previously requested in: https://github.com/jupyterlab/jupyterlab-desktop/issues/266

**Comment by mbektas** [comment]
macOS now has auto-update feature
