### ISSUE TITLE
Environment variables are not loaded

### ISSUE THREAD

**Issue by piotr-machura** [jupyterlab/jupyterlab-desktop#373]
## Description
Hello, when using jupyterlab-desktop the program seems to start in a completely empty environment. Variables such as `$USER` and `$HOME` are unset. This is the case in all notebooks and all terminals.
![screenshot_307598](https://user-images.githubusercontent.com/59394665/146599002-c6173f59-74f2-4ac3-a17f-8906aef690df.png)
The terminal then sources my `~/.profile` and arrives at nonsense paths
![screenshot_583409](https://user-images.githubusercontent.com/59394665/146600458-1d723190-64d2-4152-b9ac-869d43c1b041.png)
(notice how some of them they start with `/.config/` or `/.local/`, since `$HOME` was unset).

## Reproduce
The program was installed from the 3.2.5 [deb](https://github.com/jupyterlab/jupyterlab-desktop/releases/download/v3.2.5-1/JupyterLab-Setup-Debian.deb) via this [aur](https://aur.archlinux.org/packages/jupyterlab-desktop-bin/) package (but with `$pkgver` updated to v3.2.5). It is launched with `/opt/JupyterLab/jupyterlab-desktop`.

Upon first launch I selected the python executable at `/usr/bin/python`, which has the "regular" jupyterlab installed. The packages are working fine (I am able to import everything installed on my system), but there are no environment variables.

## Expected behavior

Environment variables are present. This issue does not exist when I launch the "regular", browser-based jupyterlab in Firefox 95.0.1:
![screenshot_048219](https://user-images.githubusercontent.com/59394665/146599963-96e5ed75-7b7e-4066-9209-337577d8f0dd.png)

## Context

- Operating System and version: Arch Linux
- JupyterLab-Desktop version: 3.2.5
- Installer: .deb

**Comment by krassowski** [comment]
Thank you for detailed report @piotr-machura. #374 should fix this.
