### ISSUE TITLE
Thank you for this project!

### ISSUE THREAD

**Issue by connorferster** [jupyterlab/jupyterlab-desktop#376]
I just wanted to say "Thank you!" to the folks who have been putting time into this project. I have switched to using JupyterLab Desktop as my primary Jupyter environment and I love it. Open files by double-clicking? Awesome!

Thank you so much for your time and efforts!

**Comment by krassowski** [comment]
Thank you for the nice comment :) We closed it on a triage meeting to clean up the list of issues.
