### ISSUE TITLE
Can I directly move to another file which is referenced in the currently open file?

### ISSUE THREAD

**Issue by hellojinwoo** [jupyterlab/jupyterlab-desktop#378]
Let's say I am taking a look at the codes on the `open.py` .
The code is as follows:

```
import cache as cc
var_1 = cc.openPosition()
var_2 = cc.closePosition()

def a_random_func():
    print("hello")
    qty = var_1 
    return qty
```

I would like to move to the `cache.py` file by clicking the `cc.openPosition()` function, because I need to check what that function means. Do we have this function on jupyterlab-desktop? As far as I know, VS code supports it.

p.s. I love the jupyterlab-desktop! Thanks for your great project.

**Comment by krassowski** [comment]
You could install [jupyterlab-lsp](https://github.com/jupyter-lsp/jupyterlab-lsp) extension which provides this functionality.

**Comment by hellojinwoo** [comment]
> You could install [jupyterlab-lsp](https://github.com/jupyter-lsp/jupyterlab-lsp) extension which provides this functionality.

As you are a creator of the library `jupyterlab-lsp`, I am afraid to tell you this, but let me tell you honestly. After installing jupyterlab-lsp on the jupyterlab, I have experienced a huge speed problem so I have deleted the anaconda library as a whole. I don't know how to uninstall jupyterlab-lsp separately.

I am worried if the library `jupyterlab-lsp` would lower the speed of jupyterlab-desktop as well. Do you think jupyterlab-lsp would slow down the jupyterlab-desktop as well?

**Comment by krassowski** [comment]
This is hard to tell, but I have not seen `jupyterlab-lsp` as responsible for any major slowdown. This could be an issue with a specific language server you used, a user error when installing it (e.g. mixing conda and pip, having misconfigured anaconda channels), or even be completely unrelated. We cannot fix issues that you do not report. Uninstallation of  `jupyterlab-lsp` is done the same way as [installation](https://github.com/jupyter-lsp/jupyterlab-lsp#installation) - via pip or conda. Asking for features that you know are already implemented is not the way to help to move the project forward (as now I have several minutes less to improve both Desktop and LSP) - reporting bugs is :)
