### ISSUE TITLE
Add kerrgeodesic_gw package to jupyterlab desktop

### ISSUE THREAD

**Issue by andrelucchini** [jupyterlab/jupyterlab-desktop#384]
Good night.

First of all, thanks so much for the desktop version, it's amazing.

I would like to clear a question, in the browser version I use the kerrgeodesic_gw package for my research and I would like to use it also in the desktop version, but the error appears:

"No module named 'kerrgeodesic_gw' "

but I already have it installed, and it runs in the browser version. Do I have to re-install specifically for the desktop version? Because I don't know how to do this. Can you help me?

I have Linix Mint 20.1, Ubuntu 20.04.

Thank you for your attention.

**Comment by hellojinwoo** [comment]
Have you installed the library following this instruction? https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#customizing-the-bundled-python-environment

**Comment by andrelucchini** [comment]
I've been to this site before, but to be honest I didn't quite understand the step 

"Install the application by double clicking the installer file"

For first time I installed the package to use on Sagemath, I installed it from the terminal, I didn't download any package installer. 

How can I proceed?

**Comment by krassowski** [comment]
This step refers to installation of [JupyterLab Desktop](https://github.com/jupyterlab/jupyterlab-desktop) itself, not of the user packages.

**Comment by andrelucchini** [comment]
The  jupyterlab desktop is already installed, I'm using it perfectly even. The only package I'm not able to use is kerrgeodesic_gw

**Comment by hellojinwoo** [comment]
> The jupyterlab desktop is already installed, I'm using it perfectly even. The only package I'm not able to use is kerrgeodesic_gw

Oops. sorry. I meant the step right below the "customizing the bundled python environment". So you can refer to this step https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#installing-new-python-packages . It is about how to install the library on Jupyterlab-Desktop

**Comment by andrelucchini** [comment]
Thank you very much, it was my lack of attention.

One more thing, this package I use in Sagemath, but it can only be used in versions equal to or greater than 9.3, but jupyterlab comes in version 9.0. Is sagemath in newer versions already available for him?

**Comment by hellojinwoo** [comment]
> Thank you very much, it was my lack of attention.
> 
> One more thing, this package I use in Sagemath, but it can only be used in versions equal to or greater than 9.3, but jupyterlab comes in version 9.0. Is sagemath in newer versions already available for him?

Which program are you talking about when you said 9.0 or 9.3? It is definitely not Python as the Python's recent version is up to 3.x. And what does him refer to in the last sentence?

**Comment by andrelucchini** [comment]
I'm talking about Sagemath, it's symbolic computing software that I use. Normally, to use it in the Browser I launch it in the terminal

"sage -n jupyter" or "sage -n jupyterlab"

and both open in the version I use, Sagemath 9.3, but on the desktop it opens in version 9.0.

**Comment by hellojinwoo** [comment]
There should be no difference in terms of package version if you install it from the same source.
I advise you to uninstall the library and re-install it. If it does not solve your problem, you can also uninstall jupyterlab-desktop and reinstall it.

**Comment by andrelucchini** [comment]
Perfect, I will try to reinstall it.

@hellojinwoo thank you very much for your help and patience. You helped me a lot.

**Comment by andrelucchini** [comment]
@hellojinwoo  Looks like I closed the problem too soon. lol

I tried to make the changes you suggested and reinstalled jupyterlab, but Sagemath is still on version 9.0 on the desktop.

**Comment by krassowski** [comment]
I would not expect re-installation alone to change the `Sagemath` version. First, I do not understand why you expect `Sagemath` to be provided by `JupyterLab Desktop` - the two should have no connection as far as I know; we do not provide a `Sagemath` installer with `JupyterLab Desktop`. JupyterLab Desktop installs a minimal conda environment, which you can change using the selector on the statusbar. If you have installed sagemath to one of your environments you should update it there. You may have several versions installed, and maybe when using JupyterLab Desktop a different version is available because of the path configurations (compared to when you access it normally); in either case I don't believe this is a problem with JupyterLab Desktop at all, but an issue with your local installation.

**Comment by mbektas** [comment]
closing since not a Desktop app issue. please create new issue if you still have problems.
