### ISSUE TITLE
No output from running cells after installation on Windows

### ISSUE THREAD

**Issue by astroStudent123** [jupyterlab/jupyterlab-desktop#385]
I installed on Windows using the instructions in the README file. Everything appears fine, except running cells produces no output; e.g. if I open a new notebook, create a code cell with the code `print('here')`, and click the "run the selected cells and advance" button, the curser advances but no output is produced. Should I try re-installing?

**Comment by krassowski** [comment]
Reinstallation might be worth trying. Would you mind filling in the [bug report template](https://github.com/jupyterlab/jupyterlab-desktop/issues/new?assignees=&labels=bug&template=bug_report.md)?

**Comment by astroStudent123** [comment]
Hmm.. reinstalling doesn't help.  Any other suggestions? I will fill out a bug report template.

**Comment by krassowski** [comment]
Closing this on in favour of #386 which now has a lot of useful information. Thank you!
