### ISSUE TITLE
My jupyterlab crashes so often. How can I report logs?

### ISSUE THREAD

**Issue by hellojinwoo** [jupyterlab/jupyterlab-desktop#391]
When I right click the variable and click `rename_symbol`, it does not change anything. 
I would like to report a backlog as well, but I don't know how to see it on jupyterlab-desktop. If you let me know, I will add it, please.

**Comment by krassowski** [comment]
What is `rename_symbol`? Could you add a screenshot and more information as requested by the bug report template please?

**Comment by hellojinwoo** [comment]
`rename_symbol` is a tool provided in `jupyterlab-lsp` that you made! Now I believe the reason lies in that Jupyterlab-desktop got frozen while I use it. To provide more info, I need to take a look at the logs of jupyterlab-desktop, but I don't know how. Can you tell me how I can access the logs of the program, please? By doing so, I can provide with more details why the jupyterlab-desktop crashes.

**Comment by hellojinwoo** [comment]
I have changed the issue title to reflect my problem better

**Comment by krassowski** [comment]
> Can you tell me how I can access the logs of the program, please?

It is described in the [bug issue template](https://github.com/jupyterlab/jupyterlab-desktop/issues/new?assignees=&labels=bug&template=bug_report.md):

```
<details><summary>Logs (required for issues with loading, server and startup)</summary>
<!--Start application from command line as `jlab --verbose 4`, wait until it settles-->
<!--Copy-paste the logs from the following location:-->
<!--on Linux: ~/.config/jupyterlab-desktop/logs/main.log-->
<!--on macOS: ~/Library/Logs/jupyterlab-desktop/main.log-->
<!--on Windows: %USERPROFILE%\AppData\Roaming\jupyterlab-desktop\logs\main.log-->
<pre>
Paste the logs from the main.log file here.

</pre>
```
