### ISSUE TITLE
Can I use this app to connect to remote jupyter server?

### ISSUE THREAD

**Issue by yanzastro** [jupyterlab/jupyterlab-desktop#394]
This is a nice app. I'm wondering if I can use it locally to connect to my jupyterlab on my remote server?

**Comment by YAMLcase** [comment]
Thanks for asking this @yanzastro, I have a use case for remote connection.  I use Windows for my OS, but develop for Linux, so all my python environments are kept in WSL2.

**Comment by jweill-aws** [comment]
Thank you for your question! No, it cannot connect to a remote Jupyter Server right now. We have had open requests to add this functionality: see #15 and #48. Please follow these issues and add comments there.
