### ISSUE TITLE
Using a custom Jupyter Lab theme / extension

### ISSUE THREAD

**Issue by clstaudt** [jupyterlab/jupyterlab-desktop#399]
I would like to use a custom theme in my Jupyter Lab Desktop app. For Jupyter Lab in the browser, I install this extension:
https://github.com/dunovank/jupyterlab_legos_ui

Is there a way to use this theme with the desktop app too?

**Comment by clstaudt** [comment]
@hellojinwoo  That did not work for the desktop app though. A reboot has no effect.

**Comment by clstaudt** [comment]
@hellojinwoo  Interesting. Then we would need to find out where our setup differs.

**Comment by oikonang** [comment]
Mine didn't work either. The newly installed theme is available in jupyterlab but not in the standalone app. Any solution yet?

**Comment by mbektas** [comment]
could you test this with [v3.5.1-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.5.1-1) and update the issue?

**Comment by mbektas** [comment]
closing since no response for long time.
