### ISSUE TITLE
import numpy as np  results in ImportError: ...

### ISSUE THREAD

**Issue by jcoady** [jupyterlab/jupyterlab-desktop#410]
## Description

I installed the JupyterLab Desktop App on my windows machine and opened a new notebook in JupyterLab App. In a notebook cell I typed 

   import numpy as np

and ran the cell and I get the following error

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
C:\JupyterLab\resources\jlab_server\lib\site-packages\numpy\core\__init__.py in <module>
     21 try:
---> 22     from . import multiarray
     23 except ImportError as exc:

C:\JupyterLab\resources\jlab_server\lib\site-packages\numpy\core\multiarray.py in <module>
     11 
---> 12 from . import overrides
     13 from . import _multiarray_umath

C:\JupyterLab\resources\jlab_server\lib\site-packages\numpy\core\overrides.py in <module>
      6 
----> 7 from numpy.core._multiarray_umath import (
      8     add_docstring, implement_array_function, _get_implementing_args)

ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13048/3593848235.py in <module>
----> 1 import numpy as np

C:\JupyterLab\resources\jlab_server\lib\site-packages\numpy\__init__.py in <module>
    148     from . import _distributor_init
    149 
--> 150     from . import core
    151     from .core import *
    152     from . import compat

C:\JupyterLab\resources\jlab_server\lib\site-packages\numpy\core\__init__.py in <module>
     46 """ % (sys.version_info[0], sys.version_info[1], sys.executable,
     47         __version__, exc)
---> 48     raise ImportError(msg)
     49 finally:
     50     for envkey in env_added:

ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.8 from "C:\JupyterLab\resources\jlab_server\python.exe"
  * The NumPy version is: "1.21.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
## Reproduce

1.  Install JupyterLab Desktop App on Windows 10 Laptop using the default settings in the installation procedure.
2. Launch JupyterLab Desktop App and open a new notebook.
3. Type  import numpy as np in a cell and execute it
4. See error  Import Error described above.

## Expected behavior

I expected numpy to be imported without any errors.
## Context

- Operating System and version: Windows 10
- JupyterLab-Desktop version:  3.2.5-2
- Installer: https://github.com/jupyterlab/jupyterlab-desktop/releases/latest/download/JupyterLab-Setup-Windows.exe

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab-Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by connorferster** [comment]
I think this is numpy issue on Windows. Try upgrading numpy?

**Comment by mbektas** [comment]
closing since no response for long
