### ISSUE TITLE
JupyterLab for M1 Mac 

### ISSUE THREAD

**Issue by Philliec459** [jupyterlab/jupyterlab-desktop#427]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- JupyterLab-Desktop version: 
- Installer: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab-Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by Philliec459** [comment]
Would it be possible to run JupyterLab app on a Mac M1 native and not through Rosetta?

**Comment by krassowski** [comment]
Thanks for asking. This is already tracked in https://github.com/jupyterlab/jupyterlab-desktop/issues/279. Closing as a duplicate.
