### ISSUE TITLE
Verify correct jupyter installation

### ISSUE THREAD

**Issue by ddavidebor** [jupyterlab/jupyterlab-desktop#43]
There should probably be an user friendy message in case jupyter is not correctly installed that sends the user to http://jupyter.readthedocs.io/en/latest/install.html

**Comment by ddavidebor** [comment]
Depends on https://github.com/jupyterlab/jupyterlab_app/issues/48 now

**Comment by mbektas** [comment]
this is already handled by various UI notifications
