### ISSUE TITLE
Multi-User Capable?

### ISSUE THREAD

**Issue by Smack2k** [jupyterlab/jupyterlab-desktop#443]
Can this app be installed in an RDS / Multi-User enviornment and accessed by multiple users?  I know it says its self-contained and stand alone app, so I wasnt sure.

I am an IT admin with a request to install this on a Multi-User environment, so looking for any assistance.

**Comment by mbektas** [comment]
@Smack2k JupyterLab Desktop is intended mainly for use as standalone desktop application by single user. It could connect to a server that is running JupyterLab but that is no different than using a browser to do so. Please create a new issue if you have more questions. Thanks.
