### ISSUE TITLE
Can not use custom `pyenv` environment

### ISSUE THREAD

**Issue by ChiHangChen** [jupyterlab/jupyterlab-desktop#444]
Hi, my pyenv installed at `/home/jimchen/.pyenv/shims/python3` which my machine is Ubuntu20.04
![image](https://user-images.githubusercontent.com/22412708/164409918-3f04c42d-ce56-47d2-a264-d9a78f81467e.png)
But seems this environment can not be set to use jupyterlab desktop app
![image](https://user-images.githubusercontent.com/22412708/164410010-001e6cbc-89c4-48f3-82a3-6236d9029da5.png)

**Comment by krassowski** [comment]
Would you mind trying to use path like `~/.pyenv/versions/3.9.9/bin/python3` instead of the path to the shim?

**Comment by spookyuser** [comment]
Oops forgot that i hadn't installed jupyterlab on my instance, after I did that it worked!
