### ISSUE TITLE
%reload_ext autoreload %autoreload 2  issue

### ISSUE THREAD

**Issue by yucsong** [jupyterlab/jupyterlab-desktop#449]
autoload feature doesn't work?

%reload_ext autoreload
%autoreload 2

This worked for jupyter notebook before, but it seems not working for the desktop?

## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- JupyterLab-Desktop version: 
- Installer: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab-Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by krassowski** [comment]
I believe it should be `%load_ext autoreload` - and it works well for me in JupyterLab  Desktop.
