### ISSUE TITLE
Jupyterlab-desktop mangles HTTP requests and breaks my extension

### ISSUE THREAD

**Issue by pepijndevos** [jupyterlab/jupyterlab-desktop#450]
## Description

The app intercepts all HTTP requests, and then implements a custom handler to fetch them.
This handler overwrites the Authorization header, and for some POST requests never seems to finish.

https://github.com/jupyterlab/jupyterlab-desktop/blob/25c5d89f9507df2013dd034de91f28839edf7ed4/src/main/sessions.ts#L477-L529

## Reproduce

1. Install Jupyterlab-desktop
2. in the environment, run `conda install -c pepijndevos -c conda-forge ngspicesimserver couchdb pyttoresque jupyterlab-mosaic`
3. Run the app, open Mosaic from the launcher
4. Add a database, select it, and try to add a cell
5. Observe "(pending)" HTTP requests with "stalled" status

## Expected behavior

I expect the app to function the same as when accessed from `jupyter lab`, instead the app hangs when running inside Electron because jupyterlab-desktop mangles the HTTP requests.

## Context

- Operating System and version: Arch linux
- JupyterLab-Desktop version: git master
- Installer: git master

I can add more logs later if there is anything that's actually useful.

**Comment by mbektas** [comment]
@pepijndevos this should be fixed now with [v3.5.1-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.5.1-1). could you test and update the issue? Make sure you stay in `Web app mode`.

<img width="612" alt="web-app mode" src="https://user-images.githubusercontent.com/40003442/206865958-99e95869-2cc5-4a80-a426-6b49fcecdb4f.png">

**Comment by pepijndevos** [comment]
Thanks! Is it possible to make this the default mode somehow?

**Comment by mbektas** [comment]
> Thanks! Is it possible to make this the default mode somehow?

@pepijndevos `Web app` mode is already the default mode. changes to the settings in the `Preferences` dialog are persisted as well.
