### ISSUE TITLE
Can't change font

### ISSUE THREAD

**Issue by y-iizawa** [jupyterlab/jupyterlab-desktop#451]
Hi.
I can't change the font on the desktop ver. of jupyterlab while the browser ver.  allows me to change the font.
my env: macOS Monterey

Thank you.

**Comment by mbektas** [comment]
are you trying to change the font size? what are the steps to reproduce?

**Comment by mbektas** [comment]
this should be fixed now with [v3.5.1-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.5.1-1)

**Comment by donhuvy** [comment]
Cannot change font size.

![image](https://github.com/jupyterlab/jupyterlab-desktop/assets/1328316/ab5e0308-7f6b-4840-9285-174c2ac94256)

**Comment by krassowski** [comment]
@donhuvy you are clicking on 'increase **text editor** font size" while being in a **notebook**.

**Comment by donhuvy** [comment]
Can you explain / description detail about what you comment. I don't understand. I found a solution for see bigger text now
![image](https://github.com/jupyterlab/jupyterlab-desktop/assets/1328316/1a762af8-4e82-4f35-a4ef-c2ad7dfd5105)

**Comment by krassowski** [comment]
There are different editors in JupyterLab: notebook editor, text editor, etc. The menu item you where clicking was changing font size in text editor not in notebook. There is an issue in the JupyterLab repository tracking improvements here but I could not find it right now.
