### ISSUE TITLE
Google colaboratory run code locally on Jupyterlab-Desktop

### ISSUE THREAD

**Issue by scrwho** [jupyterlab/jupyterlab-desktop#452]
Hello Team,

Thank you for your good work.

Is it possible to run Google Colaboratory scripts in my computer locally? 

I would like to work collaboratively in short code scripts without having to use version control systems such as Github and being able to do so using Windows OS, in a simple way like sending a link for the code in some platform like Google Drive.

I do not know how to implement the steps on (https://research.google.com/colaboratory/local-runtimes.html) with the Jupyter desktop app.

**Comment by mbektas** [comment]
Currently JupyterLab Desktop's server launches do not allow passing additional arguments in order for you to be able to connect to it from Colab. Here is how we launch JupyterLab server for the Desktop application: https://github.com/jupyterlab/jupyterlab-desktop/blob/master/src/main/server.ts#L57

**Comment by mbektas** [comment]
@scrwho you can now [customize](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#server-launch-arguments) the server launch arguments. could you test if that works for you?

**Comment by mbektas** [comment]
closing since no response for long.
