### ISSUE TITLE
Can be installed Rkernel, how to install？

### ISSUE THREAD

**Issue by BornInDecember** [jupyterlab/jupyterlab-desktop#455]
Can be installed Rkernel, how to install？

**Comment by hellojinwoo** [comment]
What do you mean by "Can be installed Rkernel"?

**Comment by BornInDecember** [comment]
How to run r script in desktop version?

**Comment by hellojinwoo** [comment]
have you searched here on issues? I think I have seen one issue resoloved concerning R kernel.

**Comment by dorrajmachai** [comment]
@BornInDecember If you've set up R in JupyterLab already, it should show when you open ```jlab```. I am only speaking from experience, so some background from you would be helpful. What are you seeing when attempting to use R? What's your OS? What have you already tried? TIA.

**Comment by mbektas** [comment]
closing since no response from original poster for long. please create new issue if needed.
