### ISSUE TITLE
CHANGE THE PATH 

### ISSUE THREAD

**Issue by better319** [jupyterlab/jupyterlab-desktop#458]
when i open the app
it open de path  C:\Users\Administrator
i try to change to d:\ by file→ open from path...→ d:/
but it fail

anybody can help me ?
THK!

**Comment by krassowski** [comment]
`open from path...` is meant to open a notebook or a file based on path relative to the root directory. It looks that you are trying to change the root directory; this has to be done prior to launching JupyterLab Desktop and different ways of doing so are described in the README: https://github.com/jupyterlab/jupyterlab-desktop#launching-jupyterlab-desktop

**Comment by mbektas** [comment]
closing since no response for a long time. CLI can be used to launch in another directory. Also, new version will have ability to open another directory from UI.
