### ISSUE TITLE
Failed to find a compatible Python environment at the configured path

### ISSUE THREAD

**Issue by yangcht** [jupyterlab/jupyterlab-desktop#461]
`Failed to find a compatible Python environment at the configured path "/Users/xxx/Library/jupyterlab-desktop/jlab_server/bin/python". Environment Python package requirements are: jupyterlab >=3.1.0.`

This only happens since 3.3.4

**Comment by palewire** [comment]
I got this same bug after upgrading to 3.3.4. Broke my existing install. Ubuntu via deb.

**Comment by krassowski** [comment]
Can you share the `conda list` or `pip list` of environment you have selected?

**Comment by palewire** [comment]
I followed the more complete "uninstall" instructions in the documentation, and then reinstalled, which straightened things out. 

https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#debian-ubuntu-linux

**Comment by krassowski** [comment]
@palewire @yangcht do you remember from which version you were upgrading? Could it be older than 3.3.2-2? If so, let's close this in favour of #438

**Comment by krassowski** [comment]
Closing in favour of #438 due to lack of response.
