### ISSUE TITLE
[Question] How to edit a file not in the C Drive on Windows?

### ISSUE THREAD

**Issue by WHMHammer** [jupyterlab/jupyterlab-desktop#462]
When I navigate through the file tree in Jupyter, the root directory seems to be the C Drive. I tried to create a shortcut to my D drive, but it only appeared as a `.lnk` file instead of a subdirectory.

**Comment by mbektas** [comment]
@WHMHammer you can use CLI to launch JupyterLab Desktop in another directory. From a Command Prompt, you should be able to 
```
cd /d d:
jlab .
```

**Comment by mbektas** [comment]
this issue is fixed with 3.6.1-1 with the ability to open projects from different folders.
