### ISSUE TITLE
Processes remain after quitting JuputerLab Desktop app on Mac 

### ISSUE THREAD

**Issue by ivanistheone** [jupyterlab/jupyterlab-desktop#463]
## Description

On MacOS 11.6.3 (Big Sur), when I use JupyterLab Destkop and exit the application, I see there are still some processes running:

One is of the type: `python -m jupyterlab --no-browser --LabServerApp.schemas_dir=/Applications/JupyterLab.app/Contents/Resources/build/schemas --JupyterApp.config_file_name= --ServerApp.port=50583 --ServerApp.password= --ServerApp.allow_origin=* --ContentsManager.allow_hidden=True`

and each of these has multiple processes of the form `/Users/ivan/Library/jupyterlab-desktop/jlab_server/bin/python -m ipykernel_launcher -f /Users/ivan/Library/Jupyter/runtime/kernel-<SOMEUUID>.json`

<img width="1331" alt="Screen Shot 2022-06-29 at 1 28 18 AM" src="https://user-images.githubusercontent.com/163966/176359357-7f1c923d-d2e2-4fdc-a35b-5ed91014c8a7.png">
<img width="1331" alt="Screen Shot 2022-06-29 at 1 26 15 AM" src="https://user-images.githubusercontent.com/163966/176359372-ff21a169-9e4d-4e5e-ac3f-0bb7e836afed.png">

## Reproduce

Will try to reproduce from clean slate next time (laptop has been running for a few days so not sure what exactly could be the cause).

One thing I have been running is Django runserve from inside a notebook using `!./manage.py runserver` which kind of "blocks" that notebook until I press STOP button, but maybe I quit the app without stopping?

## Expected behavior

 No more processes after quitting app.

## Context

- Operating System and version: Mac  11.6.3
- JupyterLab-Desktop version: Version 3.3.4-2
- Installer: .dmg

**Comment by slark** [comment]
This issue is also happening for me:

## Context

* Operating System and version: macOS Monterey 12.4
* JupyterLab-Desktop version: 3.3.4-2
* Installer: .dmg
![JupyterLab-Desktop bug](https://user-images.githubusercontent.com/138076/177424920-19a4df5b-2b8d-492a-9863-d8426c50e3d2.png)

**Comment by tuanpham96** [comment]
I have also been seeing this in Ubuntu for some time now. E.g:

- When the program is still open:

```shell
$ ps aux | grep jupyter
179233  8.0  0.8 21497912 141848 ?     Sl   14:35   0:00 /opt/JupyterLab/jupyterlab-desktop
179236  0.0  0.2 16998200 46936 ?      S    14:35   0:00 /opt/JupyterLab/jupyterlab-desktop --type=zygote --no-zygote-sandbox
179237  0.0  0.2 16998200 46844 ?      S    14:35   0:00 /opt/JupyterLab/jupyterlab-desktop --type=zygote
179239  0.0  0.0 16998200 9992 ?       S    14:35   0:00 /opt/JupyterLab/jupyterlab-desktop --type=zygote
179270  3.9  0.9 17232892 156544 ?     Sl   14:35   0:00 /opt/JupyterLab/jupyterlab-desktop --type=gpu-process --field-trial-handle=14730733168570937471,10625192144191156938,131072 --disable-features=SpareRendererForSitePerProcess --user-data-dir=/home/user/.config/jupyterlab-desktop --gpu-preferences=<deleted>= --shared-files
179277  0.0  0.1 17070960 29340 ?      S    14:35   0:00 /opt/JupyterLab/jupyterlab-desktop --type=broker
179321  0.2  0.3 17063912 57080 ?      Sl   14:35   0:00 /opt/JupyterLab/jupyterlab-desktop --type=utility --utility-sub-type=network.mojom.NetworkService --field-trial-handle=14730733168570937471,10625192144191156938,131072 --disable-features=SpareRendererForSitePerProcess --lang=en-US --service-sandbox-type=none --user-data-dir=/home/user/.config/jupyterlab-desktop --shared-files=v8_context_snapshot_data:100
179328 35.9  1.5 25582128 254740 ?     Sl   14:35   0:03 /opt/JupyterLab/jupyterlab-desktop --type=renderer --user-data-dir=/home/user/.config/jupyterlab-desktop --app-path=/opt/JupyterLab/resources/app.asar --no-sandbox --no-zygote --field-trial-handle=14730733168570937471,10625192144191156938,131072 --disable-features=SpareRendererForSitePerProcess --lang=en-US --num-raster-threads=4 --enable-main-frame-before-activation --renderer-client-id=4 --no-v8-untrusted-code-mitigations --shared-files=v8_context_snapshot_data:100
179365 35.8  0.6 451428 107268 ?       Sl   14:35   0:03 python -m jupyterlab --no-browser --LabServerApp.schemas_dir=/opt/JupyterLab/resources/build/schemas --JupyterApp.config_file_name= --ServerApp.port=37491 --ServerApp.password= --ServerApp.allow_origin=* --ContentsManager.allow_hidden=True
```

- After closing jupyterlab-desktop, waiting for a few seconds:

```bash
$ ps aux | grep jupyter
179236  0.0  0.2 16998200 46936 ?      S    14:35   0:00 /opt/JupyterLab/jupyterlab-desktop --type=zygote --no-zygote-sandbox
179237  0.0  0.2 16998200 46844 ?      S    14:35   0:00 /opt/JupyterLab/jupyterlab-desktop --type=zygote
179239  0.0  0.0 16998200 9992 ?       S    14:35   0:00 /opt/JupyterLab/jupyterlab-desktop --type=zygote
179365  4.8  0.6 451428 107268 ?       Sl   14:35   0:03 python -m jupyterlab --no-browser --LabServerApp.schemas_dir=/opt/JupyterLab/resources/build/schemas --JupyterApp.config_file_name= --ServerApp.port=37491 --ServerApp.password= --ServerApp.allow_origin=* --ContentsManager.allow_hidden=True
181731  9.4  0.5  98140 81764 ?        S    14:36   0:00 python -m jupyterlab --no-browser --LabServerApp.schemas_dir=/opt/JupyterLab/resources/build/schemas --JupyterApp.config_file_name= --ServerApp.port=37491 --ServerApp.password= --ServerApp.allow_origin=* --ContentsManager.allow_hidden=True
```

- I usually have to manually kill them with:

```bash
 kill -9 $(ps aux | grep '[j]upyter' | awk '{print $2}')
```

## System

- Ubuntu 20.04.1
- Jupyterlab-Desktop Version 3.4.6-1

**Comment by mbektas** [comment]
this is fixed now with [v3.5.1-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.5.1-1). could you test and update the issue?

**Comment by ivanistheone** [comment]
I can confirm latest JupyterLab Desktop exists cleanly. (installed via the .dmg installed from https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.5.1-1) 

I only did limited testing: I opened, closed, then ran `pstree` and don't see any jupyter processes running.

If @tuanpham96 can confirm on linux too, I guess we could close this after.

Thanks to all involved in fixing this!

**Comment by tuanpham96** [comment]
Just updated and briefly tested (nothing showed up when doing `ps aux | grep -i '[j]upyter'` after closing), also worked on Ubuntu 20.04. Thanks for fixing this!
