### ISSUE TITLE
Opening second instance brings up the first instance too

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-desktop#475]
## Description

When I open second and consecutive instance of JupyterLab Desktop, the first instance gets focused **and all instances get resized, unmaximised and moved into a different place on screen**). This is a very annoying behaviour.

## Reproduce

1. Run `jlab .` in directory `a`
2. See first window appear
3. Run `jlab .` in directory `b`
4. See second window appear and first window getting focused (switching desktop workspace on Gnome, causing annoying context switch).

## Expected behavior

JupyterLab Desktop allows opening multiple instances smoothly.

## Context

- Operating System and version: Linux Ubuntu 22
- JupyterLab-Desktop version: 3.4.4
- Installer: deb

**Comment by krassowski** [comment]
I believe this is related to the following use of `requestSingleInstanceLock`:

https://github.com/jupyterlab/jupyterlab-desktop/blob/59519abc03fbaf33f061a2f629ffbc6f2a685f3e/src/main/main.ts#L282-L303

It clearly does not work on Linux (multiple instances are spawned), and the logic is wrong (the promise is not rejected if we did not get a lock; the Electron docs provide [an example](https://www.electronjs.org/docs/latest/api/app#apprequestsingleinstancelockadditionaldata) on how it should be done). But I do not agree with the premise that JupyterLab Desktop should be limited to a single instance (as explained above, I have many projects I want to work at simultaneously).

@mbektas how does it currently work on MacOS? Does running `jlab filename` spawn a new instance? If it does, I think that we can just remove the call to `requestSingleInstanceLock`.

**Comment by mbektas** [comment]
this is fixed with the latest version 3.6.1-1
