### ISSUE TITLE
menu bar disappears in MacOS 10.15.7

### ISSUE THREAD

**Issue by yessiexiv** [jupyterlab/jupyterlab-desktop#482]
I reinstalled miniconda in MacOS 10.15.7 and use Jupyter Lab in Safari. 

I should see something like this in the interface: 

<img width="886" alt="g3mF1" src="https://user-images.githubusercontent.com/110925011/186493366-2b882af7-ac5f-4119-b077-f53c88b7eaac.png">

However, the menu bar appears in white and there are missing buttons in the toolbar. I tried reinstalling everything and updating Conda but nothing seems to work. 

![WhatsApp Image 2022-08-24 at 12 37 09 PM](https://user-images.githubusercontent.com/110925011/186493511-1eeb5946-935c-42f0-8312-913abaef108e.jpeg)

Anyone could help?

**Comment by krassowski** [comment]
> Anyone could help?

I can take a look in my free time if you fill in the issue template in 100% (please edit this issue rather than opening a new one): https://github.com/jupyterlab/jupyterlab-desktop/issues/new?assignees=&labels=bug&template=bug_report.md

**Comment by krassowski** [comment]
I'm closing this issue since we have not heard back in over a month, but please reopen if you have additional details which would allow us to reproduce/act on it.
