### ISSUE TITLE
Lab extensions

### ISSUE THREAD

**Issue by nproctor** [jupyterlab/jupyterlab-desktop#49]
We should figure out an elegant way to handle lab extensions in the application. 

If were to use "jupyter labextension install <extensions>", the JupyterLab application assets are built and run in the application directory. So, if we wanted to use this command as-is with the Electron application, we really would only be using the extension tarballs created by "npm pack" and the settings. Then, we'd still have to use npm to install the extensions for the Electron app and we're basically repeating the process, or something similar to it. This would also mean that any lab extension installed in the standard JupyterLab would be installed for the Electron app. And this also requires the user to have npm installed to install a lab extension. 

Any thoughts on the best way to approach this?

**Comment by ddavidebor** [comment]
The server should not directly map to an electron app, sooner or later jupyterlab_app will support multiple backend servers.

I also think frontend-only extensions should be installable from the electron_app, if possible. The computing environment could be locked by the system admin but maybe this can guarantee some freedom for the user.

There's still the problem that the packaged app is locked. New modules needs to be installed in an external directory, such as the way [apm](https://github.com/atom/apm) does.
