### ISSUE TITLE
Scheduler

### ISSUE THREAD

**Issue by chongweising** [jupyterlab/jupyterlab-desktop#496]
Hi All! I'm a total greenhorn to Github as well as the jupyterlab desktop app on Mac. Just wondering, is there a scheduler within this app? If so, how may I get it? Thank you!

**Comment by krassowski** [comment]
There are several extensions providing scheduler functionality for JupyterLab which you can install in JupyterLab Desktop (using `conda` or `pip` in appropriate virtual environment).

**Comment by mbektas** [comment]
closing since no response for long.
