### ISSUE TITLE
Jupyter Lab Desktop Memory issue

### ISSUE THREAD

**Issue by ddharshan** [jupyterlab/jupyterlab-desktop#504]
Hi,
Could u please tell me how to check memory limitation of the Jupyter Lab Desktop and, how to increase it ?

Thank u

**Comment by mbektas** [comment]
can you provide more details about the issue you are having? any steps to reproduce?

**Comment by ddharshan** [comment]
> can you provide more details about the issue you are having? any steps to reproduce?

Actually, when i was train my model in jupyter notebook using chrome, I encountered the memory issue due to the limitation of memory . Therefore, I just want to increase the memory size of JupyterLab Desktop

**Comment by mbektas** [comment]
closing since no response for a long time.
