### ISSUE TITLE
JupyterLAB Desktop frozen 

### ISSUE THREAD

**Issue by ddharshan** [jupyterlab/jupyterlab-desktop#506]
Hi
When I train Deep Reinforcement Learning  model for more than 10hrs in JupyterLab Desktop, The screen was frozen and couldn't train model.
Can anyone help me on finding a solution for this. Do I have to increase the memory size??

OS - windows
RAM - 8GB 
Python 3
JupyterLab version - 3.4.6-1

**Comment by mbektas** [comment]
duplicate
