### ISSUE TITLE
[Bug] Inaccurate mime types icons on Linux

### ISSUE THREAD

**Issue by tuanpham96** [jupyterlab/jupyterlab-desktop#509]
## Issue

The file icons for many file types are either inaccurate, missing or defaulted to the `ipynb` icon. Here's an example:

![wrong-mimetypes-jlb](https://user-images.githubusercontent.com/42875763/200034684-2f99664b-7cdc-43cf-912e-a5794a5ecc22.png)

I couldn't find where the program references icons. This `icons` folder I saw seemed quite limited so I guess it's referenced somewhere else.

```
~/.config/jupyterlab-desktop/jlab_server/share/icons/
└── hicolor
    └── scalable
        └── apps
            ├── nbclassic.svg
            └── notebook.svg
```

## System

- Ubuntu 20.04.1
- Jupyterlab-Desktop Version 3.4.6-1

**Comment by mbektas** [comment]
I was not able to reproduce the issue on Ubuntu. are you consistently having this problem? is there a problem when opening markdown files? are they properly opened in markdown editor?

**Comment by krassowski** [comment]
@tuanpham96 do you happen to have jupytext extension installed?

**Comment by tuanpham96** [comment]
@mbektas Files would generally be opened fine, in terms of their syntax highlight if that's what you meant. 

@krassowski Yup, that was the issue. `pip uninstall` then rebuild solves it. Thanks for the tip. Do you know if there's a workaround for it?

**Comment by krassowski** [comment]
I don't know a workaround. Would you mind opening a new issue in jupytext repository to ask if there is one (after double checking that it was not discussed previously)?

**Comment by tuanpham96** [comment]
I don't think I found one though there were some discussions on file icons but I don't think I understood them, or whether they're truly the same issue. Anyway, I raised an issue over at `jupytext`. Should I close this one or keep it open for the time being?

**Comment by tuanpham96** [comment]
So technically this is not a bug, it's a feature. One can disable that globally in `~/.config/jupyter/jupytext.toml` with `notebook_extensions` field, or locally in specific places. See [this part of their documentation](https://jupytext.readthedocs.io/en/latest/paired-notebooks.html?highlight=notebook_extensions#how-to-open-scripts-with-either-the-text-or-notebook-view-in-jupyter). I will close this now. Thanks for pointing out the problem!
