### ISSUE TITLE
Can not change notebook font family and font size

### ISSUE THREAD

**Issue by flerxu** [jupyterlab/jupyterlab-desktop#514]
## Description

I can't change notebook font family and font size while I can do it with non-app jupyterlab.

## Reproduce

1. Go to 'Settings'
2. Click on 'Notebook'
3. Fill 'Font family' with 'Roboto Mono'
4. Fill 'Font Size' with 16
5. Save, but nothing been changed.

**Comment by krassowski** [comment]
Does restarting app help?

**Comment by krassowski** [comment]
I just tried changing `Font Size` and it worked even without restart. There are three fields for `Font Size` (separate for code cells, markdown cells, and raw cells). Can you double-check that you edit the right one?

**Comment by mbektas** [comment]
@flerxu is this still an issue? can you test with the latest version and update the issue?

**Comment by mef51** [comment]
I cannot change the fontFamily for the code cell after setting it in theme settings, notebook settings, text editor, code mirror.
Jupyter lab abb 4.0.0
macos 13.3
I've restarted the app, server, and computer several times

The output changes to the correct font but the cell is unchanged
<img width="455" alt="image" src="https://github.com/jupyterlab/jupyterlab-desktop/assets/1703141/4048d401-35af-418d-9297-e4d32158a857">

The same is true with a console:
<img width="282" alt="image" src="https://github.com/jupyterlab/jupyterlab-desktop/assets/1703141/842e4035-5773-4ec6-9647-efeca737284f">


Theme preferences:
```
{
    "theme": "JupyterLab Dark",
    "theme-scrollbars": true,
    "overrides": {
        "code-font-family": "consolas",
        "code-font-size": null,
        "content-font-family": null,
        "content-font-size1": null,
        "ui-font-family": null,
        "ui-font-size1": null
    }
}
```

Notebook prefs
```
{
    "codeCellConfig": {
        "codeFolding": true,
        "lineWrap": false,
        "customStyles": {
            "fontFamily": "consolas",
            "fontSize": null,
            "lineHeight": null
        },
        "fontFamily": "consolas"
    }
}
```

text editor prefs:
```
{
    "scrollPastEnd": true,
    "toolbar": [],
    "editorConfig": {
        "fontFamily": "consolas",
        "customStyles": {
            "fontFamily": "consolas",
            "fontSize": null,
            "lineHeight": null
        }
    }
}
```

**Comment by lcd522** [comment]
same issue... confused me a day

**Comment by mef51** [comment]
Installing a version earlier than 4.0.0 fixed the font issue.

**Comment by krassowski** [comment]
@mef51 @lcd522 JupyterLab [v4.0.1](https://github.com/jupyterlab/jupyterlab/releases/tag/v4.0.1) was released yesterday fixing font family setting (https://github.com/jupyterlab/jupyterlab/pull/14601). Could you please try the latest release and confirm whether this is still an issue?

**Comment by mef51** [comment]
@krassowski looks fixed! The font is correct. Thanks

**Comment by OhanazzZ** [comment]
Hi, I still experience this issue on the latest version of JupyterLab desktop. Updating to the latest version seems to have "overwritten" the original font family (it is now a different font after the upgrade) and also made it impossible to change to other font family. Not sure if related but I'm on a mac

**Comment by OhanazzZ** [comment]
Hey @krassowski
could you take a look and possibly reopen this? Thank you :)

**Comment by krassowski** [comment]
What happens if you remove the custom theme?

**Comment by OhanazzZ** [comment]
If by "remove" you mean "unselect" - I can adjust the font family using one of the 2 default themes.

I guess that means adjusting the font family is not possible with the custom theme. However the custom theme has been rendering just fine until I recently upgraded to the latest version of JupyterLab - since the recent update, the theme's default font seems to have been overwritten and cannot be adjusted.

The custom theme itself is via pip install and has not been updated for more than a year so I would think this has to do with JupyterLab.

**Comment by silverbulletmdc** [comment]
I found in 4.0.9 and 4.0.10, the font family issue is still exist. I can't change the font in "notebook" settings, but finnaly I successfully change the font by modify the "fontFamily" in "theme" settings.
![image](https://github.com/jupyterlab/jupyterlab-desktop/assets/11981375/673706fb-0053-4351-a7d4-6de09cf7c565)

**Comment by vincentye38** [comment]
I have the same issue on 4.2.5
