### ISSUE TITLE
Integration between our keyboard handling/shortcuts and the native OS ones.

### ISSUE THREAD

**Issue by ddavidebor** [jupyterlab/jupyterlab-desktop#52]
This issue is to discuss and consider if there are shortcuts that should be made more native-like.

From #3 

Definitely not urgent :smile:

**Comment by nproctor** [comment]
Some basic keyboard shortcuts have been added (copy, paste, cut, zoom in, zoom out). I'm planning on adding "quit". What additional shortcuts should be implemented? Should there be some additional access point (i.e. through the menubar) for these shortcuts?

**Comment by mbektas** [comment]
not relevant to latest version
