### ISSUE TITLE
Cannot change  font size in output cells

### ISSUE THREAD

**Issue by HTofi** [jupyterlab/jupyterlab-desktop#524]
## Description

I'm trying to edit a Julia notebook file. The default font size is too small, and I can't find an option in advanced settings to change the font size in output cells. Changing font size in `Code Cell Configuration` only changes input font size.

## Reproduce

1. Go to `Settings > Advanced settings editor > Notebook > Code Cell Configuration > Font Size`
2. Change font size to a certain value
3. Check the notebook file. Only input font size changes.

## Context

- Operating System and version:  Manjaro Linux
- JupyterLab-Desktop version:  3.5.0-1
- Installer:  AUR

<details><summary>Troubleshoot Output</summary>
<pre>

$PATH:
        /home/htofi/.local/bin
        /usr/local/sbin
        /usr/local/bin
        /usr/bin
        /usr/lib/jvm/default/bin
        /usr/bin/site_perl
        /usr/bin/vendor_perl
        /usr/bin/core_perl
        /usr/lib/jvm/default/bin

sys.path:
        /usr/bin
        /usr/lib/python310.zip
        /usr/lib/python3.10
        /usr/lib/python3.10/lib-dynload
        /usr/lib/python3.10/site-packages

sys.executable:
        /usr/bin/python

sys.version:
        3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]

platform.platform():
        Linux-5.15.78-1-MANJARO-x86_64-with-glibc2.36

which -a jupyter:
        /usr/bin/jupyter

pip list:
        Package              Version
        -------------------- -----------
        anyio                3.6.2
        apparmor             3.1.2
        appdirs              1.4.4
        application-utility  1.3.2
        argon2-cffi          21.3.0
        argon2-cffi-bindings 21.2.0
        asttokens            2.1.0
        async-generator      1.10
        attrs                22.1.0
        autocommand          2.2.1
        Babel                2.11.0
        backcall             0.2.0
        beautifulsoup4       4.11.1
        bleach               5.0.1
        btrfsutil            6.0.1
        certifi              2022.9.24
        cffi                 1.15.1
        chardet              5.0.0
        contourpy            1.0.6
        cryptography         38.0.3
        cupshelpers          1.0
        cycler               0.11.0
        Cython               0.29.32
        debugpy              1.6.3
        decorator            5.1.1
        defusedxml           0.7.1
        deprecation          2.1.0
        distro               1.8.0
        docopt               0.6.2
        entrypoints          0.4
        executing            1.2.0
        fastjsonschema       2.16.2
        fonttools            4.38.0
        gpg                  1.18.0
        idna                 3.4
        inflect              6.0.2
        ipykernel            6.17.1
        ipython              8.6.0
        ipython-genutils     0.2.0
        ipywidgets           8.0.2
        jaraco.context       4.1.2
        jaraco.functools     3.5.2
        jaraco.text          3.10.0
        jedi                 0.18.1
        Jinja2               3.1.2
        json5                0.9.10
        jsonschema           4.17.0
        jupyter_client       7.4.5
        jupyter_core         5.0.0
        jupyter_packaging    0.12.3
        jupyter-server       1.23.1
        jupyterlab           3.5.0
        jupyterlab-pygments  0.2.2
        jupyterlab_server    2.16.3
        jupyterthemes        0.20.0
        keyutils             0.6
        kiwisolver           1.4.4
        lesscpy              0.15.1
        LibAppArmor          3.1.2
        lit                  14.0.6.dev0
        lxml                 4.9.1
        manjaro-sdk          0.1
        MarkupSafe           2.1.1
        matplotlib           3.6.2
        matplotlib-inline    0.1.6
        mistune              2.0.4
        more-itertools       9.0.0
        nbclassic            0.4.8
        nbclient             0.7.0
        nbconvert            7.2.4
        nbformat             5.7.0
        nest-asyncio         1.5.6
        netsnmp-python       1.0a1
        nftables             0.1
        notebook             6.5.2
        notebook_shim        0.2.2
        npyscreen            4.10.5
        numpy                1.23.4
        ordered-set          4.1.0
        packaging            21.3
        pacman-mirrors       4.23.2
        pandocfilters        1.5.0
        parso                0.8.3
        pexpect              4.8.0
        pickleshare          0.7.5
        Pillow               9.3.0
        pip                  22.3.1
        platformdirs         2.5.3
        ply                  3.11
        prometheus-client    0.15.0
        prompt-toolkit       3.0.32
        psutil               5.9.4
        ptyprocess           0.7.0
        pure-eval            0.2.2
        pycairo              1.21.0
        pycparser            2.21
        pycups               2.0.1
        pycurl               7.45.1
        pydantic             1.10.2
        Pygments             2.13.0
        PyGObject            3.42.2
        pyOpenSSL            22.1.0
        pyparsing            3.0.9
        PyQt5                5.15.7
        PyQt5-sip            12.11.0
        pyrsistent           0.19.2
        PySide6              6.4.0.1
        pysmbc               1.0.23
        PySocks              1.7.1
        python-dateutil      2.8.2
        pytz                 2022.6
        PyYAML               6.0
        pyzmq                24.0.1
        reportlab            3.6.12
        requests             2.28.1
        requests-unixsocket  0.3.0
        Send2Trash           1.8.0
        setuptools           65.1.1
        shiboken6            6.4.0.1
        six                  1.16.0
        sniffio              1.3.0
        soupsieve            2.3.2.post1
        stack-data           0.6.1
        systemd-python       235
        team                 1.0
        terminado            0.17.0
        testpath             0.6.0
        tinycss2             1.2.1
        tomli                2.0.1
        tomlkit              0.11.6
        torbrowser-launcher  0.3.5
        tornado              6.2
        traitlets            5.5.0
        trove-classifiers    2022.10.19
        typing_extensions    4.4.0
        udiskie              2.4.2
        urllib3              1.26.12
        validate-pyproject   0.10.1
        wcwidth              0.2.5
        webencodings         0.5.1
        websocket-client     1.4.2
        wheel                0.38.2
        widgetsnbextension   4.0.3
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
DevTools failed to load source map: Could not load content for http://localhost:41587/opt/JupyterLab/resources/app.asar/build/out/main/preload.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:41587/desktop-app-assets/browser.bundle.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

</pre>
</details>

**Comment by JasonWeill** [comment]
We have an issue in JupyterLab to track this: https://github.com/jupyterlab/jupyterlab/issues/12178 . Resolving this issue as a duplicate. Thanks for your contribution!
