### ISSUE TITLE
JupyterLab Desktop will not allow use of external python on mac if `~/Library/jupyterlab-desktop` doesn't already exist

### ISSUE THREAD

**Issue by dimitriye98** [jupyterlab/jupyterlab-desktop#525]
## Description

On a brand new installation, when the Server Configuration window pops up, if `~/Library/jupyterlab-desktop` doesn't already exist, attempting to select a local python installation will appear to succeed if pointed at an appropriate installation, but the changes will not get committed to file, and restart will greet the user with the server configuration window again.

## Reproduce

1. Install JupyterLab Desktop on Mac.
2. Attempt to "Use a custom Python environment"
3. Point it to a valid environment such that no error message pops up.
4. The directory `~/Library/jupyterlab-desktop` will not be created, and consequently, neither will the contained `jupyterlab-desktop-data` file.
5. When the restart completes, the user will be prompted with the Server Configuration window again.

## How I diagnosed it

I really wanted to use my local python installation rather than the bundled one, so I poked around in the codebase until I figured out which field in the JSON was for it. Then, after installation, I modified the `pythonPath` field in the json manually (which later turned out to be unnecessary, the configuration page works just fine *after* the directory is created). Once it worked, I was curious to figure out what the issue was on initial install, and after deleting the `~/Library/jupyterlab-desktop` directory, found that it wasn't getting created when attempting to configure.

## Expected behavior

The directory and config file should get created, and upon restart, JupyterLab Desktop should start properly.

## Context

- Operating System and version: macOS Ventura 13.0.1
- JupyterLab-Desktop version: 3.5.0-1
- Installer: Homebrew cask

**Comment by mbektas** [comment]
@dimitriye98 thanks so much for debugging this issue and sharing your findings. I have a fix for it and added to this [PR](https://github.com/jupyterlab/jupyterlab-desktop/pull/513).

**Comment by mbektas** [comment]
this is fixed now with [v3.5.1-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.5.1-1). could you test and update the issue?

**Comment by mbektas** [comment]
closing since no response for a long time. this issue is expected to be resolved with v3.5.1-1
