### ISSUE TITLE
Improve 'reactivate' time of window on macOS

### ISSUE THREAD

**Issue by lucbouchard1** [jupyterlab/jupyterlab-desktop#53]
macOS handles applications differently from Windows/Linux in that when you close a window, the app continues to run in the background. When the application is in this backgrounded state, the user is supposed to be able to 'reactivate' the application window by clicking the application icon.

This currently works in the electron app; however, the time for the window to reappear is almost equal to the time it takes the app to startup, making the feature pretty much useless. We need to refactor the reactivate code to improve performance. This could be accomplished by not showing the splash screen on reactivate, and not destructing the electron BrowserWindow when the window is closed.

**Comment by mbektas** [comment]
this is not applicable to latest implementation
