### ISSUE TITLE
The title bar gets zoomed in/out when focused

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-desktop#534]
On Linux <kbd>ctrl</kbd> + <kbd>+</kbd>/<kbd>ctrl</kbd> + <kbd>-</kbd>:

![Screenshot from 2022-12-08 22-31-02](https://user-images.githubusercontent.com/5832902/206586894-a60dba33-5006-41df-bb98-283d3988285b.png)

![Screenshot from 2022-12-08 22-31-09](https://user-images.githubusercontent.com/5832902/206586879-282f0465-fa93-40f6-8b8f-6d9a42cfff82.png)

I would expect the titlebar to be non-resizable (I think all window managers behave like that?), but if it really is intended, it should not cut text.

**Comment by mbektas** [comment]
this is fixed now with [v3.5.1-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.5.1-1)
