### ISSUE TITLE
Cannot resize the window up using titlebar left side

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-desktop#535]
In 3.5.1-1 RC I cannot grab the larger part titlebar for resizing on Ubuntu. In particular the bit marked with red does not work while the bit marked with green works fine:

![titlebar-desktop-issue](https://user-images.githubusercontent.com/5832902/206666536-395bee49-cb93-47b5-b857-85f6dbc36d4c.png)

The orange bits for changing the width do not work either.

**Comment by krassowski** [comment]
Small correction and a hint on the underlying problem: there is a small space between hamburger icon and minimize button which cannot be used for resizing either. It suggests that buttons have it right (I guess `-webkit-user-select: none;  -webkit-app-region: drag;`) but the rest of the bar does not.

![titlebar-desktop-issue](https://user-images.githubusercontent.com/5832902/206670874-6e34e4f3-a6e0-4fad-92a4-709e846bf4ce.png)

Maybe we need to have a nested div: container which has 1-2 px size border and is non-draggable and inside the content div which stretches to full available width/height which is draggable?

**Comment by mbektas** [comment]
this is fixed now with [v3.5.1-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.5.1-1)
