### ISSUE TITLE
Title bar blur state is missing

### ISSUE THREAD

**Issue by krassowski** [jupyterlab/jupyterlab-desktop#538]
When switching between two JupyterLab Dekstop windows it is impossible to tell which on is active because title bar does not change state. Can you tell which one is active when I am switching?

![no-unfocus-state](https://user-images.githubusercontent.com/5832902/206672645-5d21f943-d4ac-4067-a549-7a85648b7f9a.gif)

Compare it with native title bars:

![native-unfocus](https://user-images.githubusercontent.com/5832902/206672896-efdaf2cf-19ff-4bce-bc5c-5a5f17929e8e.gif)

**Comment by krassowski** [comment]
Of note this is properly implemented in https://github.com/AlexTorresSk/custom-electron-titlebar.

**Comment by mbektas** [comment]
this is fixed now with [v3.5.1-1](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v3.5.1-1)
