### ISSUE TITLE
Error when launching JupyterLab

### ISSUE THREAD

**Issue by manil16** [jupyterlab/jupyterlab-desktop#542]
Hi
I can't open jupyterlab. when I tried to launch, it just came an error. 

![image](https://user-images.githubusercontent.com/120378310/207028169-27092f1e-db77-483f-8d01-e8863b757d29.png)

**Comment by mbektas** [comment]
@manil16 can you provide more details about the issue you are having? which OS, app version? are you using a custom environment? steps to reproduce?

**Comment by JasonWeill** [comment]
@manil16 We need some additional info, as @mbektas requested, to help diagnose this issue. Can you please provide the OS, app version, and other info requested?
