### ISSUE TITLE
Selected theme is not remembered

### ISSUE THREAD

**Issue by apcamargo** [jupyterlab/jupyterlab-desktop#543]
## Description

JupyterLab always follows my system theme (dark). If I change the theme to Light, it qwill work until I restart the app.

## Reproduce

1. Set the OS theme to Dark.
2. Open JupyterLab, it should be using the dark theme.
3. Chenge to the Light theme and close JupyterLab.
4. Open JupyterLab again, it should be using the Dark theme again.

## Expected behavior

JupyterLab should remember the chosen theme instead of trying to match the system's theme.

## Context

- Operating System and version: macOS 13.0.1 
- JupyterLab-Desktop version: 3.5.1
- Installer: brew

**Comment by mbektas** [comment]
@apcamargo if you want to set different theme for JupyterLab view and the rest of JupyterLab Desktop then you need to uncheck "Sync JupyterLab Theme" option in Preferences. can you try that?

<img width="501" alt="no theme sync" src="https://user-images.githubusercontent.com/40003442/208219598-b70f3e97-26b3-473b-a587-38ed77ace1f7.png">

**Comment by apcamargo** [comment]
It worked. Thanks!

I hadn't seen the hamburger button there on the upper right corner.

**Comment by krassowski** [comment]
Closing as resolved. Please feel welcome to contribute to documentation if you think the hamburger icons should be better documented.
