### ISSUE TITLE
Julia widgets not working

### ISSUE THREAD

**Issue by HTofi** [jupyterlab/jupyterlab-desktop#545]
## Description

The widgets provided by Julia's `Interact` package cannot be displayed in output cells.

## Reproduce

This is an example of a `@manipulate` slider which doesn't work with my Jupyterlab desktop installation:

```
using Plots
using Interact

u(x, t) = 1/2 * (sin(x + t) - sin(t - x))

x = 1:0.01:5
@manipulate for tᵢ in 0:0.1:1
    y = [u(x[i], tᵢ) for i in 1:length(x)]
    plot(x, y)
end
```

In the output cell only a plot can be seen, but the slider doesn't show up. No error messages are thrown by the Julia kernel.

## Context

- Operating System and version: Manjaro Linux
- JupyterLab-Desktop version: 3.5.0
- Installer: AUR
- WebIO extension installed with `pip`

**Comment by JasonWeill** [comment]
Have you tried using this same notebook with `jupyterlab` as installed by Conda or Mamba, or with Jupyter Notebook?

**Comment by HTofi** [comment]
OK, I don't know what was the problem exactly, but it seems to be solved now after I updated Julia. Sorry for bothering you!

**Comment by JasonWeill** [comment]
No problem! Please reach out again if you see any other bugs with JupyterLab Desktop.
