### ISSUE TITLE
Can't launch from command line

### ISSUE THREAD

**Issue by AJSchiller** [jupyterlab/jupyterlab-desktop#547]
## Description

1. Unable to launch JupyterLab Desktop from the command line. Depending on usage, different errors occur. Namely, command `jlab` launches a Node.js shell, while `jlab /path/to/something` returns `Error: Cannot find module '/path/to/something'`. Full outputs:
```
(jlab-test) USER@COMPUTER:~$ jlab
Welcome to Node.js v16.17.1.
Type ".help" for more information.
> .exit
(jlab-test) USER@COMPUTER:~$ jlab .
node:internal/modules/cjs/loader:966
  throw err;
  ^

Error: Cannot find module '/home/$USER'
    at Module._resolveFilename (node:internal/modules/cjs/loader:963:15)
    at Module._load (node:internal/modules/cjs/loader:811:27)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
(jlab-test) USER@COMPUTER:~$ jlab Documents/test.ipynb
/home/$USER/Documents/test.ipynb:2
 "cells": [
        ^

SyntaxError: Unexpected token ':'
    at Object.compileFunction (node:vm:360:18)
    at wrapSafe (node:internal/modules/cjs/loader:1062:15)
    at Module._compile (node:internal/modules/cjs/loader:1097:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1196:10)
    at Module.load (node:internal/modules/cjs/loader:1011:32)
    at Module._load (node:internal/modules/cjs/loader:846:12)
    at f._load (node:electron/js2c/asar_bundle:2:13328)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
```

2. Additionally, `jlab --version` returns the version of Node.js.

3. Command `jlab --verbose 4` (as indicated for logging purposes here) returns error:
```
(jlab-test) USER@COMPUTER:~$ jlab --verbose 4
/opt/JupyterLab/jupyterlab-desktop: bad option: --verbose
```

Behaviour is the same in base environment and in test environment created as described in  https://jupyterlab.readthedocs.io/en/latest/getting_started/issue.html . Exception: command `jupyter troubleshoot` (outputs under 'Context', below) works as expected in test environment, but returns 'jupyter not found' in base environment.

## Steps to reproduce
* Run `jlab` with or without specifying path to directory or notebook (errors should vary as described above).

OR

* Run `jlab --version`.

## Context

- Operating System and version: Linux Mint 20.3
- JupyterLab-Desktop version: 3.5.1-1
- Installer: .deb

<details><summary>Troubleshoot Output</summary>
<pre>
$PATH:
	/home/$USER/.local/bin
	/home/$USER/bin
	/home/$USER/.local/bin
	/home/$USER/miniconda3/envs/jlab-test/bin
	/home/$USER/.config/jupyterlab-desktop/jlab_server/condabin
	/home/$USER/.local/bin
	/home/$USER/bin
	/usr/local/sbin
	/usr/local/bin
	/usr/sbin
	/usr/bin
	/sbin
	/bin
	/usr/games
	/usr/local/games
	/snap/bin
	/home/$USER/.local/bin
	/usr/local/texlive/2022/bin/x86_64-linux

sys.path:
	/home/$USER/miniconda3/envs/jlab-test/bin
	/home/$USER/miniconda3/envs/jlab-test/lib/python311.zip
	/home/$USER/miniconda3/envs/jlab-test/lib/python3.11
	/home/$USER/miniconda3/envs/jlab-test/lib/python3.11/lib-dynload
	/home/$USER/miniconda3/envs/jlab-test/lib/python3.11/site-packages

sys.executable:
	/home/$USER/miniconda3/envs/jlab-test/bin/python

sys.version:
	5.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:40) [GCC 10.4.0]

platform.platform():
	Linux-5.15.0-56-generic-x86_64-with-glibc2.31

which -a jupyter:
	/home/$USER/miniconda3/envs/jlab-test/bin/jupyter

pip list:
	Package                       Version
	----------------------------- -----------
	anyio                         3.6.2
	argon2-cffi                   21.3.0
	argon2-cffi-bindings          21.2.0
	asttokens                     2.2.1
	attrs                         22.2.0
	Babel                         2.11.0
	backcall                      0.2.0
	backports.functools-lru-cache 1.6.4
	beautifulsoup4                4.11.1
	bleach                        5.0.1
	brotlipy                      0.7.0
	certifi                       2022.12.7
	cffi                          1.15.1
	charset-normalizer            2.1.1
	comm                          0.1.2
	cryptography                  38.0.4
	debugpy                       1.6.4
	decorator                     5.1.1
	defusedxml                    0.7.1
	entrypoints                   0.4
	executing                     1.2.0
	fastjsonschema                2.16.2
	flit_core                     3.8.0
	idna                          3.4
	importlib-metadata            5.2.0
	importlib-resources           5.10.1
	ipykernel                     6.19.4
	ipython                       8.7.0
	ipython-genutils              0.2.0
	jedi                          0.18.2
	Jinja2                        3.1.2
	json5                         0.9.5
	jsonschema                    4.17.3
	jupyter_client                7.4.8
	jupyter_core                  5.1.0
	jupyter-events                0.5.0
	jupyter_server                2.0.5
	jupyter_server_terminals      0.4.3
	jupyterlab                    3.5.2
	jupyterlab-pygments           0.2.2
	jupyterlab_server             2.17.0
	MarkupSafe                    2.1.1
	matplotlib-inline             0.1.6
	mistune                       2.0.4
	nbclassic                     0.4.8
	nbclient                      0.7.2
	nbconvert                     7.2.7
	nbformat                      5.7.1
	nest-asyncio                  1.5.6
	notebook                      6.5.2
	notebook_shim                 0.2.2
	packaging                     22.0
	pandocfilters                 1.5.0
	parso                         0.8.3
	pexpect                       4.8.0
	pickleshare                   0.7.5
	pip                           22.3.1
	pkgutil_resolve_name          1.3.10
	platformdirs                  2.6.0
	prometheus-client             0.15.0
	prompt-toolkit                3.0.36
	psutil                        5.9.4
	ptyprocess                    0.7.0
	pure-eval                     0.2.2
	pycparser                     2.21
	Pygments                      2.13.0
	pyOpenSSL                     22.1.0
	pyrsistent                    0.19.2
	PySocks                       1.7.1
	python-dateutil               2.8.2
	python-json-logger            2.0.4
	pytz                          2022.7
	PyYAML                        6.0
	pyzmq                         24.0.1
	requests                      2.28.1
	Send2Trash                    1.8.0
	setuptools                    65.6.3
	six                           1.16.0
	sniffio                       1.3.0
	soupsieve                     2.3.2.post1
	stack-data                    0.6.2
	terminado                     0.17.1
	tinycss2                      1.2.1
	tomli                         2.0.1
	tornado                       6.2
	traitlets                     5.8.0
	typing_extensions             4.4.0
	urllib3                       1.26.13
	wcwidth                       0.2.5
	webencodings                  0.5.1
	websocket-client              1.4.2
	wheel                         0.38.4
	zipp                          3.11.0

conda list:
	# packages in environment at /home/$USER/miniconda3/envs/jlab-test:
	#
	# Name                    Version                   Build  Channel
	_ipython_minor_entry_point 8.7.0                h0c17e10_0    conda-forge
	_libgcc_mutex             0.1                 conda_forge    conda-forge
	_openmp_mutex             4.5                       2_gnu    conda-forge
	anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
	argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
	argon2-cffi-bindings      21.2.0          py311hd4cff14_3    conda-forge
	asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
	attrs                     22.2.0             pyh71513ae_0    conda-forge
	babel                     2.11.0             pyhd8ed1ab_0    conda-forge
	backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
	backports                 1.0                pyhd8ed1ab_3    conda-forge
	backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
	beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
	bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
	brotlipy                  0.7.0           py311hd4cff14_1005    conda-forge
	bzip2                     1.0.8                h7f98852_4    conda-forge
	ca-certificates           2022.12.7            ha878542_0    conda-forge
	certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
	cffi                      1.15.1          py311h409f033_3    conda-forge
	charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
	comm                      0.1.2              pyhd8ed1ab_0    conda-forge
	cryptography              38.0.4          py311h42a1071_0    conda-forge
	debugpy                   1.6.4           py311ha362b79_0    conda-forge
	decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
	defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
	entrypoints               0.4                pyhd8ed1ab_0    conda-forge
	executing                 1.2.0              pyhd8ed1ab_0    conda-forge
	flit-core                 3.8.0              pyhd8ed1ab_0    conda-forge
	idna                      3.4                pyhd8ed1ab_0    conda-forge
	importlib-metadata        5.2.0              pyha770c72_0    conda-forge
	importlib_resources       5.10.1             pyhd8ed1ab_1    conda-forge
	ipykernel                 6.19.4             pyh210e3f2_0    conda-forge
	ipython                   8.7.0              pyh41d4057_0    conda-forge
	ipython_genutils          0.2.0                      py_1    conda-forge
	jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
	jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
	json5                     0.9.5              pyh9f0ad1d_0    conda-forge
	jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
	jupyter_client            7.4.8              pyhd8ed1ab_0    conda-forge
	jupyter_core              5.1.0           py311h38be061_0    conda-forge
	jupyter_events            0.5.0              pyhd8ed1ab_1    conda-forge
	jupyter_server            2.0.5              pyhd8ed1ab_1    conda-forge
	jupyter_server_terminals  0.4.3              pyhd8ed1ab_0    conda-forge
	jupyterlab                3.5.2              pyhd8ed1ab_0    conda-forge
	jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
	jupyterlab_server         2.17.0             pyhd8ed1ab_0    conda-forge
	ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
	libffi                    3.4.2                h7f98852_5    conda-forge
	libgcc-ng                 12.2.0              h65d4601_19    conda-forge
	libgomp                   12.2.0              h65d4601_19    conda-forge
	libnsl                    2.0.0                h7f98852_0    conda-forge
	libsodium                 1.0.18               h36c2ea0_1    conda-forge
	libsqlite                 3.40.0               h753d276_0    conda-forge
	libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
	libuuid                   2.32.1            h7f98852_1000    conda-forge
	libzlib                   1.2.13               h166bdaf_4    conda-forge
	markupsafe                2.1.1           py311hd4cff14_2    conda-forge
	matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
	mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
	nbclassic                 0.4.8              pyhd8ed1ab_0    conda-forge
	nbclient                  0.7.2              pyhd8ed1ab_0    conda-forge
	nbconvert                 7.2.7              pyhd8ed1ab_0    conda-forge
	nbconvert-core            7.2.7              pyhd8ed1ab_0    conda-forge
	nbconvert-pandoc          7.2.7              pyhd8ed1ab_0    conda-forge
	nbformat                  5.7.1              pyhd8ed1ab_0    conda-forge
	ncurses                   6.3                  h27087fc_1    conda-forge
	nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
	notebook                  6.5.2              pyha770c72_1    conda-forge
	notebook-shim             0.2.2              pyhd8ed1ab_0    conda-forge
	openssl                   3.0.7                h0b41bf4_1    conda-forge
	packaging                 22.0               pyhd8ed1ab_0    conda-forge
	pandoc                    2.19.2               h32600fe_1    conda-forge
	pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
	parso                     0.8.3              pyhd8ed1ab_0    conda-forge
	pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
	pickleshare               0.7.5                   py_1003    conda-forge
	pip                       22.3.1             pyhd8ed1ab_0    conda-forge
	pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
	platformdirs              2.6.0              pyhd8ed1ab_0    conda-forge
	prometheus_client         0.15.0             pyhd8ed1ab_0    conda-forge
	prompt-toolkit            3.0.36             pyha770c72_0    conda-forge
	psutil                    5.9.4           py311hd4cff14_0    conda-forge
	ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
	pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
	pycparser                 2.21               pyhd8ed1ab_0    conda-forge
	pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
	pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
	pyrsistent                0.19.2          py311hd4cff14_0    conda-forge
	pysocks                   1.7.1              pyha2e5f31_6    conda-forge
	python                    3.11.0          ha86cf86_0_cpython    conda-forge
	python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
	python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
	python-json-logger        2.0.4              pyhd8ed1ab_0    conda-forge
	python_abi                3.11                    3_cp311    conda-forge
	pytz                      2022.7             pyhd8ed1ab_0    conda-forge
	pyyaml                    6.0             py311hd4cff14_5    conda-forge
	pyzmq                     24.0.1          py311ha4b6469_1    conda-forge
	readline                  8.1.2                h0f457ee_0    conda-forge
	requests                  2.28.1             pyhd8ed1ab_1    conda-forge
	send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
	setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
	six                       1.16.0             pyh6c4a22f_0    conda-forge
	sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
	soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
	stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
	terminado                 0.17.1             pyh41d4057_0    conda-forge
	tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
	tk                        8.6.12               h27826a3_0    conda-forge
	tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
	tornado                   6.2             py311hd4cff14_1    conda-forge
	traitlets                 5.8.0              pyhd8ed1ab_0    conda-forge
	typing_extensions         4.4.0              pyha770c72_0    conda-forge
	tzdata                    2022g                h191b570_0    conda-forge
	urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
	wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
	webencodings              0.5.1                      py_1    conda-forge
	websocket-client          1.4.2              pyhd8ed1ab_0    conda-forge
	wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
	xz                        5.2.6                h166bdaf_0    conda-forge
	yaml                      0.2.5                h7f98852_2    conda-forge
	zeromq                    4.3.4                h9c3ff4c_1    conda-forge
	zipp                      3.11.0             pyhd8ed1ab_0    conda-forge

conda env:
	name: /home/$USER/miniconda3/envs/jlab-test
	channels:
	  - conda-forge
	dependencies:
	  - _ipython_minor_entry_point=8.7.0=h0c17e10_0
	  - _libgcc_mutex=0.1=conda_forge
	  - _openmp_mutex=4.5=2_gnu
	  - anyio=3.6.2=pyhd8ed1ab_0
	  - argon2-cffi=21.3.0=pyhd8ed1ab_0
	  - argon2-cffi-bindings=21.2.0=py311hd4cff14_3
	  - asttokens=2.2.1=pyhd8ed1ab_0
	  - attrs=22.2.0=pyh71513ae_0
	  - babel=2.11.0=pyhd8ed1ab_0
	  - backcall=0.2.0=pyh9f0ad1d_0
	  - backports=1.0=pyhd8ed1ab_3
	  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
	  - beautifulsoup4=4.11.1=pyha770c72_0
	  - bleach=5.0.1=pyhd8ed1ab_0
	  - brotlipy=0.7.0=py311hd4cff14_1005
	  - bzip2=1.0.8=h7f98852_4
	  - ca-certificates=2022.12.7=ha878542_0
	  - certifi=2022.12.7=pyhd8ed1ab_0
	  - cffi=1.15.1=py311h409f033_3
	  - charset-normalizer=2.1.1=pyhd8ed1ab_0
	  - comm=0.1.2=pyhd8ed1ab_0
	  - cryptography=38.0.4=py311h42a1071_0
	  - debugpy=1.6.4=py311ha362b79_0
	  - decorator=5.1.1=pyhd8ed1ab_0
	  - defusedxml=0.7.1=pyhd8ed1ab_0
	  - entrypoints=0.4=pyhd8ed1ab_0
	  - executing=1.2.0=pyhd8ed1ab_0
	  - flit-core=3.8.0=pyhd8ed1ab_0
	  - idna=3.4=pyhd8ed1ab_0
	  - importlib-metadata=5.2.0=pyha770c72_0
	  - importlib_resources=5.10.1=pyhd8ed1ab_1
	  - ipykernel=6.19.4=pyh210e3f2_0
	  - ipython=8.7.0=pyh41d4057_0
	  - ipython_genutils=0.2.0=py_1
	  - jedi=0.18.2=pyhd8ed1ab_0
	  - jinja2=3.1.2=pyhd8ed1ab_1
	  - json5=0.9.5=pyh9f0ad1d_0
	  - jsonschema=4.17.3=pyhd8ed1ab_0
	  - jupyter_client=7.4.8=pyhd8ed1ab_0
	  - jupyter_core=5.1.0=py311h38be061_0
	  - jupyter_events=0.5.0=pyhd8ed1ab_1
	  - jupyter_server=2.0.5=pyhd8ed1ab_1
	  - jupyter_server_terminals=0.4.3=pyhd8ed1ab_0
	  - jupyterlab=3.5.2=pyhd8ed1ab_0
	  - jupyterlab_pygments=0.2.2=pyhd8ed1ab_0
	  - jupyterlab_server=2.17.0=pyhd8ed1ab_0
	  - ld_impl_linux-64=2.39=hcc3a1bd_1
	  - libffi=3.4.2=h7f98852_5
	  - libgcc-ng=12.2.0=h65d4601_19
	  - libgomp=12.2.0=h65d4601_19
	  - libnsl=2.0.0=h7f98852_0
	  - libsodium=1.0.18=h36c2ea0_1
	  - libsqlite=3.40.0=h753d276_0
	  - libstdcxx-ng=12.2.0=h46fd767_19
	  - libuuid=2.32.1=h7f98852_1000
	  - libzlib=1.2.13=h166bdaf_4
	  - markupsafe=2.1.1=py311hd4cff14_2
	  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
	  - mistune=2.0.4=pyhd8ed1ab_0
	  - nbclassic=0.4.8=pyhd8ed1ab_0
	  - nbclient=0.7.2=pyhd8ed1ab_0
	  - nbconvert=7.2.7=pyhd8ed1ab_0
	  - nbconvert-core=7.2.7=pyhd8ed1ab_0
	  - nbconvert-pandoc=7.2.7=pyhd8ed1ab_0
	  - nbformat=5.7.1=pyhd8ed1ab_0
	  - ncurses=6.3=h27087fc_1
	  - nest-asyncio=1.5.6=pyhd8ed1ab_0
	  - notebook=6.5.2=pyha770c72_1
	  - notebook-shim=0.2.2=pyhd8ed1ab_0
	  - openssl=3.0.7=h0b41bf4_1
	  - packaging=22.0=pyhd8ed1ab_0
	  - pandoc=2.19.2=h32600fe_1
	  - pandocfilters=1.5.0=pyhd8ed1ab_0
	  - parso=0.8.3=pyhd8ed1ab_0
	  - pexpect=4.8.0=pyh1a96a4e_2
	  - pickleshare=0.7.5=py_1003
	  - pip=22.3.1=pyhd8ed1ab_0
	  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_0
	  - platformdirs=2.6.0=pyhd8ed1ab_0
	  - prometheus_client=0.15.0=pyhd8ed1ab_0
	  - prompt-toolkit=3.0.36=pyha770c72_0
	  - psutil=5.9.4=py311hd4cff14_0
	  - ptyprocess=0.7.0=pyhd3deb0d_0
	  - pure_eval=0.2.2=pyhd8ed1ab_0
	  - pycparser=2.21=pyhd8ed1ab_0
	  - pygments=2.13.0=pyhd8ed1ab_0
	  - pyopenssl=22.1.0=pyhd8ed1ab_0
	  - pyrsistent=0.19.2=py311hd4cff14_0
	  - pysocks=1.7.1=pyha2e5f31_6
	  - python=3.11.0=ha86cf86_0_cpython
	  - python-dateutil=2.8.2=pyhd8ed1ab_0
	  - python-fastjsonschema=2.16.2=pyhd8ed1ab_0
	  - python-json-logger=2.0.4=pyhd8ed1ab_0
	  - python_abi=3.11=3_cp311
	  - pytz=2022.7=pyhd8ed1ab_0
	  - pyyaml=6.0=py311hd4cff14_5
	  - pyzmq=24.0.1=py311ha4b6469_1
	  - readline=8.1.2=h0f457ee_0
	  - requests=2.28.1=pyhd8ed1ab_1
	  - send2trash=1.8.0=pyhd8ed1ab_0
	  - setuptools=65.6.3=pyhd8ed1ab_0
	  - six=1.16.0=pyh6c4a22f_0
	  - sniffio=1.3.0=pyhd8ed1ab_0
	  - soupsieve=2.3.2.post1=pyhd8ed1ab_0
	  - stack_data=0.6.2=pyhd8ed1ab_0
	  - terminado=0.17.1=pyh41d4057_0
	  - tinycss2=1.2.1=pyhd8ed1ab_0
	  - tk=8.6.12=h27826a3_0
	  - tomli=2.0.1=pyhd8ed1ab_0
	  - tornado=6.2=py311hd4cff14_1
	  - traitlets=5.8.0=pyhd8ed1ab_0
	  - typing_extensions=4.4.0=pyha770c72_0
	  - tzdata=2022g=h191b570_0
	  - urllib3=1.26.13=pyhd8ed1ab_0
	  - wcwidth=0.2.5=pyh9f0ad1d_2
	  - webencodings=0.5.1=py_1
	  - websocket-client=1.4.2=pyhd8ed1ab_0
	  - wheel=0.38.4=pyhd8ed1ab_0
	  - xz=5.2.6=h166bdaf_0
	  - yaml=0.2.5=h7f98852_2
	  - zeromq=4.3.4=h9c3ff4c_1
	  - zipp=3.11.0=pyhd8ed1ab_0
	prefix: /home/$USER/miniconda3/envs/jlab-test
</pre>
</details>

Logs
See item 3 under 'Description', above.

**Comment by krassowski** [comment]
Linking back to initial [Discourse thread](https://discourse.jupyter.org/t/jlab-command-launches-node-js-shell-instead-of-jupyterlab-desktop/) with things already tried. @mbektas any ideas?

**Comment by mbektas** [comment]
@AJSchiller have you used the deb installer from the Releases page?
this looks like an incompatibility issue introduced with electron-builder / electron / Linux Mint upgrades.

**Comment by AJSchiller** [comment]
@mbektas yes, I used the deb installer from the Releases page of this repo. Might installing it via Mint's own Software Manager solve the problem? (The installation instructions included here in the repo don't mention that as an option, I hadn't realised it was until I just checked now.)

**Comment by mbektas** [comment]
@AJSchiller can you retry with the latest version and provide an update? There has been several updates to the dependencies which might also resolve this issue.

**Comment by AJSchiller** [comment]
@mbektas thanks for the tag. I tried the update and one thing has changed - command `jupyter troubleshoot` now works in base environment as well (see last paragraph of original bug description). This makes no practical difference to my usage, does it provide any clues to you?

I did also notice a new problem - when I launch JupyterLab from the start menu or by opening a notebook from my system's file browser, and click Help -> About JupyterLab it shows version 3.5.2.

This has happened with previous updates as well, but I thought I was probably doing something wrong and anyway I haven't really needed JupyterLab lately, so I didn't really think about it too much. But I just did a thorough cleanup (deleted old .deb installers, uninstalled by right-clicking jlab in start menu and also followed uninstall instructions in the manual), rebooted, ran apt update + upgrade, rebooted again, then downloaded the .deb installer for the most recent version (4.0.5) and installed with `dpkg`, however all the problems described previously and also this problem (showing version 3.5.2) persist. Do you have any idea if this additional problem could be related to the original bug? Or is everyone seeing an older version number?

**Comment by mbektas** [comment]
closing since no response for long time. please create a new issue if needed.

**Comment by AJSchiller** [comment]
Sorry @mbektas , looks like I missed your last message.

The project I was using JupyterLab for has ended and I don't currently need it for anything else, so for the time being I give up. Thank you for your help.

For the record, I installed the latest version and tried your last suggestion, troubleshooting as I went along. Unfortunately, the original issue hasn't changed.
