### ISSUE TITLE
Right click menu/ scrolling output by default

### ISSUE THREAD

**Issue by Wickdhub** [jupyterlab/jupyterlab-desktop#554]
Hello!

I know there is there is a ticket dealing with this issue for Jupyterlab in browser, but is there a way in the Jupyterlab app desktop to add the copy/paste options in the right-click menu (If I can replace right click by shift+ right click for example)?

Also is there a way to set a maximum length before scrolling output activate? Or simply to enable scrolling output by default?

Thanks in advance

**Comment by JasonWeill** [comment]
Thank you for your contribution! It looks like there are already JupyterLab items for your requests, so I would recommend following along with them in the JupyterLab repo (or by submitting pull requests there).

The related JupyterLab items are https://github.com/jupyterlab/jupyterlab/issues/3224 and https://github.com/jupyterlab/jupyterlab/issues/13553.

JupyterLab also has multiple issues concerning scrolling, such as https://github.com/jupyterlab/jupyterlab/issues/9673 and https://github.com/jupyterlab/jupyterlab/issues/7567.
