### ISSUE TITLE
Couldn't load from customized python environment

### ISSUE THREAD

**Issue by yucsong** [jupyterlab/jupyterlab-desktop#558]
This is for the newest version of desktop : Version 3.5.1-1 (3.5.1-1) on Mac OS (M1 chip)

Failed to find a compatible Python environment at the configured path "/Users/xxx/opt/anaconda3/envs/wp_env/bin/python". Environment Python package requirements are: jupyterlab >=3.4.5.

But I have 3.5.3 installed on that environment,

jupyterlab                3.5.3              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.19.0             pyhd8ed1ab_0    conda-forge

I noticed that this issue also bothers others.

**Comment by JasonWeill** [comment]
I'm also using macOS on an M1 processor (on macOS 12.6.3 "Monterey"). I downloaded the JupyterLab Desktop installer for 3.5.1, ran the installer, and I see JupyterLab Desktop running successfully.

To help us diagnose this problem, can you please share:
* What version of macOS are you running?
* What exactly did you do before you saw that error? (Ran the installer, opened JupyterLab with a specific command, etc)
* Any other errors that you see in console or terminal.

**Comment by yucsong** [comment]
I found it really annoying, even if I provided all the information, people still ask.
