### ISSUE TITLE
Quitting every time I do Command-A (french keyboard, mac)

### ISSUE THREAD

**Issue by Yquetzal** [jupyterlab/jupyterlab-desktop#559]
For some reason, every time I do Command+A in a cell, the application quit. I cannot understand if it is a crash, or if the command wrongly call a shortcut to close the application. One suspicion could be a wrong trigger of command+q since I'm using a french keyboard where A is were Q is in a qwerty keyboard, but I never encountered this problem in any other app.

I tried to change the shortcuts in the settings (the interface is not working correctly for me, so I used directly json), but I could not solve the problem.

**Comment by JasonWeill** [comment]
We should check whether we're looking for the keypress's key code, as <kbd>A</kbd> on a French keyboard has the same position as <kbd>Q</kbd> has on a US or international English keyboard does. [KeyboardEvent.keyCode](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode) is deprecated. [KeyboardEvent.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) is supported, but MDN's documentation about it specifically mentions the <kbd>Q</kbd>/<kbd>A</kbd> problem in this issue.

**Comment by JasonWeill** [comment]
@SylvainCorlay I'm limited in how I can diagnose it because I don't have a physical French keyboard available. Could someone on your team look into this, if you have time, please?

**Comment by mbektas** [comment]
@Yquetzal can you try in the latest version. There were several Electron updates. There is also an option now to customize Cmd + W key to not close the window, in case that is related to your issue (Hamburger menu -> Settings -> Advanced).

**Comment by Yquetzal** [comment]
Indeed, I happily noticed that the problem solved itself some times ago :)

**Comment by mbektas** [comment]
happy to hear that!
