### ISSUE TITLE
PYTHONPATH is not known when launching JupyterLab app

### ISSUE THREAD

**Issue by oliviermarti** [jupyterlab/jupyterlab-desktop#573]
Hello,

When I start JupyterLab from the command line (`> jlab&` ), it take into account my personal `PYTHONPATH`, which is fine

When I start by double clicking the application icon, I didn't find a way in the App to define `PYTHONPATH`.

I can get around the problem by putting at the start of each notebook some lines like :
```
import sys, os
sys.path.append (os.path.join(os.environ['HOME'], "Python", "Library"))
import <my_module_in_new_path>
```
I don't find this very convenient. Could we have the possibility to define `PYTHONPATH` in the settings ?

Thanks,

Olivier

Info : 
- Jupyterlab-desktop 3.67.1-1
- Mac OS X 13.1 Ventura
- Python 3.9.7 from Conda install

**Comment by mbektas** [comment]
@oliviermarti when the app launches a server, it does use the environment variables in your system. If you would like to use a custom Python environment as default, you can set it in the [settings dialog](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#to-change-the-default-python-environment).

**Comment by oliviermarti** [comment]
I've put the path to my `conda` install in my settings, and it work fine.

But  ...

I also need to use some personnal library in `~/Python/Library`. I can put in the settings a path with several directories like `/Users/XXX/opt/anaconda3/envs/DEV/bin/python3.10:/Users/XXX/Python/Library`, but it don't seem to be effective. Only the first one is effective.
```
print (sys.path)
['/Users/XXX/Unix/Notebooks/Tests',
 '/Users/XXX/opt/anaconda3/envs/DEV/lib/python310.zip',
 '/Users/XXX/opt/anaconda3/envs/DEV/lib/python3.10',
 '/Users/XXX/opt/anaconda3/envs/DEV/lib/python3.10/lib-dynload',
 '',
 '/Users/XXX/opt/anaconda3/envs/DEV/lib/python3.10/site-packages',
 '/Users/XXX/opt/anaconda3/envs/DEV/lib/python3.10/site-packages/cdat_info-8.2.1-py3.9.egg']
```

I whish I can add `~/Python/Library` from the settings.

Olivier

**Comment by mbektas** [comment]
@oliviermarti we will look into this. as a workaround you can try creating a symlink in the environment's site-packages to your folder. `/Users/XXX/opt/anaconda3/envs/DEV/lib/python3.10/site-packages` (this path would differ based on the environment you are using)

**Comment by karlglazebrook** [comment]
This is the same as #393 - the issue seems to be that when the app is launched from the UI, when it runs the server it does not do so via a shell and environment variables are not picked up

**Comment by mbektas** [comment]
you can now set environment variables with the newest version 3.6.1-2. please install it and check the [user guide](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#server-environment-variables) for instructions.
