### ISSUE TITLE
UI mode setting is undocumented and can cause confusing errors

### ISSUE THREAD

**Issue by nathancarter** [jupyterlab/jupyterlab-desktop#574]
## Description

The settings page for the new JupyterLab Desktop app (version 3.6.1) gives you two choices for "JupyterLab UI mode," and they are called "Web app" and "Client app."  There are two problems:

 1. These are not documented anywhere I could find by searching the web, so I just decided to experiment with them.
 2. Switching to "Client app" and restarting caused the application to no longer detect my Python environment (which it had previously correctly detected) and thus gray out the "New notebook...," "New session...," and "Open..." buttons on the start page.

## Reproduce

 1. Open JupyterLab Desktop app.
 2. Open its Settings.
 3. Switch to Client app.
 4. Apply and restart.

## Expected behavior

I expected there to be documentation on these two options and that both would work.

## Context

- Operating System and version: Mac OS 12.4
- JupyterLab-Desktop version: 3.6.1
- Installer: .dmg

My suspicion from the tooltips on those two options is that one of them runs JupyterLab from within the Python environment you've selected and the other one just runs the Python kernel from that environment, but runs JupyterLab from within the Python environment that the desktop app can install for you.  And since I hadn't asked it to install a Python environment for me, it didn't have one.  If that's correct, it's particularly confusing that you get a message about your Python environment not being detected when the only setting you changed didn't have anything to do with your Python environment!

If this suspicion is correct, then perhaps the right thing to do is to gray out "Client app" when it doesn't actually apply, and place a message below it saying that you can't use it unless you install the bundled Python environment first.  (But I'm guessing here about what the problem might be.)

**Comment by mbektas** [comment]
@nathancarter thanks for reporting this. yes, the client app mode is more restrictive. I actually would like to sunset that mode in future releases.

**Comment by mbektas** [comment]
Client App mode is removed now.
