### ISSUE TITLE
Broken since new release (3.6.1-1) when using dtale

### ISSUE THREAD

**Issue by Schmetzler** [jupyterlab/jupyterlab-desktop#576]
## Description

The server gives an error when a connection to dtale is not possible and shuts down the server completely. In the earlier version it just filed a javascript error, but I was able to work with the files. Now if I open a notebook that had a dtale connection open in a previous run I just get a connection error and cannot work with my files.

![Screenshot_20230213_095731](https://user-images.githubusercontent.com/12082018/218414599-7afa04fc-f474-463e-a2b8-e55814af21f1.png)

## Reproduce

1. Start jlab
2. Install Dtale and numpy
3. Create a notebook and start a dtale connection: 
```
import numpy as np
import dtale
test = np.random.rand(16,200)
dtale.show(test)
```
4. Save and close
5. Start jlab again and open file

## Expected behavior

It should show an error message (as in previous builds), but should not completly dissallow further usage with the fullscreen error.

## Context

- Operating System and version: Manjaro-Linux Kernel 5.15.89-1
- JupyterLab-Desktop version: 3.6.1-1
- Installer: AUR jupyterlab-desktop-bin (uses the .deb file)

The important part from the log:
<pre>
[2023-02-13 09:57:11.101] [warn]  Unsatisfied version 6.0.1 of shared singleton module @jupyter-widgets/base (required ^2.0.0 || ^3.0.0 || ^4.0.0)
[2023-02-13 09:57:12.491] [verbose] Starting application in workspace: "default"
[2023-02-13 09:57:14.795] [error] (node:10843) electron: Failed to load URL: http://linuxtowerdom:40000/dtale/iframe/2 with error: ERR_CONNECTION_REFUSED
(Use `jlab --trace-warnings ...` to show where the warning was created)
[2023-02-13 09:57:14.832] [error] (node:10843) electron: Failed to load URL: http://linuxtowerdom:40001/dtale/iframe/6 with error: ERR_CONNECTION_REFUSED
</pre>

**Comment by mbektas** [comment]
@Schmetzler thanks for reporting this. dtale is creating an iframe and that is failing to load the next time the notebook is opened. app is not handling this case properly, we will fix it.

**Comment by simonkeys** [comment]
I have the same issue with the new release using snakeviz.
