### ISSUE TITLE
Changing theme to solarized is opening desktop app in dark mode instead

### ISSUE THREAD

**Issue by deepspacewrong** [jupyterlab/jupyterlab-desktop#579]
I have the solarized dark theme installed and in settings have selected that theme as the user default.

Whenever I open the app, it opens it in dark mode instead of the solarized dark theme. Then I have to go to themes and select the solarized dark again, but in settings it shows that my preference is solarized dark. 

![image](https://user-images.githubusercontent.com/109931901/218669845-97707ab5-fe52-4a8d-95f9-63ffa30bb8e8.png)

Could this have something to do with the app only having dark and light as its options [in the main title bar] until a user installs a new profile? So its only opening with dark or light as an option and then just ignoring the user selection until the user selects another theme from the settings menu bar once a notebook is opened.

Note: this happens whether I open jupyterlab-desktop to home or to a new notebook or to the previous session.

**Comment by mbektas** [comment]
@deepspacewrong in your case you need to turn off JupyterLab theme syncing from the Settings dialog (menu on top right of a window -> Settings). Then your theme selection in the Settings dialog will apply only to desktop app dialogs / titlebar etc.
<img width="812" alt="not sync theme" src="https://user-images.githubusercontent.com/40003442/219075864-8a1e4534-a084-4582-adba-cbec1071cc7e.png">
