### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by kpthedev** [jupyterlab/jupyterlab-desktop#580]
I've been working on a Flatpak package for easy distribution across different Linux distros. I noticed that this was mentioned before in #225, but it seems like it didn't get much traction. My manifest is for the latest `v3.6.1-1` release and in my testing it works great!

## Flathub

Packaging as a Flatpak allows for distribution on Flathub, the go-to Flatpak repository. This would allow easy distribution across several Linux distros (including those without .deb or .rpm support). I've personally been waiting for a Jupyter Flatpak to be available on Flathub for a while, and I figured this would be a great opportunity to fill the void. 

My repo is ready for submission for Flahub's approval and I'd be happy to maintain the Flathub repository if needed.

**Link to repo:** https://github.com/kpthedev/flathub/tree/org.jupyter.JupyterLab

**Comment by JasonWeill** [comment]
@mbektas FYI

@kpthedev Thank you for taking the initiative on this!

**Comment by kpthedev** [comment]
@mbektas Would you like to move forwards with this? I noticed that it was "approved" in the meeting, but I'm not quite sure what that means.

It's all ready to be submitted, and again I'd be happy to to maintain the repo.

**Comment by mbektas** [comment]
hi @kpthedev github releases page is our main distribution channel but you can go ahead with your Flatpak distribution integration. Similarly someone volunteered to integrate with winget. Please make sure you update it regularly. Your configuration uses 3.6.1-1 but 3.6.1-2 is the latest now.

**Comment by kpthedev** [comment]
Sounds good!
