### ISSUE TITLE
Define GatewayClient when starting JLD

### ISSUE THREAD

**Issue by gogasca** [jupyterlab/jupyterlab-desktop#583]
## Description

How can I define?
```
-GatewayClient.url
-GatewayClient.headers
```

When launching JL desktop.

## Reproduce

N/A

## Expected behavior

N/A

## Context

I want to connect external kernels using: https://github.com/GoogleCloudPlatform/notebook-kernels-mixer

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab-Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by mbektas** [comment]
@gogasca customizing server launch arguments is not supported yet but I plan to add it soon.
