### ISSUE TITLE
Pause automatic updates

### ISSUE THREAD

**Issue by simonkeys** [jupyterlab/jupyterlab-desktop#585]
## Description

I can't use version 3.6.1-1 because of #576.  If I install an earlier version it upgrades me back to 3.6.1-1 on the next restart.

## Reproduce

I installed version 3.5.1-1 and immediately got a dialog box offering to restart to upgrade. I clicked "Later" (the dialog then reappeared and I had to click later again to make it go away). Everything was fine until I restarted, at which point the app upgraded and I had to reinstall 3.5.1-1 again.

## Expected behavior

An option in the dialog to ignore the update, or a setting in preferences to not perform automatic updates.

## Context

- Operating System and version: macOS 12.6.3
- JupyterLab-Desktop version: Version 3.5.1-1 
- Installer: .dmg

**Comment by mbektas** [comment]
@simonkeys you should have the settings file for 3.5.1-1 at `~/Library/jupyterlab-desktop/jupyterlab-desktop-data`. After installing that version, and before launching it, open this file and set these two values to false.
```
{
  "jupyterlab-desktop": {
    "JupyterLabDesktop":{
      "checkForUpdatesAutomatically":false,
      "installUpdatesAutomatically":false
```

**Comment by simonkeys** [comment]
@mbektas  Great, thanks for the info!
