### ISSUE TITLE
File save hooks don't seem to work in JLDA

### ISSUE THREAD

**Issue by miwojc** [jupyterlab/jupyterlab-desktop#589]
It seems Jupyter Desktop App doesn't use File Save hooks, which work for Jupyter Lab.
https://jupyter-server.readthedocs.io/en/latest/developers/savehooks.html

JLDA version: 3.6.1-1 (hooks don't work)

JL version: Version 3.4.8 (hooks work)

Update. When connected to existing JL server then they work in JLDA. So it must be different location expected for the hooks for the JLDA. Currently my hooks are in `~/.jupyter`. Which directory this should be for the JLDA?

**Comment by JasonWeill** [comment]
PR #588 is merged, so it seems like this bug is now fixed. Thanks!
