### ISSUE TITLE
Font resizing fails

### ISSUE THREAD

**Issue by Saunak626** [jupyterlab/jupyterlab-desktop#598]
When using a language other than English, the theme's font size will not work

**Comment by JasonWeill** [comment]
@Saunak626 Thanks for opening this issue! Which non-English languages have you tried using? Can you attach a screen shot of how these languages look?

**Comment by krassowski** [comment]
This appears related to https://github.com/jupyterlab/jupyterlab/issues/13598 especially https://github.com/jupyterlab/jupyterlab/issues/13598#issuecomment-1443739694 and that one has already a PR open.
