### ISSUE TITLE
Jupyterlab Desktop Installer fail, cannot close Jupyterlab

### ISSUE THREAD

**Issue by cannocraft** [jupyterlab/jupyterlab-desktop#602]
## Description

I had previously installed Jupyterlab Desktop but had to uninstall it and re-install it. 
When I went to reinstall it now won't complete the installation.
I get the following errors.
"Jupterlab cannot be closed"
![image](https://user-images.githubusercontent.com/126864210/222678478-17141ea2-6d3f-4343-89e2-5668352ab6db.png)
retry repeats that message, ignoring proceeds to the following messages, each one after pressing ignore again.
"Error opening file for writing" this directory doesn't exist yet as it's not installed.
![image](https://user-images.githubusercontent.com/126864210/222678638-dfc5c368-217a-455d-972a-c61400af3fe0.png)
same this directory isn't created yet.
![image](https://user-images.githubusercontent.com/126864210/222678655-aadd2799-fb60-4ad9-9c03-991648a64832.png)

![image](https://user-images.githubusercontent.com/126864210/222678672-1ccfe9cd-3107-4040-a7d4-b06ca141a426.png)

I didn't initially know about the uninstall procedure to remove jupterlab desktop python environment [as described here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#uninstalling-jupyterlab-desktop)

Any advice would be greatly appreciated.

**Comment by mbektas** [comment]
You can try these
- Make sure no JupyterLab Desktop or server instance is running (rebooting should terminate them if any)
- If you want to uninstall any existing JupyterLab Desktop and/or Server installation, go to `Add / Remove Programs` remove all of the related installations.
- If there are any dangling installations that cannot be removed from `Add / Remove Programs` then remove those dangling ones by following `with care`: https://support.microsoft.com/en-us/topic/removing-invalid-entries-in-the-add-remove-programs-tool-0dae27c1-0b06-2559-311b-635cd532a6d5
- The instructions in the link above may need to be followed also for: `HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall`

**Comment by JasonWeill** [comment]
@cannocraft Can you please add a comment about the additional steps (as @mbektas described) you followed, and whether they fixed the problem? Thanks!

**Comment by cannocraft** [comment]
hi sorry for the delay in replying.
I've tried all those steps but I still get the same error when installing.
in response to @mbektas 4 points.
1. there's nothing running that i can see, in apps or processes. i've restarted several times to no benefit.
2. I have removed all installations of jupyterlab desktop and the python server instance. still see the same error when trying to install.
3. and 4. I've checked the registry and can't see any entries for jupyterlab desktop in either the `HKEY_CURRENT_USER` or `HKEY_LOCAL_MACHINE` key trees.

Other troubleshooting:
I have searched the C: drive for the word jupyter and found a working executable in `C:\Users\_my_username_\AppData\Local\Temp\nsyC78F.tmp\7z-out` this seems to have a temp extraction during install, from there i can find an installer for the JupyterLabDesktopAppServer which installs successfully. I still can't install the main program from the downloaded installer but this seems to be a workaround of sorts.

The folder structure is here
![image](https://user-images.githubusercontent.com/126864210/224286823-7317ea79-3df1-4afa-bd98-34e21feed305.png)
when i run jupyterlab.exe the program runs fine it seems

Any ideas on this? should i just back up this folder and then delete it?

**Comment by mbektas** [comment]
Have you tried installing to the default installation directory `C:\JupyterLab`? Also running the installer as administrator?

**Comment by JasonWeill** [comment]
@cannocraft Can you please respond to @mbektas 's comment earlier?

**Comment by cannocraft** [comment]
Hi @mbektas and @JasonWeill, it looks like my previous comment didn't post correctly. 
I tried installing to the default location with admin rights but it didn't work.
I then moved the temp folder to another location and when I went to reinstall with the installer it worked fine. I used admin rights that time too.
For me this issue is closed now.
Thanks for the help
