### ISSUE TITLE
Windows 10: Cannot move window after resizing window

### ISSUE THREAD

**Issue by connorferster** [jupyterlab/jupyterlab-desktop#607]
## Description

In Windows 10, there seems to be a bug with the GUI window where, upon first load, I can move the window. However, if I resize the window, then I can no longer move it by clicking-and-dragging the top of the window. I can "move" the window by using the resize handles to move it one edge at a time but it is a weird behaviour I noticed with both 3.6.1 releases.

## Reproduce

1. On Windows 10, open JupyterLab v 3.6.1-x
2. Resize the window
3. Attempt to move the window by clicking-and-dragging the top of the window (unable to do so)

## Expected behavior

The window moves with the usual gestures.

## Context

- Operating System and version: Windows 10
- JupyterLab-Desktop version: 3.6.1-x
- Installer: .exe

**Comment by JasonWeill** [comment]
This may occur on Linux as well, per @krassowski

**Comment by mbektas** [comment]
@connorferster can you test again with the latest (3.6.2-1)? There were some electron updates to drag regions and the issue might be resolved now.
