### ISSUE TITLE
z label is not displyed in matplotlib 3d plot

### ISSUE THREAD

**Issue by tmacchant3** [jupyterlab/jupyterlab-desktop#608]
## Description

z label is not displyed in matplotlib 3d plot
## Reproduce

Excecute the below script on JupyterLab on JupyterLab
`

import matplotlib.pyplot as plt

fig = plt.figure()

fig, ax = plt.subplots(subplot_kw = dict(projection='3d'))

ax.set_ylabel('y')

ax.set_zlabel('z')

plt.show()

`

y label is displayed but z is no displayed.
On jupyterLab on Anaconda3.2022.10, the script works as expected.
I found a workaround.
https://stackoverflow.com/questions/75275130/z-label-does-not-show-up-in-3d-matplotlib-scatter-plot

## Expected behavior

z label is displaed.
## Context

- Operating System and version: Windows 10 
- JupyterLab-Desktop version: 3.6.1-2
- Installer:  .exe

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab-Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by mbektas** [comment]
@tmacchant3 this is not really a desktop app issue. it is reproduceable in browser version as well. you may want to report the issue in matplotlib project.

**Comment by Tatsuro-MATSUOKA** [comment]
> you may want to report the issue in matplotlib project.
However, if I execute the code as .py in python, z label represent normally.
Is this really  matplotlib issue?
I think this issue jupyterlab issue. (Anaconda's jupterlab version is older than those used the Desktop app.)

**Comment by mbektas** [comment]
@Tatsuro-MATSUOKA if .py version works, then that means issue is in the widget implementation of matplotlib. please raise an issue in the the matplotlib project.

**Comment by mbektas** [comment]
not a JupyterLab Desktop specific issue
