### ISSUE TITLE
Winget packages are out of date

### ISSUE THREAD

**Issue by vasiljevic** [jupyterlab/jupyterlab-desktop#609]
## Description

Latest version in the winget repository is 3.5.1-1, but the latest publised version is 3.6.1-2 (on March 10, 2023)

Since the version 3.6.1-1 is published on Feb 6, winget repo for jupyterlab is more than one month out of date.

Also, after installation using winget, jlab reports that new version exists and ask me to downoad it, not to upgrade using winget. 

## Reproduce

1. In the Windows command prompt execute `winget search jupyterlab --versions`
2. See the latest version that is not up to date

## Expected behavior

It is expected not to have significant delay of new winget pachages after a new version of jupyterlab-desktop is published.

## Context

- Operating System and version: Windows 11
- JupyterLab-Desktop version: 3.6.1-2
- Installer: winget

**Comment by JasonWeill** [comment]
winget is a Microsoft-administered package manager. JupyterLab Desktop's manifest has been committed by @brl0 and modified by @mdanish-kh. I'm not sure whether they would be the right people to submit newer versions to winget.

**Comment by mdanish-kh** [comment]
@JasonWeill WinGet packages are entirely community maintained. There is some work to be done for https://github.com/microsoft/winget-pkgs/issues/100, which would let publishers take control of their package submissions. Right now, the expectation is that publishers integrate the submission process as part of their releases or the community updates the manifests themselves.

If the maintainers want to automate the submission process and keep the package up-to-date, they can integrate [winget-create](https://github.com/microsoft/winget-create) (maintained by the WinGet team) as part of their release workflow. They can follow the steps [outlined in the documentation](https://github.com/microsoft/winget-create#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline) and also take a look at an example of how PowerShell maintainers use winget-create to [automate the submissions](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml).

Apart from winget-create, there is also a popular community-developed GitHub Action [winget-releaser](https://github.com/vedantmgoyal2009/winget-releaser/) maintained by @vedantmgoyal2009 for the same task.

**Comment by brl0** [comment]
I submitted an update to the winget package.  After running into some issues with WingetCreate, I tried KOMAC, the tool utilized by `winget-releaser` GitHub Action mentioned above, and it worked well.  I have submitted #647 to add a workflow to make use of that action.

**Comment by vedantmgoyal2009** [comment]
The PR by @brl0 looks good. @JasonWeill would you like to merge?

**Comment by JasonWeill** [comment]
@vedantmgoyal2009 I linked #647 to this issue. I have not yet added the GitHub token or forked the package as you specified, and I'm about to leave town for over a week (due primarily to JupyterCon) so I will not be available to do this until after I'm back.

**Comment by brl0** [comment]
I submitted another update to the winget package.  Komac makes it really easy to do, but it would be nice to have it included in GitHub Actions so that it is automatically updated.  Let me know if there is anything I can do to assist with that.

**Comment by JasonWeill** [comment]
@vedantmgoyal2009 Thanks for the follow up! I'd prefer if @mbektas take a look at PR #647 — he was also at JupyterCon.

**Comment by halr9000** [comment]
As a new user, as someone who uses winget FIRST to install everything, I was disappointed to find that the repo is out of date. Anyone working to resolve? The github actions path mentioned above sounds great.
