### ISSUE TITLE
macOS app icon doesn't follow human interface guidelines

### ISSUE THREAD

**Issue by michaelpginn** [jupyterlab/jupyterlab-desktop#613]
## Description

The macOS icon does not follow the macOS [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons#macos/), particularly 

> In macOS, app icons share a common set of visual attributes, including a rounded-rectangle shape, front-facing perspective, level position, and uniform drop shadow.

The icon should be updated to maintain consistency with the OS.

<img width="128" alt="Circle" src="https://user-images.githubusercontent.com/7244206/224844987-30e9b7c5-abb1-416d-9e3d-63dc8ce9d532.png">

## Reproduce

N/A

## Expected behavior

Some sort of rectangular icon. Below is an example.

<img width="128" alt="square" src="https://user-images.githubusercontent.com/7244206/224845183-efe82739-e10e-40ed-aa53-d2df250ba0cc.png">

## Context

N/A

**Comment by mbektas** [comment]
@michaelpginn thanks for notifying us about the icon issue. do you have an SVG version of the icon you shared? would you like to contribute it to this project?

**Comment by michaelpginn** [comment]
I found the png icon at https://macosicons.com/. I believe it was created by @s-valent, maybe they could provide the original file?

**Comment by s-valent** [comment]
> maybe they could provide the original file?

Sadly I don't have an svg version, this one was made in Pixelmator Pro. SVGs and shadows are not a great combination, so I'm not sure if convertiong it to svg will be any good.

[JupyterLab.pxd.zip](https://github.com/jupyterlab/jupyterlab-desktop/files/11075134/JupyterLab.pxd.zip)
[JupyterLab.psd.zip](https://github.com/jupyterlab/jupyterlab-desktop/files/11075142/JupyterLab.psd.zip) (this one is converted to psd, not sure how well though)

**Comment by mbektas** [comment]
Thanks @s-valent I used the .icns file and it worked well. below is how it looks.

<img width="329" alt="lab-icon-squared" src="https://user-images.githubusercontent.com/40003442/230528196-cd95eebf-1b0a-4e27-bdb1-d4b47bb89ec5.png">

<img width="54" alt="lab-icon-squared2" src="https://user-images.githubusercontent.com/40003442/230528203-bd3f34bd-9458-4492-965e-b766715607fb.png">

@JasonWeill are there any concerns to use this icon? Is there a UX person to get involved?

**Comment by mbektas** [comment]
another option could be something like this one. this would be more ideal I think since it preserves the original icon.

<img width="242" alt="jlab-icon-squared3" src="https://user-images.githubusercontent.com/40003442/230685167-0ca6e3ba-5d25-4969-b4cb-f782d5ef07d5.png">

**Comment by JasonWeill** [comment]
I've noticed that the "rounded-corner rectangle with otherwise unmodified icon inside" convention is used by a few different third-party apps on my MacBook, including Microsoft Office apps, Slack, Quip, Visual Studio Code, and Chrome. I like the most recent icon concept, since it preserves the circular JupyterLab logo that is more recognizable.

**Comment by mbektas** [comment]
App icon is now updated to use rounded rectangle and standard Jupyter icon.
