### ISSUE TITLE
Blank screen on open

### ISSUE THREAD

**Issue by JonahDG** [jupyterlab/jupyterlab-desktop#614]
## Description

Downloaded JupyterLab Desktop for first time and whenever I open it, it opens to blank screen.
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/60613947/224906669-582ec2a4-8f1c-40db-8022-8af4fecdc9c3.png">

I am able to return to normal main menu by opening a new window by clicking on the 3 lines in the top right and opening a new window, however, it doesn't automatically connect to local host (or any other server for that matter) unless I first open it in terminal or via anaconda navigator.

## Reproduce

Literally happens every time I open the desktop app.

## Expected behavior

It should open up to the welcome screen and allow me to connect to localhost without opening it via terminal.

## Context

- Operating System and version: MacOS Ventura Version: 13.2.1
- JupyterLab-Desktop version: Version 3.6.1-2
- Installer: .dmg

Honestly I think this is probably a super simple fix, but I've tried many things and I'm very confused.

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab-Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by mbektas** [comment]
@JonahDG what is your CPU architecture? is it Apple silicon? Also, can you try these:
1. can you check the logs in `~/Logs/jupyterlab-desktop/main.log` and share
2. if logs don't have any valuable information, can you retry after setting log level to 'Debug'. Menu -> Settings -> Advanced -> Log level: Debug
3. Go to Menu -> Settings -> Server and check if there are any prompts / warnings about bundled Python environment? you can share a screenshot here. Try installing the bundled Python environment if an option is provided to you.

**Comment by JonahDG** [comment]
I am on an Intel based Mac Book Pro.

The logs are empty both before and after the 'Debug' change.

That said, I did some work in JupyterLab thru anaconda and now everything seems to be working fine and I can't seem to replicate my issue, so I think I am actually okay, but let me know if you want anything from me if you think this needs further investigation.
