### ISSUE TITLE
Add a button to refresh current session

### ISSUE THREAD

**Issue by palpen** [jupyterlab/jupyterlab-desktop#615]
Each day I need to login and refresh my credentials on our servers before I can begin work on my notebooks. Once my credentials are refreshed, I need to close the current JupyterLab session and then click on the link to my server under "Recent Sessions" in order to refresh the session. It would be great to be able to do this in one step, without having to close the current session. Perhaps a button along the top right corner next to the icons in the screenshot.

![image](https://user-images.githubusercontent.com/9051141/225059775-8e5a01e7-3f12-4874-8b5a-cafab47359ab.png)

**Comment by mbektas** [comment]
@palpen have you tried unchecking `Persist session data` in the Connect dialog where you enter your URL?

There is also Clear `Browser session cache & data` in `Hamburger menu` -> `Settings` -> `Privacy` section.

Do these work for you?

**Comment by mbektas** [comment]
no response for a long time. please reopen if needed.
