### ISSUE TITLE
Jupyterlab Desktop Application doesn't launch

### ISSUE THREAD

**Issue by RJ15293** [jupyterlab/jupyterlab-desktop#617]
When trying to open Jupyterlab desktop app. It doesn't open at all. It crashes right away. I checked event logs and nothing is there. It acts like it does nothing when trying to open. I have reinstalled multiple times and tried conda navigator. I have tried launching from the command line as well and nothing happens. Please advise. This started when I got the latest update and others I work with are experiencing the same issue.

**Comment by hellojinwoo** [comment]
I am having the same issue. My windows version is windows 11 and the JupyterLab desktop version that I used was v3.6.1-3

**Comment by mbektas** [comment]
@RJ15293 did you have the issue on Windows too? can you provide more details? version, OS etc.

**Comment by RJ15293** [comment]
This is on Windows 10. I am actually a tech for a company and this happened to someone I support. The web version works fine. This only happened when we got the update. I checked the logs and didn't see anything there. When you click to open the application, it does nothing. Like it's not even there. Not sure what else we can.

**Comment by JasonWeill** [comment]
Closing because we don't have the information that we need to diagnose and fix this issue.
