### ISSUE TITLE
Completely removing Jupyterlab Desktop according to instructions does not remove everything

### ISSUE THREAD

**Issue by jzuhone** [jupyterlab/jupyterlab-desktop#620]
## Description

I have several times completely removed JupyterLab Desktop according to the [uninstall instructions on macOS](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#macos). However, when I re-install it, I discover that it remembers one of the JupyterLab servers I told it about previously. 

## Reproduce
1. Previously installed JupyterLab has custom server information I no longer want
2. Uninstall JupyterLab completely
3. Reinstall from fresh installer
4. Open jupyterlab, find that custom server is still found

## Expected behavior

The custom server information should be gone.

## Context

- Operating System and version: macOS Ventura 13.1 Apple Silicon
- JupyterLab-Desktop version: 3.6.1-3
- Installer dmg

Perhaps a separate issue, but seems to be related, this particular Python environment that I want removed is an x86_64 mambaforge stack that was created by an arm64 base mambaforge environment.

**Comment by mbektas** [comment]
@jzuhone this is by the design. App keeps user settings and app settings between installation / upgrades. You can clear some of the settings from Menu -> Settings -> Privacy. To perform a deeper clean you can delete [these files](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#configuration-and-data-files) additionally and clean logs from `~/Library/Logs/jupyterlab-desktop`.

**Comment by jzuhone** [comment]
@mbektas I've done all of the things you recommended--nothing has worked.

**Comment by mbektas** [comment]
Your local Python environments are discovered automatically on launch. If you added one that was not discovered, then it should be deleted when you clear `User set Python environments` from  `Menu -> Settings -> Privacy` or when you delete `app-data.json` as instructed in the link. Deleting the files manually should be done when the app is closed otherwise they will be recreated by the app on close.
