### ISSUE TITLE
Changing environment 

### ISSUE THREAD

**Issue by msh855** [jupyterlab/jupyterlab-desktop#621]
I am using JupyterLab Desktop in Mac

I am trying to change the environment but the Lab doesn't work: 
![image](https://user-images.githubusercontent.com/114295360/226116013-955f5a08-0c6c-471e-b89d-6cf8d67193a9.png)

It only works with the Bundled environment

I also see differences in the terminal of my Mac and the Terminal in JupyterLab:

![image](https://user-images.githubusercontent.com/114295360/226116162-4ab413f5-ad3a-4969-b7b9-7801a1a696c5.png)

**Comment by mbektas** [comment]
@msh855 do you have `jupyterlab` Python package installed in your custom environment (`pip install jupyterlab`)? Can you check share the logs in `~/Library/Logs/jupyterlab-desktop/main.log`.

The commands you ran in the different terminals are different. Can you retry with the same command?

**Comment by msh855** [comment]
Hi, there was no `jupyterlab-desktop` folder in this path (I am using Mac). In my custom env `jupyterlab` is installed. Whenever I tried to use my custom env the Lab fails to create new sessions, even if I am trying to switch to the default `bundled` env. Here is the message I get:

![image](https://user-images.githubusercontent.com/114295360/227721128-511d0569-18f8-4906-aa1e-e686a2820ef7.png)

**Comment by JasonWeill** [comment]
@msh855 As @mbektas requested, can you please check and share the logs in `~/Library/Logs/jupyterlab-desktop/main.log` ? Thanks!

**Comment by msh855** [comment]
@JasonWeill thanks for the response. As mentioned in my previous message, there is no such folder in the location you suggest, and it was impossible to find any 'main.log' file on my computer.

**Comment by mbektas** [comment]
can you create the folder manually? `~/Library/Logs/jupyterlab-desktop`. could you be having write permission issues?

can you also check if you have this directory created: `~/Library/Application Support/jupyterlab-desktop`

**Comment by JasonWeill** [comment]
@msh855 Any update in response to @mbektas 's questions above?

**Comment by msh855** [comment]
Sorry, I had to gave up completely  and removed jupyter-desktop. I use it via anaconda which looks more stable.

**Comment by JasonWeill** [comment]
@msh855 I understand — if you find any other issues, please open new ones here. Thanks!
