### ISSUE TITLE
Broken installation link for 'macOS Intel Installer' in README file redirects to 404 Error

### ISSUE THREAD

**Issue by shylaatchison** [jupyterlab/jupyterlab-desktop#625]
## Description

Within the README.md file and under the "Installation" section, the link titled "macOS Intel Installer" for installing JupyterLab desktop app for MacOS Intel (same with the "macOS Apple silicon Installer" link) leads to 404 Error.

<img width="485" alt="Screenshot 2023-03-22 at 2 13 40 PM" src="https://user-images.githubusercontent.com/53931881/227041245-f7b98161-cdad-479c-886f-9c127a1adfff.png">

<img width="870" alt="Screenshot 2023-03-22 at 2 13 58 PM" src="https://user-images.githubusercontent.com/53931881/227041292-ba0b198e-8eb4-45de-b162-c913e64b00a1.png">

## Reproduce

1. Go to 'https://github.com/jupyterlab/jupyterlab-desktop'
2. Click on 'Code'
3. Click on 'README.md' or scroll down past the files to where the 'README.md' file is automatically displayed on the page.
4. Scroll down to the section titled 'Installation'
5. See error(s) in the third bullet point, the two broken links titled 'macOS Intel Installer' and 'macOS Apple silicon Installer'

I clicked on the links and then was redirected to Error 404 pages.

## Expected behavior

I expected the macOS Intel Installer to download or at least produce a prompt for starting installation via an installation helper?

## Context

Sorry if this is a bad bug report. I've literally never done one before and I'm still getting the hang of GitHub. I'm not doing all this other stuff listed below. The error isn't that complicated to require any of it. The README.md file literally just has broken links in it.

- Operating System and version: 
- JupyterLab-Desktop version: 
- Installer: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab-Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by mbektas** [comment]
@shylaatchison thanks for reporting this issue. we had to rollback the latest release due to Windows installer issues reported but forgot to update the installer links.

**Comment by mbektas** [comment]
pushed the fix now. thanks!

**Comment by shylaatchison** [comment]
thank you!!
