### ISSUE TITLE
Can I change the temp directory path for jlab?

### ISSUE THREAD

**Issue by handabaldeep** [jupyterlab/jupyterlab-desktop#627]
In our company we are not allowed to write/modify files under `%localappdata%\temp` on Windows. When I try to launch a new notebook I am seeing 

`"Failed to create session" with "Error: Jupyter Server process terminated before the initialization completed".`

At the same time I am seeing access denied errors from our security console. 

Is it possible to override the temporary files location for JupyterLab Desktop?

**Comment by mbektas** [comment]
@handabaldeep you can try setting `TMP` and `TEMP` environment variables to the directory (needs to exist already) you want to use. You can do that in `Menu -> Settings -> Server -> Additional JupyterLab server environment variables` . Example:
```
TMP="C:\tmp-test"
TEMP="C:\tmp-test"
```

**Comment by handabaldeep** [comment]
@mbektas, that didn't help. 

I think it is Desktop application specific and not related to the server as I am able to launch the server from cmd using the command in the preview dialog box. Not sure if it helps but the full path it is trying to run a `launch.bat` file from is `%localappdata%\temp\jlab_dekstopxxxxx` which results in an access denied on my side. If I can point the app to write and run this file from some other user location then it would work.

**Comment by mbektas** [comment]
You can create a custom shortcut for JupyterLab Desktop app and set the environment variables TMP & TEMP that way. [This page](https://netlicensing.io/blog/2012/06/15/set-environment-variables-in-windows-shortcut/) explains how.

**Comment by handabaldeep** [comment]
Thanks @mbektas. Tried your suggestion but the application gets stuck when I create a new session or a new notebook.

The command I am running is:
`C:\Windows\System32\cmd.exe /c "SET TMP=C:\path\to\new\temp && SET TEMP=C:\path\to\new\temp && START /D C:\JupyterLab JupyterLab.exe"`

**Comment by mbektas** [comment]
You can check the logs if there is any relevant information is available. You may want to set log level to debug to get more details. `Hamburger menu on top right` -> `Settings` -> `Advanced`.

Logs are in `%appdata%\jupyterlab-desktop\logs\main.log`
