### ISSUE TITLE
Can't close code hints

### ISSUE THREAD

**Issue by Saunak626** [jupyterlab/jupyterlab-desktop#628]
can't open JSON Setting Editor, don't have User preferences. How do I turn off code hints
![image](https://user-images.githubusercontent.com/34276206/227522896-7b4d5800-de02-4791-bcc0-f69c347d1f74.png)

**Comment by JasonWeill** [comment]
The JSON settings editor should be present if you go to Settings > Advanced Settings Editor and click "JSON Settings Editor" in the upper-right corner:
![image](https://user-images.githubusercontent.com/93281816/229863586-98addc87-f601-4988-aa8d-2a36f9cd7a54.png)

Are you able to change the settings this way?

**Comment by krassowski** [comment]
This is coming from https://github.com/jupyter-lsp/jupyterlab-lsp extension btw, you can uninstall or disable the extension or disable this feature alone:

![Screenshot from 2023-04-04 18-12-20](https://user-images.githubusercontent.com/5832902/229867309-733090ac-db24-4e6e-9726-c5269cd0ee7e.png)

**Comment by Saunak626** [comment]
> The JSON settings editor should be present if you go to Settings > Advanced Settings Editor and click "JSON Settings Editor" in the upper-right corner: ![image](https://user-images.githubusercontent.com/93281816/229863586-98addc87-f601-4988-aa8d-2a36f9cd7a54.png)
> 
> Are you able to change the settings this way?

I can't open the JSON setting editor.

**Comment by Saunak626** [comment]
> This is coming from https://github.com/jupyter-lsp/jupyterlab-lsp extension btw, you can uninstall or disable the extension or disable this feature alone:
> 
> ![Screenshot from 2023-04-04 18-12-20](https://user-images.githubusercontent.com/5832902/229867309-733090ac-db24-4e6e-9726-c5269cd0ee7e.png)

disable the feature can close code hints
