### ISSUE TITLE
Mac - Command+W 

### ISSUE THREAD

**Issue by AnilRh** [jupyterlab/jupyterlab-desktop#630]
In JupyterLap Command+W on Mac closes the main window (so the app disappears). This might make sense if the app used multiple windows, but since it's a tabbed app I don't think this is normal mac behaviour.

In most tabbed apps that know (Chrome and Safari being two big ones) Command+W closes the current tab, not the main window. Could the shortcut on Mac be changed to do the same?  If someone wants to close the Main window they may as well Command+Q.

From Apple Support - here's what it says about Command+W:
Command-W: Close the front window. To close all windows of the app, press Option-Command-W.
https://support.apple.com/en-us/HT201236

**Comment by mbektas** [comment]
You can customize Cmd + W behavior as shown [here](https://github.com/jupyterlab/jupyterlab-desktop/pull/606#issue-1614733230).

**Comment by krassowski** [comment]
I would say the same for Linux (but for ctrl + w)

**Comment by mbektas** [comment]
fixed already
