### ISSUE TITLE
Can't save the theme setting 

### ISSUE THREAD

**Issue by Saunak626** [jupyterlab/jupyterlab-desktop#633]
I change the theme and open show line numbers. But when I restart the client, those settings are changed back to their default values
. And when I change those settings, open another client also keep the default values. It seems that these changes are temporary. Moreover, the Font size can't zoom like browser.

**Comment by mbektas** [comment]
@Saunak626 please check [this section](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#theming) in user guide. You need to turn off `Sync JupyterLab theme`.

I wasn't able to reproduce the issue with persisting line number toggling.
