### ISSUE TITLE
Default working directory is not saved

### ISSUE THREAD

**Issue by gaksaray** [jupyterlab/jupyterlab-desktop#634]
## Description

Default working directory is set to a different folder than user home. But launching new session reverts to user home. Launching Jupyterlab from terminal by `jlab --working-dir [directory]` does launch a session in `directory` but launching it from the app reverts is back to user home.

## Reproduce

1. Launch Jupyterlab Desktop
2. Settings → Server → Default working directory: `/Users/[username]/Library/CloudStorage/Dropbox`
3. Apply & restart
4. New session → Starts in home folder

## Expected behavior

To be able to set the default working directory and have Jupyterlab launch in that folder every time

**Comment by mbektas** [comment]
@gaksaray thanks for reporting this. I am able to reproduce the issue. It must have been broken during a refactoring. We will release a patch with next version.
