### ISSUE TITLE
[macOS] cannot use `/usr/bin/python3` to start server

### ISSUE THREAD

**Issue by yw662** [jupyterlab/jupyterlab-desktop#637]
## Description

The desktop app failed to start the server when using macOS stock environment.

## Reproduce

1. Go to 'settings -> server -> custom python environment'
2. set it to `/usr/bin/python3`
3. try start the server
4. See `Error: Jupyter server process terminated before the initialization completed`.

I have already installed jupyterlab throw `python3 -m pip install` and this command runs with no error:
```
python3 -m jupyterlab --no-browser --expose-app-in-browser --ServerApp.port=1234 --ServerApp.password="" --ServerApp.token="12345678" --LabApp.quit_button=False --JupyterApp.config_file_name="" --ContentsManager.allow_hidden=True
```

## Expected behavior

The server should run.

## Context

- Operating System and version: macOS 13.3.1 arm64
- JupyterLab-Desktop version: 3.6.2-1
- Installer: .dmg

**Comment by mbektas** [comment]
Can you check if there are any helpful [logs](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#Logs)?

**Comment by mbektas** [comment]
closing since no reply for a long time. please create a new issue if needed.
