### ISSUE TITLE
cannot connect to ipython kernels

### ISSUE THREAD

**Issue by bill-tatsis** [jupyterlab/jupyterlab-desktop#645]
Hello, 
I am using jupyterlab desktop 3.6.3-1 and it fails to connect to some of the ipython kernels I have installed.
jupyter-lab connects fine to these kernels. How could I debug this issue?

Thanks

**Comment by mbektas** [comment]
@bill-tatsis have you selected your custom Python environment as described [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#to-set-project-specific-python-environment)?

**Comment by mbektas** [comment]
@bill-tatsis can you provide more details. how did you install additional kernels? which kernels are they? are there any error [logs](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#Logs)?

**Comment by mbektas** [comment]
closing since no response for long
