### ISSUE TITLE
jlab CLI installation on Mac OS fails

### ISSUE THREAD

**Issue by abulte** [jupyterlab/jupyterlab-desktop#655]
## Description

`jlab` CLI is not installed and manual installation is difficult.

## Reproduce

Install and launch JupyterLab Desktop.

## Expected behavior

`jlab` command should be in the PATH after first launch.

The docs should be able to troubleshoot the problem completely.

## Manual fix and troubles

Following [troubleshooting instructions](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#macos-write-permission-issues) won't help since the following command will fail with permission denied (including with `sudo`):

```
chmod 755 /Applications/JupyterLab.app/Contents/Resources/app/jlab
```

In order for this to work, you need to allow your Terminal application to manage apps in Mac OS security settings. After it's done and the terminal is rebooted, you can make the CLI executable.

Still, JupyterLab Desktop won't create the symlink in the PATH in order for you to have `jlab` available. You need to create it manually.

```
sudo ln -s /Applications/JupyterLab.app/Contents/Resources/app/jlab /usr/local/bin/jlab
```

## Context

- Operating System and version: Mac OSX 13.3.1(a) Ventura
- JupyterLab-Desktop version: 3.6.3-2
- Installer: .dmg
- Architecture : Silicon M1

**Comment by fjhickernell** [comment]
Please help.  
![Screenshot 2023-05-16 at 5 09 45 PM](https://github.com/jupyterlab/jupyterlab-desktop/assets/817530/6f16de2a-f1c9-470d-b662-20a520a436cf)
I tried following the instructions and I still get
(base) fredhickernell@Freds-MacBook-Pro bin % ln -s /Applications/JupyterLab.app/Contents/Resources/app/jlab /usr/local/bin/jlab
ln: /usr/local/bin/jlab: Permission denied

What am I missing?

**Comment by fjhickernell** [comment]
Okay, so I typed sudo and then the link command and all worked.

Thanks to the developers for this nice app.

**Comment by abulte** [comment]
@fjhickernell thanks, I updated the "instructions" above.

**Comment by chrisjcameron** [comment]
This is still an issue for new installs on macOS and closing the github issue just makes it harder to find the solution. The improved documentation helps but does not address the missing symlink.

**Comment by chrisjcameron** [comment]
It would be helpful if the macOS specific setup steps where linked under the Install section in https://github.com/jupyterlab/jupyterlab-desktop?tab=readme-ov-file

**Comment by mbektas** [comment]
@chrisjcameron there is now a [dedicated doc](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/cli.md#setting-up-the-jlab-cli-command) on CLI and there I am covering setting up CLI for macOS.

**Comment by mbektas** [comment]
I added a new feature with version [v4.1.2-1 ](https://github.com/jupyterlab/jupyterlab-desktop/releases/tag/v4.1.2-1) that lets you set jlab CLI from Settings dialog. see [this section](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#macOS-write-permission-issues) on troubleshooting document for instructions.
