### ISSUE TITLE
ntire app doesn't open after changing python path.....fedora silverblue flatpack

### ISSUE THREAD

**Issue by billyblackburn** [jupyterlab/jupyterlab-desktop#661]
## Reproduce

2. Click on '...'
3. Scroll down to '...'
4. See error '...'

## Context

- Operating System and version: 
- JupyterLab-Desktop version: 
- Installer: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).
[bly@localhost-live ~]$ flatpak run org.jupyter.JupyterLab 

[2:0531/221818.275771:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Gtk-Message: 22:18:18.482: Failed to load module "canberra-gtk-module"
Gtk-Message: 22:18:18.483: Failed to load module "canberra-gtk-module"
[2:0531/221818.499005:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[2:0531/221818.499036:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[bly@localhost-live ~]$ 

</pre>
</details>

**Comment by mbektas** [comment]
did you check this [section](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#Dealing-with-custom-environment-server-launch-errors) in Troubleshooting guide? are you trying to use a custom python environment?
