### ISSUE TITLE
The default install location for JupyterLabDesktopAppServer does not match the location documented in the user guide

### ISSUE THREAD

**Issue by tommcd** [jupyterlab/jupyterlab-desktop#677]
## Description

The Windows instructions in the user-guide:  
https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#windows-instructions
states that the default install locations for JupyterLab Desktop Server is
  C:\Users\<username>\AppData\Roaming\jupyterlab-desktop\jlab_server
however, the installer actually defaults to a different destination folder:
  C:\Users\<username>\AppData\Local\jupyterlabdesktopappserver

![JupyterLabDesktop Install location_Screenshot 2023-07-06 142522](https://github.com/jupyterlab/jupyterlab-desktop/assets/92704/6ec3f254-641e-40df-a172-936b3b38705c)

## Reproduce
Run: https://github.com/jupyterlab/jupyterlab-desktop/releases/latest/download/JupyterLab-Setup-Windows.exe

## Expected behavior

I expect the default destination folder used by the installer to match the documented location.

## Context

- Operating System and version: 
      OS Name:   Microsoft Windows 10 Enterprise
     OS Version: 10.0.19045 N/A Build 19045
- JupyterLab-Desktop version: 4.0.1-1
- Installer: .exe

**Comment by mbektas** [comment]
@tommcd I couldn't reproduce the issue. However, the good news is that I am in the process of removing this server installer with version [4.0.2-1](https://github.com/jupyterlab/jupyterlab-desktop/pull/679).

**Comment by tommcd** [comment]
> @tommcd I couldn't reproduce the issue. However, the good news is that I am in the process of removing this server installer with version [4.0.2-1](https://github.com/jupyterlab/jupyterlab-desktop/pull/679).

Thanks, I can confirm that the issue is resolved for me with version 4.0.2-1
