### ISSUE TITLE
Windows 10 - After installation, it does not prompt for Desktop App Server installation

### ISSUE THREAD

**Issue by rudolf-erdei** [jupyterlab/jupyterlab-desktop#678]
## Description

Versions older than 3.5.1-1 do not offer to install the **JupyterLabDesktopAppServer**, so the app is unable to start. This behavior is observed on Win10.

## Reproduce

 1. Remove older **JupyterLab**, as well as **JupyterLabDesktopAppServer**;
 2. Download any version after 3.5.1-1 and use the provided installer to install it;
 3. Start JupyterLab. An error is displayed and the app is not starting or working. It does not offer to install the **JupyterLabDesktopAppServer**.

## Expected behavior

The app crashes at first start, without offering to install the **JupyterLabDesktopAppServer**. 

## Context

OS: Windows 10
JupyterLab Version: any above 3.5.1-1
Installer: exe

**Comment by JasonWeill** [comment]
Per https://github.com/jupyterlab/jupyterlab-desktop/issues/677#issuecomment-1626877029, @mbektas reports that the Desktop app server installer is being removed with version 4.0.2-1.
