### ISSUE TITLE
Jupyter Lab Won't launch due to Javascript error

### ISSUE THREAD

**Issue by Tigger36** [jupyterlab/jupyterlab-desktop#684]
## Description

Upon opening JupyterLab I get an error message that says the following...
"A JavaScript error occurred in the main process

Uncaught Exception:
SyntaxError: Unexpected token '

## Reproduce

1. Open JupyterLab
2. See Error

## Expected behavior

I expected JupyterLab to load like it did yesterday

## Context

- Operating System and version:  --> Windows 11
- JupyterLab-Desktop version:  4.0.2-1
- Installer:  .exe

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).
There are no logs from today to post
</pre>
</details>

**Comment by mbektas** [comment]
can you please provide logs? you check the doc [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#Logs).

**Comment by mbektas** [comment]
closing since no response for long
