### ISSUE TITLE
After restart the kernel, there is a high probability that cells with only comments will get stuck while running

### ISSUE THREAD

**Issue by Shi-YuZhang** [jupyterlab/jupyterlab-desktop#687]
MacBook Pro Apple M2 13.4.1 (22F82)
JupyterLab Desktop 4.0.2-1
After restart the kernel, there is a high probability that cells with only comments will get stuck while running. This situation would not happen if i just connect the kernel. However, if i restart the kernek, i execute the cells with only comments, it got stuck.
<img width="532" alt="image" src="https://github.com/jupyterlab/jupyterlab-desktop/assets/74309824/db90a617-7051-447b-89e8-897ce81d5639">

**Comment by JasonWeill** [comment]
@Shi-YuZhang Thanks for your follow up! I'm going to close this issue, but you might want to open one against the variable inspector extension, or see if someone else has already done so.
