### ISSUE TITLE
Using exist remote server for local jupyter notebooks

### ISSUE THREAD

**Issue by dhtc** [jupyterlab/jupyterlab-desktop#697]
Hi, I express my gratitude for the delightful tools you have provided. Furthermore, I am curious to know if there exists a method to utilize remote Jupyter kernels for local notebooks. To illustrate, I envision initiating a JupyterLab server on the remote machine A, accessible via the URL http://A_address:8888, and subsequently selecting kernels from this server for my local notebooks. Although VScode supports this functionality, it often encounters obstacles during communication with the remote server. Notably, Google Colab also offers this capability through the selection of runtimes. Hence, it appears feasible to accomplish this endeavor.

**Comment by mbektas** [comment]
@dhtc You can look into using `--GatewayClient.url` launch argument as shown [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/user-guide.md#server-launch-arguments).
