### ISSUE TITLE
Unable to uninstall Jupyter Lab Desktop on Windows

### ISSUE THREAD

**Issue by fongbx** [jupyterlab/jupyterlab-desktop#698]
Hi, I have not been able to fully uninstall the past versions of Jupyter Lab Desktop on Windows as the JupyterLabDesktopAppServer application does not appear in my windows uninstaller. I have tried using third-party uninstallers as well and it is the same. Is there any other way to go about the uninstallation on Windows? Thanks much.

![image](https://github.com/jupyterlab/jupyterlab-desktop/assets/29515199/cb9eee15-43f3-47fb-b736-a2d95090a0f9)

**Comment by mbektas** [comment]
If you see invalid records in Windows Uninstaller you can clean using the instructions [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#Windows-uninstall-issues). If you have installation directories still around, you can manually delete.
After doing these, you can install a new version and your installation records should be corrected.
