### ISSUE TITLE
Invalid environment error with conda environment

### ISSUE THREAD

**Issue by tleyden** [jupyterlab/jupyterlab-desktop#704]
## Description

When trying to set a custom conda environment, I get this error:

<img width="1136" alt="Screenshot 2023-09-11 at 2 29 25 PM" src="https://github.com/jupyterlab/jupyterlab-desktop/assets/296876/483d0ed3-d0b3-4267-962b-47b3cafed52e">

## Reproduce

1. Download install the OSX (mac silicon) version of jupyterlab-desktop
2. Create a conda env with `conda create --name my-conda-env python=3.11`
3. Open JupyterLab desktop and create a new session in a directory
4. In the top right conda env picker menu (screenshot below) choose that conda env by navigating to `/opt/miniconda/envs/my-conda-env/bin` and choosing python
5. It gives an error about the conda env not being valid, but no other reasons about why it wasn't valid

<img width="263" alt="Screenshot 2023-09-11 at 2 31 23 PM" src="https://github.com/jupyterlab/jupyterlab-desktop/assets/296876/77763ecc-8b71-4567-b3e3-d75cd81be359">

## Expected behavior

It should be a valid conda environment, so I wouldn't expect an error.

## Context

- Operating System and version: OSX Ventura
- JupyterLab-Desktop version: 4.05-1
- Installer: .dmg

<details><summary>Troubleshoot Output</summary>
<pre>
[Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.](zsh: command not found: jupyter)
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>

</pre>
</details>

**Comment by krassowski** [comment]
@tleyden I edited your issue to remove some values from the logs, I hope this is ok. You may want to check if there is anything else that needs to be sanitised.

**Comment by tleyden** [comment]
Ok thank you.  I went ahead and deleted the logs.  Let me know if you can still look at the issue without them

**Comment by krassowski** [comment]
Is jupyterlab package installed in your environment? `my-conda-env` or `self-query-experiment`? If so what version?

**Comment by tleyden** [comment]
No it's not in my `base` conda env or in `self-query-experiment`, do I need to add it to either/both?

**Comment by krassowski** [comment]
Yes, as per https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#dealing-with-custom-environment-server-launch-errors. This really should be shown in the UI though, the current error is not useful at all - this looks like regression. Can you confirm that installing the package fixes it?
