### ISSUE TITLE
Jupyter Desktop App Won't Open Files

### ISSUE THREAD

**Issue by EngDM** [jupyterlab/jupyterlab-desktop#705]
## Description

Starting a few weeks ago, I could no longer double click my jupyter .ipynb files and have them open. All it does now is open to the main screen. I use this since I am pretty novice at setting up environments but use it for some open-source engineering tools. No clue how to solve this, originally I thought it was because I switched my network from being mapped to a drive but after re-mapping to the same drive it appears that is not the issue.

Send help.

## Reproduce

Double click .ipynb file

Profit?

## Expected behavior

I double click file, it opens and I can run my little programs.

## Context

- Operating System and version: 
- JupyterLab-Desktop version: 
- Installer: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by EngDM** [comment]
Update: I've tried updating, and now when I try to open it it says "Invalid Environment configured for project". Did uninstalling prior to updating screw me?

**Comment by JasonWeill** [comment]
@mbektas Have you seen this issue before? Suggestions about the error after updating?

**Comment by JasonWeill** [comment]
Hi @EngDM , thanks for your patience! We have a troubleshooting guide that might help you with this issue. Can you try the instructions in this section in particular? https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#Dealing-with-custom-environment-server-launch-errors

**Comment by JasonWeill** [comment]
@EngDM Any results after trying the troubleshooting guide?

**Comment by EngDM** [comment]
> @EngDM Any results after trying the troubleshooting guide?

Haven't had the opportunity. It's on a work computer and we are really busy rn, and I've found a semi work around that I can just load the web browser version and get it to work (although not as easily) so I haven't been able to take a day to fix the desktop version. Will keep you posted.

**Comment by mbektas** [comment]
@EngDM regarding `Invalid Environment configured for project` error:
1. do you have a custom Python environment setup for the directory you have the .ipynb file? That environment might not have `jupyterlab` Python package installed. You can check the [section](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#dealing-with-custom-environment-server-launch-errors) @JasonWeill mentioned.
2. is the problem reproducible when opening notebooks from other directories?

**Comment by JasonWeill** [comment]
@EngDM Any update regarding the questions Mehmet asked earlier?

**Comment by JasonWeill** [comment]
We haven't seen any update on this issue in some time, so I'm going to close it out. Please reopen if the issue persists. Thanks!

**Comment by EngDM** [comment]
@mbektas I tried running it from my Desktop and it works. It doesn't seem to want to run from my network drive. I tried installing an environment but I kind of got lost on what to do. I can move stuff to my desktop and copy back after I'm done, but I wish I had a better solution.

Sorry this was so late, I had to wait until a job came through that required me to use this to spend company time on it.
