### ISSUE TITLE
Development with m1 mac issues with create_env_installer:mac (osx-arm64)

### ISSUE THREAD

**Issue by snoolord** [jupyterlab/jupyterlab-desktop#711]
## Description
Following the [local development guide](https://github.com/jupyterlab/jupyterlab-desktop/blob/a438bf232ac929729a6822561d96ac200e420fd7/dev.md#local-development), I'm running into an issue with the `yarn create_env_installer:<platform>` step, receiving  the error: `Platform in lockfile 'osx-64' is not compatible with system platform 'osx-arm64'.` On further inspection it looks that all the `conda-osx-64.lock` is downloading all packages for osx-64 currently. 
Is there any devs using M1 macs that have a workaround to get conda working for local development? 

These  issues after installing conda via miniforge3 and all relevant conda dependencies.  

## Reproduce

1. Go to [developer documentation](https://github.com/jupyterlab/jupyterlab-desktop/blob/a438bf232ac929729a6822561d96ac200e420fd7/dev.md#developer-documentation)
2. Follow the instructions on an M1 macbook 
3. once at the `yarn create_env_installer:mac` step
```
yarn create_env_installer:mac
yarn run v1.22.19
warning ../../package.json: No license field
$ yarn clean_env_installer && conda-lock install --prefix ./env_installer/jlab_server ./env_installer/conda-osx-64.lock && conda pack -p ./env_installer/jlab_server -o ./env_installer/jlab_server.tar.gz
warning ../../package.json: No license field
$ rimraf ./env_installer/jlab_server.tar.gz && conda env remove -p ./env_installer/jlab_server -y
Traceback (most recent call last):
  File "/Users/winstonzhao/miniforge3/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 1477, in install
    do_validate_platform(lockfile_contents)
  File "/Users/winstonzhao/miniforge3/lib/python3.10/site-packages/conda_lock/conda_lock.py", line 195, in do_validate_platform
    raise PlatformValidationError(
conda_lock.errors.PlatformValidationError: Platform in lockfile 'osx-64' is not compatible with system platform 'osx-arm64'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/winstonzhao/miniforge3/bin/conda-lock", line 10, in <module>
    sys.exit(main())
  File "/Users/winstonzhao/miniforge3/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/Users/winstonzhao/miniforge3/lib/python3.10/site-packages/click/core.py", line 1078, in main
```

## Expected behavior
yarn create_env_installer:mac creates the local python installer and local development works. 

## Context

- Operating System and version: MacOS Ventura 13.4.1
- JupyterLab-Desktop version: 4.0.6-1
- Installer: local development? .dmg

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by mbektas** [comment]
thanks for reporting this @snoolord . since we are not bundling Apple silicon Python environment with the app yet (due to GitHub Actions limitation), we didn't add support in the local dev environment. I will work on the local dev environment support soon to address this problem.

**Comment by mbektas** [comment]
@snoolord we now have full support for Apple silicon on Mac with version 4.0.7-1. For local development you can use the new script `yarn create_env_installer:osx-arm64`
