### ISSUE TITLE
Remote CLI launch doesnt not persist session data

### ISSUE THREAD

**Issue by marius311** [jupyterlab/jupyterlab-desktop#722]
Just tried the new CLI remote launch in 4.0.7-1 which was exciting to streamline getting on my cluster, but it looks like it doesn't persist session data even for the same URL. So e.g. 

```bash
$ jlab https://jupyter.mycluster.com
# log in via my clusters web interface in the jupyterlab window
# close jupyterlab
$ jlab https://jupyter.mycluster.com
# have to log in again
```

which makes it actually _less_ streamlined than using the GUI "recent sessions" (which does correctly persist sessions). Would be great if CLI calls with the same URL persisted data.

**Comment by mbektas** [comment]
thanks for reporting this @marius311 . I found the source of the issue. I will push a fix soon.

**Comment by mbektas** [comment]
@marius311 I pushed a PR for the fix. You can use the installers which will be available [here](https://github.com/jupyterlab/jupyterlab-desktop/actions/runs/6669947022) until we release with a new version.

**Comment by marius311** [comment]
Just tested and it works, thanks for the lightspeed fix!
