### ISSUE TITLE
Unable to launch from the GUI by clicking the application's icon in Windows 11

### ISSUE THREAD

**Issue by Shi-YuZhang** [jupyterlab/jupyterlab-desktop#729]
I would like to launch the GUI by clicking the application's icon, however, no action or response has occurred. Hence, I wanted to know where is the path of log file related to the application launching so that I could check the reason.   

Version 4.0.5
windows 11

**Comment by mbektas** [comment]
@Shi-YuZhang you can check [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#Logs) for the location of the log files on your system.

**Comment by JasonWeill** [comment]
@Shi-YuZhang Any updates about the errors you see in the log?

**Comment by Shi-YuZhang** [comment]
Sorry for the late reply. I have checked the log file and found the problem was caused by the wrong python path.
