### ISSUE TITLE
Ctrl-W does nothing on Mac

### ISSUE THREAD

**Issue by bacook17** [jupyterlab/jupyterlab-desktop#732]
I'm using Jupyterlab Desktop (v 4.0.7-1) on a Mac (Sonoma 14.0, on Apple Silicon) and am unable to get the Ctrl-W keybinding to pass through to the terminal.

Specifically, Ctrl-W is a primary keybinding (kill-region) in Emacs, which I open from within a terminal in Jupyterlab.

I'm aware of the following issues / PRs related to capturing Ctrl-W (on Windows/Linux) or Cmd-W (on Mac) for closing the window and/or tabs.
https://github.com/jupyterlab/jupyterlab-desktop/issues/436
https://github.com/jupyterlab/jupyterlab-desktop/issues/630
https://github.com/jupyterlab/jupyterlab-desktop/pull/606

However, I believe the unintended consequence is that for Macs, BOTH Ctrl-W and Cmd-W get captured. And, even if the option is set to "Do Not Close", the commands are not sent on into the terminal.

If I use the browser-based version of Jupyterlab (Chrome 119.0.6045.159 on my Mac), then Ctrl-W is sent through to the terminal as expected.

**Comment by JasonWeill** [comment]
@mbektas Possibly related to #644, which maps CTRL+W or CMD+W? I would expect that on macOS, CTRL+W would be unmapped so it gets passed through to a terminal, although @bacook17 is finding that CTRL+W isn't getting propagated at all.

**Comment by mbektas** [comment]
hi @bacook17 . It looks like the code lines you shared point to the bug. this line, should have been like
`((input.meta && process.platform === 'darwin') || input.control && process.platform !== 'darwin')`.
