### ISSUE TITLE
Wrong version on the release page

### ISSUE THREAD

**Issue by Helleeni** [jupyterlab/jupyterlab-desktop#775]
## Description

When trying to download version v4.1.2 (supposedly the latest release) the [page](https://github.com/jupyterlab/jupyterlab-desktop/releases) shows version v4.1.1. at the top, and when downloaded the version is actually v4.0.8. (that is the MacOS Arm versions are, others I couldn't test).

## Reproduce

1. Go to this page: https://github.com/jupyterlab/jupyterlab-desktop/releases
2. Download https://github.com/jupyterlab/jupyterlab-desktop/releases/download/v4.1.1-1/JupyterLab-Setup-macOS-arm64.dmg
3. Uninstall any previous version of JupyterLab
4. Install this version
5. Check the version of the package: 4.0.8.

## Expected behavior

Either 4.1.1. would be installed or 4.1.2. would be available for installation as mentioned here: https://medium.com/jupyter-blog/python-environment-management-in-jupyterlab-desktop-3b119c5811d9

## Context

- Operating System and version: MacOS Sonoma 14.1.1.
- JupyterLab-Desktop version: ?
- Installer: .dmg and .zip

**Comment by mbektas** [comment]
@Helleeni I double checked now to confirm that the latest version has the proper JupyterLab version (v4.1.1) bundled. Have you installed 4.0.8 version of the application before or are you using a custom Python environment yourself created before?

Please see [this section](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#after-jupyterlab-desktop-update-why-there-is-still-the-old-jupyterlab-web-application-version) (After JupyterLab Desktop update, why there is still the old JupyterLab Web Application version?) in troubleshooting doc.

**Comment by Helleeni** [comment]
Thank you and sorry for opening a defect for a wrong reason. Obviously there is then something in my environment that I don't understand. I'm using conda to manage my Python environments. I'll try to follow the instructions on the linked page and figure out why I don't seem to get the right version opened. The browser version of Jupyter Lab works OK. And thank you guys working on this amazing tool.
