### ISSUE TITLE
Can jupyterlab-desktop be made into a portable version?

### ISSUE THREAD

**Issue by angelfish0808** [jupyterlab/jupyterlab-desktop#785]
Can jupyterlab-desktop be made into a portable version so that it can be used out of the box without installation and deletion is also very convenient, thanks!

**Comment by EricHUANG970823** [comment]
upvote! Jupyterlab desktop installer requires administrator permission, which is inconvenient in some cases. Portable version or version under user permission is a desirable choice.

**Comment by JasonWeill** [comment]
@angelfish0808 @EricHUANG970823 Thank you for your contribution! We have #307, which already covers this enhancement; let's keep the conversation going there.
