### ISSUE TITLE
Document TOC in Zen mode?

### ISSUE THREAD

**Issue by fperez** [jupyterlab/jupyterlab-desktop#795]
First, huge thanks for the new release and the new UI modes! I discovered them yesterday on update before even seeing the blog post, and loved it!

I do have one request/suggestion: while I love Zen mode, one thing that unfortunately makes it a non-starter for me is the loss of the TOC. When I'm focused on a single notebook (the whole point of Zen mode), one of the most important/useful things for me to have is easy navigation throughout my document's structure, and not by scrolling. For that, the TOC is absolutely critical, and it is for me one of the most valuable features we have in Lab today. It helps me stay in the flow of the document by quickly going to the part of the analysis/narrative I need.

I suspect it's a bit tricky from a UI perspective to offer it in Zen mode if you've entirely suppressed the left side panel, but I still think it would be worth exploring.

Otherwise congrats on the release/blog post and thanks for the great work!  I am using it more and more regularly as my main Jupyter UI instead of the web app!

**Comment by mbektas** [comment]
Thanks for the feedback @fperez ! I will add an option to enable TOC in Zen Mode. I thought of possibly enabling other widgets (status bar / file explorer (instead of TOC)) in Zen Mode but Single Document Mode looks better fit for those use cases.

**Comment by fperez** [comment]
Agreed @mbektas - I could go either way on the status bar (I can see it being useful even in zen mode and not distracting most users). But I totally think the file panel should stay out: this is precisely a desktop app, where people have a "real" file manager lying around from their OS (and typically a better one than ours), so it makes sense to delegate that task to the Desktop OS, and let our tools focus on one task: Jupyter.
