### ISSUE TITLE
Julia Interact Widgets not working

### ISSUE THREAD

**Issue by paulnakroshis** [jupyterlab/jupyterlab-desktop#796]
## Description

Julia Interact widgets are not displaying in Jupyterlab desktop.

## Reproduce
This is an example of a @manipulate slider which doesn't work with my Jupyterlab desktop installation:

using Plots
using Interact

u(x, t) = 1/2 * (sin(x + t) - sin(t - x))

x = 1:0.01:5
@manipulate for tᵢ in 0:0.1:1
    y = [u(x[i], tᵢ) for i in 1:length(x)]
    plot(x, y)
end
In the output cell only a plot can be seen, but the slider doesn't show up. 
I do get the following warning:
┌ Warning: attempting to remove probably stale pidfile
│   path = "[/Users/hiddenusername/.jlassetregistry.lock](http://localhost:50982/Users/hiddenusername/.jlassetregistry.lock)"
└ @ Pidfile [~/.julia/packages/Pidfile/DDu3M/src/Pidfile.jl:260](http://localhost:50982/~/.julia/packages/Pidfile/DDu3M/src/Pidfile.jl#line=259)

## Expected behavior

I expected a plot with a slider to allow me to manipulate the plot.
## Context

- Operating System and version: MacOS 14.4
- JupyterLab-Desktop version: Version 4.1.4-1 (4.1.4-1)
- Installer: .dmg

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by mbektas** [comment]
@paulnakroshis can you test it with the web app to confirm that it is an issue specific to Desktop app or not. [here](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#launching-jupyterlab-server-manually) are the instructions. also checkout [this](https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#Detecting-if-an-issue-is-specific-to-JupyterLab-Desktop-or-not).

**Comment by paulnakroshis** [comment]
Thanks—I’ll get to this when possible…swamped grading papers now:-(

-p

Paul Nakroshis
Chair & Associate Professor
 
 
Department of Physics, Univ. of Southern Maine
 
96 Falmouth Street, PO Box 9300, Portland ME 04103
 
***@***.*** | mainesight.com | paulnakroshis.github.io
 
+1.207.780.4158 | +1.207.449.7531 | portlandphysics.me

**Comment by JasonWeill** [comment]
@paulnakroshis Have you tried the web app with this case? Thanks!

**Comment by JasonWeill** [comment]
@paulnakroshis Any update regarding this?

**Comment by paulnakroshis** [comment]
> @paulnakroshis Any update regarding this?

Hi Jason,
In jupyterlab desktop, if I open a terminal and type 
> jupyter lab

I obtain the following error:

```
Traceback (most recent call last):
  File "/Users/paulnakroshis/Library/jupyterlab-desktop/jlab_server/bin/jupyter-lab", line 6, in <module>
    from jupyterlab.labapp import main
ModuleNotFoundError: No module named 'jupyterlab'
```

I am using the most recent version of Jupyterlab-desktop on an M2 MacBook Pro and using the bundled python environment:

```
% which python
/Users/paulnakroshis/Library/jupyterlab-desktop/jlab_server/bin/python
```

Any thoughts?
-p

**Comment by JasonWeill** [comment]
Have you tried installing JupyterLab separately from JupyterLab Desktop, such as in a separate Conda environment? If so, does this issue recur?

**Comment by JasonWeill** [comment]
@paulnakroshis Any update on whether this issue is reproducible in JupyterLab (without the Desktop app)? If you can reproduce it without Lab Desktop, we should probably move this to https://github.com/jupyterlab/jupyterlab.

**Comment by JasonWeill** [comment]
@paulnakroshis I haven't received updates from you about this issue, so I'm going to close it. If you can reproduce the problem in JupyterLab by itself (not just in JupyterLab Desktop) please open an issue here: https://github.com/jupyterlab/jupyterlab/issues/
