### ISSUE TITLE
Ctrl-Z shortcut does not work for jupyterlab desktop v3.6.3-2 and after

### ISSUE THREAD

**Issue by Wickdhub** [jupyterlab/jupyterlab-desktop#804]
## Description

The undo shortcut on a french laptop does not work after de 3.6.3-2 version. Instead it closes my window. 

If I disable ctrl+ w behavior, nothing happens

Undo Still works if I rebind the shortcut with other keys or if I use the undo in edit menu

I guess that is because z on azerty is on the same spot as w in the qwerty

## Expected behavior

Undo correctly 
## Context

- Operating System and version: 
- JupyterLab-Desktop version: 
- Installer: 

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by JasonWeill** [comment]
@Wickdhub Thanks for opening this issue! Which versions have you tried? (Have you tried any 4.0.x or 4.1.x release?) What OS and version are you running? Does this happen with JupyterLab when run on its own, or is it specific to JupyterLab Desktop? Thanks!

**Comment by Wickdhub** [comment]
I have tried all versions after the 3.6.3-2 I believe, including 4.0.x and 4.1.x yes.

I'm running on Windows 10.

I'm pretty sure that's specific to jupyterlab desktop because my jupyterlab version do not change but works correctly on 3.6.3-1 

Thanks for your help

**Comment by JasonWeill** [comment]
@Wickdhub Thanks for your response! Issue #709 covers the case of CTRL-Z not working on a French AZERTY keyboard. Let's continue the conversation there.
