### ISSUE TITLE
Jupyter-lab 4.15-1 refuse to write the character "}"

### ISSUE THREAD

**Issue by oliviermarti** [jupyterlab/jupyterlab-desktop#812]
## Description

Jupyter-lab 4.15-1 refuse to write the character "}"

It works only if there is no non-blank character before the cursor on the line.

## Context
- Operating System and version:  Mac OS 14.4.1 Intel Mac
- JupyterLab-Desktop version: 4.1.5-1
- Installer: automatic upgrade by Jupyter Desktop (with first install from dmg)

**Comment by krassowski** [comment]
Please see https://github.com/jupyterlab/jupyterlab/issues/15744#issuecomment-1999433752

**Comment by JasonWeill** [comment]
Closing in favor of JupyterLab issue @krassowski linked above — thanks!
