### ISSUE TITLE
How do I use it in the python2.7 environment?

### ISSUE THREAD

**Issue by Dumbliidore** [jupyterlab/jupyterlab-desktop#839]
## Description
I want to use the python environment of arcgis, but there is "File selected is not a python binary" when I add existing python env.

## Reproduce
1. Open jupyterlab destop
2. Open Manage Python environments
3. Click Add existing and select the python env of arcgis
4. See error "File selected is not a Python binary"

## Context
- Operating System and version: Windows 10
- JupyterLab-Desktop version: latest
- Installer: .exe
- Python version of arcgis: 2.7

**Comment by JasonWeill** [comment]
Just to clarify, are you using ArcGIS Pro 2.7 or Python version 2.7? The latter is no longer supported. As for the former, which version of Python does this environment use?

**Comment by Dumbliidore** [comment]
> Just to clarify, are you using ArcGIS Pro 2.7 or Python version 2.7? The latter is no longer supported. As for the former, which version of Python does this environment use?澄清一下，您使用的是 ArcGIS Pro 2.7 还是 Python 2.7 版本？不再支持后者。至于前者，这个环境使用的是哪个版本的Python？

Thank you for your answer, my python version is 2.7.
