### ISSUE TITLE
Conflict with rye python shims

### ISSUE THREAD

**Issue by bluss** [jupyterlab/jupyterlab-desktop#850]
## Description

In some [Rye](https://rye.astral.sh/)-using setups:

- Starting jlab succeeds. Opening notebooks inside the jlab interface works, after selecting appropriate jupyterlab venv
- Starting jlab notebookfile.ipynb **fails to start**. Dragging notebook to jlab window fails to open it the same way
  The error there is "Jupyter server process terminated before the initialization completed"

## Reproduce

1. Install Rye
2. ~/.rye/shims/python is now the first python on $PATH
3. Install jupyterlab-desktop
4. Install jupyterlab as python -m pip --user  (~/.rye.shims/python user site environment) (Python 3.10)
5. Install jupyterlab separately in a more appropriate virtual environment "V"  (Python 3.12)
6. Open jlab. Select that you use virtual environment "V" in the drop down in the top of the window
7. Now try to open a notebook file using jlab notebookfile.ipynb

## Expected behavior

jlab notebookfile.ipynb should maybe use the same selected virtual environment "V" that the user interface otherwise defaulted to.

jlab should not try to launch ~/.rye/bin/python as if it is a virtual environment, because it's not (it's a shim for a system interpreter).

## Context

The following appeared in the debug log, and this obviously fails, because that activate script does not exist:

```
source "/home/ulrik/.rye/bin/activate"
```

This is quite suspicious - the "system python path" is "$HOME/.rye/bin/python" and jlab is treating that as if it's a .venv (it's not, that shim will reexecute to /usr/bin/python which is python 3.10)

- Operating System and version: Ubuntu 22.04
- JupyterLab-Desktop version: 4.2.1-1
- Installer: .deb
- platform: linux (x86_64)

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

### Suggested Workaround

Make sure jupyter is *not* installed in any system interpreter's user site.

Thanks for the nice work on jupyterlab desktop :)

**Comment by JasonWeill** [comment]
This looks like the same error message as in #847, although that issue mentions Windows 10 and doesn't mention Rye.

**Comment by JasonWeill** [comment]
Out of curiosity, if you're not using Rye, do you see the same "Jupyter server process terminated before the initialization completed" error? If so, this might effectively be a duplicate of #847.

**Comment by bluss** [comment]
![bild](https://github.com/user-attachments/assets/b6c14183-f0da-4116-a33e-f9ed3bc7133a)
It's a very generic error message, I'm not surprised if separate problems can lead to the same place.

If I don't use rye I don't have the problem.

**Comment by bluss** [comment]
When this happens I can grab the launch script from the log - something like /tmp/jlab_desktopfiS6Bd/launch.sh - and that script starts jupyterlab correctly when I run it. So that's mysterious.

**Comment by bluss** [comment]
I can see now later that the `source "/home/ulrik/.rye/bin/activate"` is a red herring. (or maybe not?) but even cases that work print commands like source "/usr/bin/activate"  - another path that doesn't usually exist. (Which by the way is a correctness or even safety hazard - one can't just rely on that path not existing. It could be something that wrecks the execution.)

**Comment by bluss** [comment]
I'll abandon this bug as uv has taken over all rye's features, and I do not use rye anymore.
