### ISSUE TITLE
Python3 kernel and notebook not valid

### ISSUE THREAD

**Issue by luigallucci** [jupyterlab/jupyterlab-desktop#859]
Hi all!

I was using jupyterlab desktop for a while...suddenly, after an update probably, it started to not found the python environment so I'm not able anymore to use a python3 kernel. Even if I use the bundled environment after I started a notebook with python3 kernel, is said: [Errno 2] No such file or directory: '/Users/lgallucc/miniforge3/bin/python'

The problem is that I have any type of folder in this path and I don't know from where it is taking the path because no where in the settings I indicate this.

Can you help me?

**Comment by JasonWeill** [comment]
@luigallucci Thanks for opening this issue! I'm not sure exactly why you're seeing this error. If you reinstall miniforge, then also restart your terminal, do you continue to see this error? Is there something in your shell's setup script that's adding the above mentioned directory to your PATH or any other environment variable?

**Comment by luigallucci** [comment]
I did reinstall of miniforge recently, but nothing is changing...and no, I'm actually from a Mac, and nothing in my zshrc is pointing to that path. There is a setting folder where I can give him a different path for the kernel?

**Comment by luigallucci** [comment]
Hi!

I solved the problem, checking from the terminal `jupyter kernelspec list` to check where the kernel file was located and modifying the file containing the path...to be onest, I still don't know from where it took this path, but now is solved :)
