### ISSUE TITLE
Having installed library in macOS terminal via pip but JupyterLab desktop report none of it

### ISSUE THREAD

**Issue by TomHsiung** [jupyterlab/jupyterlab-desktop#860]
## Description

Hello, sir or madam

Thank you for creating this Github community for JupyterLab. I love its support for SAS, Python, and R languages, which helps me to process raw data faster. But today, I tried to some Excel editing stuff which requires the library of openpyxl in the JupyterLab Desktop 4.2.1-1 on macOS (Intel). I had already installed the library of openpyxl via pip in the macOS terminal app and I do have python 3.11 installed, which I downloaded from Python official website.

The JupyterLab Desktop says

> ---------------------------------------------------------------------------
> ModuleNotFoundError                       Traceback (most recent call last)
> Cell In[1], line 3
>       1 import pandas as pd
>       2 import numpy as np
> ----> 3 from openpyxl import load_workbook
>       4 from openpyxl.utils.dataframe import dataframe_to_rows
> 
> ModuleNotFoundError: No module named 'openpyxl'

I think I need to connect the installed python via terminal and the JupyterLab desktop but I don't know how I should. Many thanks and looking forward to your reply.

**Comment by TomHsiung** [comment]
Thank you, Jason. After some investigation, I decided to use Google's Colab as my online code notebook. I heard that Colab is based on JupyterLab too.

**Comment by JasonWeill** [comment]
I understand. Closing this issue, but if you decide to try JupyterLab Desktop again and find any other issues, please open new ones. Thanks for your contribution!
