### ISSUE TITLE
JupyterLab running as a service, or, a daemon

### ISSUE THREAD

**Issue by TomHsiung** [jupyterlab/jupyterlab-desktop#861]
I know I can install JupyterLab on my Mac and launch it in the terminal. But, can we install JupyterLab on a Ubuntu server and access it remotely? We want to manage it like other service, for example, apache2, bind, or strongSwan. We would like to manage it via the systemctl commands. Also, we would like to custom its service port, the IP it is listening on.

I appreciate your work on this great coding notebook. Many thanks.

Tom

**Comment by JasonWeill** [comment]
@TomHsiung Thanks for opening this issue! It looks like what you're asking for is available in Jupyter Server: https://jupyter-server.readthedocs.io/ . Jupyter Server lets you run a hosted instance, which you can connect to over a network. If you find issues with Jupyter Server, you can open an issue here: https://github.com/jupyter-server/jupyter_server/issues . We also have a Discourse forum: https://discourse.jupyter.org/

**Comment by TomHsiung** [comment]
Great! Many thanks, Jason. I will take a look at those webpages you mentioned.
