### ISSUE TITLE
JupyterLab-Desktop installed on Fedora 40 via SNAP, stops working after a dnf update

### ISSUE THREAD

**Issue by Ernie-07** [jupyterlab/jupyterlab-desktop#869]
## Description

Attempts to use the JupyterLab-Desktop Notebook fail with a blank window.

## Reproduce6.10.8-200.

1. Follow instructions for a Fedora Snap install. All is well.
2.  Execute dnf update going from kernel 6.10.8-200 to kernel  6.10.9-200 several days later.
3.  Failure which requires BOTH JupyterLab-Desktop and SNAP removal and reinstallation.

1. Again, follow instructions for a Fedora Snap install. All is well.
2.  Execute dnf update going from kernel 6.10.9-200 to kernel  6.10.10-200 several days later.
3.  Failure which requires BOTH JupyterLab-Desktop and SNAP removal and reinstallation.

## Expected behavior

I expected components/dependencies associated with JupyterLab-Desktop to be upgrade automatically during a dnf upgrade.
## Context

Linux fedora 6.10.10-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:26:09 UTC 2024 x86_64 GNU/Linux
JupyterLab Desktop v4.2.5-1
Installer SNAP -- yuck  this is not the first issue that I have had associated with a snap installation

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the terminal inside of JupyterLab Desktop here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Browser Output (required for interface issues after loading)</summary>

<pre>
Paste the output from the DevTools JavaScript console here, if applicable.

</pre>
</details>

<details><summary>Logs (required for issues with loading, server and startup)</summary>

<pre>
Paste the logs from the `main.log` file here (optionally also from `renderer.log`).

</pre>
</details>

**Comment by JasonWeill** [comment]
@Ernie-07 Thank you for opening this issue! When you try to load JupyterLab Desktop after a kernel update, do you see any errors in the logs along with a blank window? You can find info about logs in the JupyterLab Desktop docs here: https://github.com/jupyterlab/jupyterlab-desktop/blob/master/troubleshoot.md#Logs

Start application from command line as `jlab --log-level debug`, wait, then check in ~/.config/jupyterlab-desktop/logs/main.log . Do you see any messages?

**Comment by Ernie-07** [comment]
Thanks for the fast response.
After two failures with two unrelated snap installs, I have installed
JupyterLab-Desktop via 'JupyterLab-Setup-Fedora-x64.rpm'. If I have further
issues, I will follow your suggestions and return appropriate feedback.

Ernie-07

**Comment by JasonWeill** [comment]
@Ernie-07 Thanks for the update! I'm going to close this issue for now, but if you see it again, please reopen this or open a new issue, including both the error and any log data. I appreciate your contribution.
