### ISSUE TITLE
No "+" for new tabs since Version 4.1?

### ISSUE THREAD

**Issue by D-HH** [jupyterlab/jupyterlab-desktop#873]
I updated from version 4.0.? to 4.2 and there is no "+" for new tabs any more. I do not see any reasonable reason to remove it. I had to go back to the older version since this is quiet uncomfortable to use know. 

Still very helpful free application! But (for my use) much worse due to the update

**Comment by krassowski** [comment]
This has NOT been removed, it is still in there. It might be a version mismatch or disabled core plugin or a third-party extension disabling it. Can you post a screenshot demonstrating what you see and the version info dialog open (Help → About JupyterLab)?

**Comment by D-HH** [comment]
Thanks for the quick response! 
I added Screenshots from the newest version and my old version. Weirdly, when I use the old version I get the note I should update, but when I go to help - About JupyterLab it still shows "Version 4.2.5"

![Help](https://github.com/user-attachments/assets/c40cef71-fc99-48ed-be95-203f0d1df85c)
![Old_Version](https://github.com/user-attachments/assets/cfa87fee-5329-43b8-b18c-540bd95d9f7b)
![Version_4 2](https://github.com/user-attachments/assets/76d0809e-7e79-4225-80b4-79908f68dd7e)

**Comment by krassowski** [comment]
You have "Simple" mode enabled and some sidebars disabled, so "Zen mode" in JupyterLab Desktop. You can click on the hamburger menu in top right corner (next to "conda: jlab_server") and select another option from "UI Mode" list.

Alternatively you can click on "View" → "Appearance" → "Simple Mode" to toggle it, along with the visibility of side panels.

I think the "Zen mode" is the default when opening a single notebook, you can change it in the settings:

![image](https://github.com/user-attachments/assets/0513a36d-cd23-4e76-b68e-be35bbfe36c1)

**Comment by D-HH** [comment]
Thanks a lot! Now everything works perfectly fine!

**Comment by JasonWeill** [comment]
Thank you @krassowski for helping @D-HH with this issue! Closing, as it doesn't seem to be an issue in Lab Desktop code. Please open another issue if you find anything else wrong. Thanks for your contribution!
