### ISSUE TITLE
Improve robustness of Jupyter server error handling

### ISSUE THREAD

**Issue by lucbouchard1** [jupyterlab/jupyterlab-desktop#98]
Right now, the code that handles errors from the spawned Jupyter server is not particularly robust. It should be improved to a) cleanly handle Jupyter server anomalies and b) properly inform the user when something goes wrong with the Jupyter server. 

I began implementing this with #96, but we can make a lot more improvements.

**Comment by krassowski** [comment]
This was tackled in #339. Ideally we would also display logs in addition to the error message.

**Comment by mbektas** [comment]
closing since there were several enhancements already implemented
